### PR TITLE
i18n: Revert translations on keywords

### LINKED ISSUE #621: [2.1] i18n: getting KeyError after new translations
```
$ cura_app.py 
2016-01-29 17:12:03,167 - DEBUG - Loaded a mesh with 22626 vertices                                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                                          
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 254, in getSceneBoundingBoxString                                                                                                                                     
    return self._i18n_catalog.i18nc("@info", "%(width).1f x %(depth).1f x %(height).1f mm") % {'width' : self._scene_boundingbox.width.item(), 'depth': self._scene_boundingbox.depth.item(), 'height' : self._scene_boundingbox.height.item()}                                                                                                                                                                                                                                         
KeyError: 'Breite'                                                                                                                                                                                                                          
```

Three more when opening an object: (same errors)
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 254, in getSceneBoundingBoxString
    return self._i18n_catalog.i18nc("@info", "%(width).1f x %(depth).1f x %(height).1f mm") % {'width' : self._scene_boundingbox.width.item(), 'depth': self._scene_boundingbox.depth.item(), 'height' : self._scene_boundingbox.height.item()}
KeyError: 'Breite'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 254, in getSceneBoundingBoxString
    return self._i18n_catalog.i18nc("@info", "%(width).1f x %(depth).1f x %(height).1f mm") % {'width' : self._scene_boundingbox.width.item(), 'depth': self._scene_boundingbox.depth.item(), 'height' : self._scene_boundingbox.height.item()}
KeyError: 'Breite'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 254, in getSceneBoundingBoxString
    return self._i18n_catalog.i18nc("@info", "%(width).1f x %(depth).1f x %(height).1f mm") % {'width' : self._scene_boundingbox.width.item(), 'depth': self._scene_boundingbox.depth.item(), 'height' : self._scene_boundingbox.height.item()}
KeyError: 'Breite'
```

### PR DESCRIPTION
**Pull request by thopiekar**
* Because these keywords got translated the code can't replace them with values.
* Basicly the idea having these keywords in translation files is just to change the order of them (according to the culture and the region, where another order would be expected).
-> So reverted the translated keywords for german and french.

Fixes #621

### CODE REVIEW

**Comment by thopiekar** [comment]
PS: Sorry for the auto-corrections, which my editor does here.

**Comment by thopiekar** [comment]
Now found some time and tested my own fix.
It works fine, but still hangs at #622

**Comment by Ghostkeeper** [comment]
Yeah the socket error is my top priority right now.
Looks good. I can see why the translators tried to translate those keys. Good catch!

**Comment by thopiekar** [comment]
Thanks. Hope you can get it fixed easily.
Please remember that I already added another PR for the missing message in
CuraEngine.

**Pull request merged**
