### PR TITLE
TPU FAbtotum's profiles

### PR DESCRIPTION
**Pull request by krios-fabteam**
Added profiles for TPU
Improvements to existing profiles

### CODE REVIEW

**Comment by krios-fabteam** [comment]
Are the files in quality folder the wrong place to put  "_speed_print_" value?

**Comment by nallath** [comment]
For our reference; CURA-4955

**Comment by Appesteijn** [comment]
I'm only missing the TPU profiles in the material drop down. Do they still need to be added to the machine definition? (not sure tho)

**Comment by Appesteijn** [comment]
Do you still want us to merge this?

**Comment by krios-fabteam** [comment]
Hi @Appesteijn if you are talking with us the answer is "yes" :)

**Comment by Appesteijn** [comment]
@krios-fabteam could you then see if it is correct that TPU profiles miss in the material drop down?

**Comment by krios-fabteam** [comment]
Hi @Appesteijn ,
what I have to do to check it?

**Comment by Appesteijn** [comment]
If you switch to your branch, add your printer, open the material selection dropdown. I didn't see TPU in here and I thought that it should be here.

**Comment by krios-fabteam** [comment]
I can see it

image

**Comment by Appesteijn** [comment]
Now I see it also, I had an old version of fdm_materials...

**Comment by krios-fabteam** [comment]
Great 👍

**Pull request merged**
