### PR TITLE
[master] Importing and using Logger correctly

### PR DESCRIPTION
**Pull request by thopiekar**
Usually we import Logger a different way across our code. Fixing this
kind of typo just keeps this convention.

### CODE REVIEW

**Comment by thopiekar** [comment]
Oh, btw. I guess it also should be called UM.Logger.Logger.log(*args) before, as the UM.Logger module includes a Logger class, which finally has .log(*args).

**Comment by fieldOfView** [comment]
@awhiemstra has recently introduced a new way of importing UM modules. Importing UM.Logger and using UM.Logger.log() should work. Also see ExtruderManager.py

**Comment by thopiekar** [comment]
I left ExtruderManager.py unchanged, because I thought you are still working on it.
I can review this file, too, if you like.

So are we going to change the way of importing the modules in general?

**Comment by fieldOfView** [comment]
> So are we going to change the way of importing the modules in general?

In general, I believe new code is supposed to use the new-style imports. But because we have been working towards a release, most of us did not change our habbits yet. This will likely change the coming week(s).

**Comment by nallath** [comment]
The "new" style imports are usefull for circular dependencies and having less issues with namespace polution.

**Comment by thopiekar** [comment]
Ok, if you like you can merge this. At least this would keep one coding style being used at the moment.

**Comment by thopiekar** [comment]
Closing this?

**Comment by fieldOfView** [comment]
Yup

**Pull request closed without merging**
