### PR TITLE
[master] Using UM.Platform for OS detection

### PR DESCRIPTION
**Pull request by thopiekar**
This is just cosmetics. It works the same as system.platform, but looks
better. Additionally "win32" might be misleading, as it sounds like we
are checking for Windows 32bit here.

### CODE REVIEW

**Comment by awhiemstra** [comment]
Hmm, I actually added the Platform class to UM a while ago to take care of this. It has a Platform.isWindows() method that will return True if we are on Windows.

**Comment by thopiekar** [comment]
Ok, will search for it and replace it.

**Comment by thopiekar** [comment]
Oops, there is a copy I made when switching between branches. Will remove it of course when I'm back home.

**Comment by awhiemstra** [comment]
According to Github there is a conflict, but feel free to merge this once you resolve that.

**Comment by fieldOfView** [comment]
This seems to have broken Cura on both windows and ubuntu
```
2016-06-15 15:47:32,715 - CRITICAL - ...\cura\CrashHandler.py (show [24]): An uncaught exception has occurred!
2016-06-15 15:47:32,718 - CRITICAL - ...\cura\CrashHandler.py (show [24]): Traceback (most recent call last):
2016-06-15 15:47:32,720 - CRITICAL - ...\cura\CrashHandler.py (show [24]):   File "cura_app.py", line 50, in <module>
2016-06-15 15:47:32,722 - CRITICAL - ...\cura\CrashHandler.py (show [24]):     app.run()
2016-06-15 15:47:32,723 - CRITICAL - ...\cura\CrashHandler.py (show [24]):   File "C:\Users\Aldo\Documents\Code Projects\UM\Cura\cura\CuraApplication.py", line 344, in run
2016-06-15 15:47:32,725 - CRITICAL - ...\cura\CrashHandler.py (show [24]):     self._platform = Platform(root)
2016-06-15 15:47:32,726 - CRITICAL - ...\cura\CrashHandler.py (show [24]): TypeError: object() takes no parameters
```

**Comment by awhiemstra** [comment]
And that is why unqualified imports are bad ^^

**Comment by thopiekar** [comment]
Got it! I redefined Platform from UM with UM.Scene :sob:

**Comment by fieldOfView** [comment]
Was this tested before merging?

**Comment by thopiekar** [comment]
I think so :eyes:
Just fixed that asap..

**Pull request merged**
