### PR TITLE
add 3ntr A4v2 & A4v3

### PR DESCRIPTION
**Pull request by StuSerious**
# _**Work in Progress!**_ New 3ntr printers!
The aim of this pull request is to add the A4v2 and A4v3 line of printers and to learn a bit of JSON and git as I go!
I don't know how many people will actually benefit from this PR or use Cura on these printers, since they come packaged with another slicer, but hey this is a learning opportunity and maybe there are others like me out there!

_NOTE: these are **very** work in progress, but since I have very little experience with both JSON and git I'm still making the pull request to receive advice and to version control the files, I hope that's not an issue!_

## A pic of the printers: 
A4v3 on top, A4v2 on the bottom:
image

___

### TODOs:
- [x] model baseplate
- [x] align the buildplate STL correctly
- [ ] learn git and JSON 🤣
- [ ] finish base and derivative machine overrides 
- [ ] add _unique_ qualities and profiles
- [ ] add images
- [ ] actually test these profiles against the CustomFFF ones

### CODE REVIEW

**Comment by StuSerious** [comment]
future self: files in qualities are the same as the global default ones, that's the reason why it's failing add TODO after overrides.

**Comment by Ghostkeeper** [comment]
The tests are failing because there are duplicate profile IDs. The filename of a profile is its ID. It needs to be unique among all profiles. So you can't use `extra_fast.inst.cfg` since that name is already used for the fallback profile (for printers that don't have specialised profiles).

**Comment by StuSerious** [comment]
@Ghostkeeper thanks for the tip!
Also, sorry for leaving this stale lately, I'm not currently working on-site due to CoVid. 
Development will pick up again as soon as I can get hands on with the printers once again (hopefully soon 🤞🏼)

**Comment by Ghostkeeper** [comment]
Well, we're not the best with that either. It's going to be fine, as long as the `setting_version` is kept up to date (which is currently still fine).

**Comment by StuSerious** [comment]
Closing this because I have since re-written everything in a better way, I'll get around to opening PRs when this and other printers and profiles are in a better state.

Sorry if I left this stale for a while, I kinda forgot it was still open 😅

**Pull request closed without merging**
