### PR TITLE
Fix rendering issues in Monitor Page

### PR DESCRIPTION
**Pull request by diegopradogesto**
I saw this many times before in macOS when connecting to a secondary screen. I added some missed renderType properties in the Labels in QML.

**Before**:
Screenshot 2019-04-30 at 11 35 12

**After**:
Screenshot 2019-04-30 at 11 32 54

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Can't we make a "UltimakerLabel" component that has all the right settings applied to it by default? That would prevent a lot of code duplication.

**Comment by diegopradogesto** [comment]
That would be a good idea.

**Comment by nallath** [comment]
I'd prefer having something like UM.Label {}, but yeah that makes sense. We've already been working on getting more of those default things into a re-usable component.

**Comment by fieldOfView** [comment]
It would be great if that UM.Label could automatically align itself to a whole pixel offset so all of that rounding fractional offsets in all QML won't be as critical anymore.

**Comment by ianpaschal** [comment]
Thanks for the assistance @diegopradogesto. I agree a component would be dandy and I will use them in the monitor tab if you guys build it, but this seems like a fine fix to me for the time being.

**Comment by ChrisTerBeke** [comment]
It's def out of scope for this PR

**Pull request merged**
