### PR TITLE
[5.0b1] Fix material "Print Settings" tab

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR fixes setting values on the Print Settings tab of the Materials pane of the preferences. Without this PR, changes will not be saved at all. This PR also disables the input fields on the Print Settings tab for "read-only" materials.

Fixes https://github.com/Ultimaker/Cura/issues/12155

### CODE REVIEW

**Review by nallath — APPROVED** [review]

**Comment by nallath** [comment]
CURA-9275

**Comment by Madmike-1337** [comment]
This is not fixed. Version 5.1.0 still does not save changes without deliberate user action that is not just  closing the window.  I have been wrestling with this since cura 2.3 or something. A save button or apply button won't kill you. Neither would a note that tabbing to another pane is needed to put the users in control of the interface.

**Comment by fieldOfView** [comment]
@Madmike-1337, the PR fixed a specific issue. That does not mean that there are no remaining issues. There is no use complaining about #11941 here.

**Comment by nallath** [comment]
> A save button or apply button won't kill you. 

A normal way of reporting a bug would similarly also not kill you ;)

**Comment by Madmike-1337** [comment]
> @Madmike-1337, the PR fixed a specific issue. That does not mean that there are no remaining issues. There is no use complaining about #11941 here.

They are the same issue, ergo not fixed.

**Comment by Madmike-1337** [comment]
> > A save button or apply button won't kill you.
> 
> A normal way of reporting a bug would similarly also not kill you ;)

You're correct, it wouldn't kill me.  It also doesn't fix the problem. Sorry for riling feathers.

**Comment by fieldOfView** [comment]
That is not the point. This, where you are posting, is _not_ an issue report. It is a pull request for changes I proposed to Cura, which fixed a different underlying issue (#12155). What you are talking about is already reported as an issue in #11941. 

Unless you think the changes made in this pull request broke things, discussion about your issue here is useless.

**Comment by Madmike-1337** [comment]
> That is not the point. This, where you are posting, is _not_ an issue report. It is a pull request for changes I proposed to Cura, which fixed a different underlying issue (#12155). What you are talking about is already reported as an issue in #11941.
> 
> Unless you think the changes made in this pull request broke things, discussion about your issue here is useless.

Thank you for correcting me on this misconception.

**Pull request merged**
