### PR TITLE
CL-1348 Enable cloud actions

### PR DESCRIPTION
**Pull request by ianpaschal**
Contributes to CL-1348

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Not sure if this is done yet, but simply enabling the UI elements won't make it work. The functions also need to be implemented in the CloudOutputDevice.

**Comment by ianpaschal** [comment]
Are you sure? I didn't commit this without checking; I was able to delete and move to top as expected.

**Comment by ChrisTerBeke** [comment]
I guess you were still connected locally then behind the scenes. When you left the print job action endpoints weren't even deployed in the cloud yet :)

**Comment by diegopradogesto** [comment]
@ianpaschal , can we close this PR? The internal ticket says "Unresolved" but maybe it was changed to another internal reference.

**Comment by ChrisTerBeke** [comment]
Working on a new PR, closing this one.

**Pull request closed without merging**
