### PR TITLE
# Pause at height for FlyingBear Ghost

### PR DESCRIPTION
**Pull request by firexx**
# * tested with FBG4S
# * FBG4S don't make a pause on M0 command. but M25 can be used instead.
# * some default parameter changes that make more sense for this printer

### CODE REVIEW

**Comment by firexx** [comment]
can't understand how add a new PostProcessing script can cause the beak of build cura...

**Comment by fieldOfView** [comment]
Note that there's an effort going on to unify all Pause at Height scripts into a single one, with a dropdown to select which method to use. Using an `M25` command is one of those methods.

See https://github.com/Ultimaker/Cura/pull/7201

**Comment by firexx** [comment]
it can be also done, but not simple understandable for all users. not all are familiar with g-code commands. but your way is more logical for me also. it was a first idea to implement so like you suggest.

**Comment by fieldOfView** [comment]
For now, the BQ version uses M25.

**Comment by firexx** [comment]
this inserts the M25 on wrong place. so the pause is directly after heating bed and before heating hot end. that is completely wrong but this pause works :-D

what ist about to read also the scripts from users/<username>/AppData/Roaming/cura/<version>/plugins/PostProcessing/scripts

so the plugin for FlyingBear would install own script and i don't have to pull request to whole cura- where the most users of cura don't need that script.

**Comment by fieldOfView** [comment]
> also the scripts from ...

Try `%APPDATA%\cura\"version"\scripts`

**Comment by firexx** [comment]
cool that's work. thank you very much, i will now make a pull request to MKS plugin! Very nice!

**Pull request closed without merging**
