### PR TITLE
Include OctoPrint plugin

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR merges the OctoPrintPlugin from https://github.com/fieldofview/OctoPrintPlugin.git. This plugin allows the user to print directly to an OctoPrint instance, much like how you can print to an UM3.

This plugin is used by a lot of Cura users. The Lulzbot Edition of Cura2 will ship with this plugin, and so will future versions of the PPA distribution. This leaves the main distribution crippled in comparison.

See https://github.com/Ultimaker/Cura/issues/1489#issuecomment-284398011 for discussion

### CODE REVIEW

**Comment by fieldOfView** [comment]
Alternatively this could be done in cura-build; let me know what is preferred

**Comment by Ghostkeeper** [comment]
Willing to try again? Well, so am I. Devs, see CURA-3761.

**Comment by fieldOfView** [comment]
For clarity, I actually think https://github.com/Ultimaker/cura-build/pull/119 might be a better idea.

**Comment by fieldOfView** [comment]
Closing this one, in favor of https://github.com/Ultimaker/cura-build/pull/119, to keep the Cura issue queue clean.

**Pull request closed without merging**
