### PR TITLE
Create alfawise_u30.def.json

### PR DESCRIPTION
**Pull request by NicolasNSSM**
I basically took the base from [Samuel Pinches U20 def](https://github.com/Ultimaker/Cura/blob/master/resources/definitions/alfawise_u20.def.json) and compiled it with the old Cura .ini given by Alfawise on the SD card.

I don't know anything about Cura config so double check it real good!

I'll test it further tomorrow as for now I don't have access to my printer: TESTED OK

### CODE REVIEW

**Comment by NicolasNSSM** [comment]
It works!

image

**Comment by pinchies** [comment]
Thanks for implementing this for the U30. You may also want to change the start gcode slightly if you have problems with the prime line hitting the bed clips. You can change the X60 and X100 move commands to be Y60 and Y100 commands instead. I've just updated the U20 file here: https://github.com/Ultimaker/Cura/pull/5093

**Comment by NicolasNSSM** [comment]
@pinchies I don't have any X60 or X100 in my command as there wasn't any in the `.ini` file

**Comment by pinchies** [comment]
> @pinchies I don't have any X60 or X100 in my command as there wasn't any in the `.ini` file

Maybe have a look in this file, so you can compare the start gcode: #5093

**Comment by NicolasNSSM** [comment]
Of course I did, I saw what you updated but as I don't have any of these in my code and I don't even know what it means, I'm not sure what to do?! Just copy your updated part without deleting anything?
Honestly, if you know how to do it, you'll be faster pushing a commit over it! :D

**Comment by pinchies** [comment]
Here you go - I don't know how to create a new pull request over yours, this is the one file that needs to be changed to add a prime line. Would you like to try to replace the contents of your file with this one please?
[alfawise_u30.def.json.zip](https://github.com/Ultimaker/Cura/files/2720502/alfawise_u30.def.json.zip)

**Comment by NicolasNSSM** [comment]
Done! ;)

**Comment by nallath** [comment]
For our reference; CURA-6081

**Pull request merged**
