### PR TITLE
CURA-6978/Added the project name in Window Title

### PR DESCRIPTION
**Pull request by DonExo**
Added the project name in Window Title.

### CODE REVIEW

**Comment by BagelOrb** [comment]
Idea is conform almost any other program, format corresponds with how other programs do it as well.

Code looks good; simple oneliner without any risk.

I vote to merge this right away.

**Comment by DonExo** [comment]
FYI @fieldOfView , since you are the creator of https://github.com/fieldOfView/Cura-VersionInTitlebarPlugin

**Comment by fieldOfView** [comment]
"there's a plugin for that"

It would be nice if this could use the application display name (Application.getApplicationDisplayName()) instead of hardcoding Ultimaker Cura.

**Comment by BagelOrb** [comment]
> It would be nice if this could use the application display name (Application.getApplicationDisplayName()) instead of hardcoding Ultimaker Cura.

I don't see why that makes this PR better. It only introduces a small extra risk in order for some benefit which is not clearly described here.

**Comment by rburema** [comment]
> ... some benefit ...

@BagelOrb If we ever decide to grey-label Cura.

**Comment by BagelOrb** [comment]
What I'm saying is that we should make changes for "grey-labeling' when we decide to implement or merge 'grey-labeling' - not in this PR.

PS: please don't interpret my comments as required work; I'm just making a principled argument here.

**Comment by rburema** [comment]
@BagelOrb Hardcoding stuff comes with it's own risks, and is generally considered a code smell.

**Comment by rburema** [comment]
@DonExo For future reference: If we've got other PR's related to this one, we usually put it here.

**Pull request merged**
