### PR TITLE
Added the "Within Infill" combing option that functions identically to the original "Not in Skin" option.

### PR DESCRIPTION
**Pull request by smartavionics**
See https://github.com/Ultimaker/CuraEngine/pull/781

### CODE REVIEW

**Comment by smartavionics** [comment]
Thanks for merging this.

I hope you realise that the change to the no skin combing behaviour means that people who are currently using no skin combing will see different results (hopefully better!). If they want the old behaviour then they have to use this new within infill setting. So I am wondering if you want to add something to your version upgrade script to automatically change the value of the retraction_combing setting in existing profiles from "noskin" to "infill"  so that the user doesn't see a change in behaviour when they upgrade?

**Comment by alekseisasin** [comment]
I have noted in the ticket that the old implementation is "infill": "Within Infill".
by the way, it is a good notice, indeed we probably need to apply the change in project loading. Tomorrow I will discuss it with other colleagues.

**Comment by alekseisasin** [comment]
@smartavionics , we made the change to the version upgrade, now after loading an old project the retraction_combing = "noskin" will become "infill"

**Comment by smartavionics** [comment]
Good. That should avoid people getting a shock when their prints come out different to expected.

**Pull request merged**
