### PR TITLE
Create AddCoolingProfile.py and Update InsertAtLayerChange

### PR DESCRIPTION
**Pull request by GregValiant**
Commit 1) A new Post-Processor to add a Cooling Profile to gcode
- Remove all M106 lines up to the end of the last layer.
- Add new M106 lines either "By Layer" or "By Feature".
- Support for PWM and 0-1 fan speed scales.
- Optional Starting and Ending layers for the insertions.

Commit 2) Update InsertAtLayerChange
- Add support for multi-line insertions
- Add optional Starting and Ending layers
- Add option for a single insertion at a layer
- Add Frequency of Insertions (Every Layer, every 2nd, 3rd, 5th, 10th, 25th, 50th, 100th)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] And update to an existing feature

# How Has This Been Tested?

- [ X] Test A:  Tested with "All at Once" and "One at a Time" and with Cooling enabled and Cooling disabled in Cura.

**Test Configuration**:
* Operating System: Windows 11, Cura 5.2.1, 5.3, 4.13.1

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by GregValiant** [comment]
Functionally both plugins work as they should.

In regards to the Cooling Profile plugin:
When using "By Layer" it picks up an extra linefeed/newline/carriage-return character somehow and I've been unable to eliminate it.  This leaves a space in the gcode between layers.  That happens whether an M106 line was inserted at the location or not.
Although the effect is to actually make the gcode a bit easier to read, the space between layers shouldn't be there.

**Comment by MariMakes** [comment]
Thanks for contribution! 👍 
For internal reference CURA-10210

**Comment by GregValiant** [comment]
Much better I think.

**Comment by MariMakes** [comment]
Oh No! @GregValiant, why did you close the PR?

**Comment by GregValiant** [comment]
Hi @MariMakes ,

I thought I had made a mess of it.  It ended up with the two files and should have only been the one file.  I'm stumbling through the dark with this.  The original pull request was an effort to get it into 5.3 as I think the plugin is a good idea and would be helpful to many.  I knew the code needed to be cleaned up but I'm not very skilled at Python and so I just passed along the design and hoped that someone would pick it up and run with it.
I put up another pull request for "AddCoolingProfile" and I think it's better from a coder point of view.  It's #14485 .

This continues to be a work in progress and should probably be an Extension rather than a post processor, but learning how to do that is slow going.
The last couple of days I added support for multiple extruders with multiple layer cooling fans.  It would be preferable to pull the info from Cura rather than having more boxes for the user to fill in.  I don't know how to access the setting for "extruder[#] {machine_extruder_cooling_fan_number}".

At any rate - there is still a pull request, it's just a different pull request.

**Pull request closed without merging**
