### PR TITLE
Add Alfawise U20

### PR DESCRIPTION
**Pull request by pinchies**
Add a preset for the Alfawise U20 to model list.

### CODE REVIEW

**Comment by nallath** [comment]
For our reference; CURA-5902

**Comment by Appesteijn** [comment]
2018-11-26 15:44:52,118 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [65]: An uncaught error has occurred!
2018-11-26 15:44:52,119 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: Traceback (most recent call last):
2018-11-26 15:44:52,120 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/Users/m.suurmond/Develop/Cura/cura/Settings/MachineManager.py", line 403, in addMachine
2018-11-26 15:44:52,120 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     new_stack = CuraStackBuilder.createMachine(name, definition_id)
2018-11-26 15:44:52,120 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/Users/m.suurmond/Develop/Cura/cura/Settings/CuraStackBuilder.py", line 68, in createMachine
2018-11-26 15:44:52,121 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     cls.createExtruderStackWithDefaultSetup(new_global_stack, position)
2018-11-26 15:44:52,121 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/Users/m.suurmond/Develop/Cura/cura/Settings/CuraStackBuilder.py", line 128, in createExtruderStackWithDefaultSetup
2018-11-26 15:44:52,121 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     extruder_definition = registry.findDefinitionContainers(id = extruder_definition_id)[0]
2018-11-26 15:44:52,122 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: IndexError: list index out of range

**Comment by pinchies** [comment]
> When adding this printer:
> 
> 2018-11-26 15:44:52,118 - CRITICAL - [MainThread] cura.CrashHandler.**init** [65]: An uncaught error has occurred!
> [...]

Sorry, I uploaded the wrong file into the extruders folder. Fixed now!

**Comment by diegopradogesto** [comment]
Thanks for the fix.

**Pull request merged**
