### PR TITLE
Add user editable snap distance

### PR DESCRIPTION
**Pull request by cubiq**
This PR requires an update to CuraEngine as well ( https://github.com/Ultimaker/CuraEngine/pull/818 )

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
I think we need to give this a better name and a more neutral description. This adjusts a filter that removes polygons with a circumference less than the "snap distance". So Snap Distance is not a good name because it doesn't snap to anything at all. What about Minimum Circumference? Or if you can find something more elegant...

The description mentions that it's suitable for SLA printers. I'd prefer that to be more neutral so that other types of printers may use this too. The first sentence of the description is also inaccurate. It's not between polygons.

Yeah, I think we should adjust that variable name in the engine as well.

**Comment by cubiq** [comment]
Thanks @Ghostkeeper for evaluating my PR!

So if I get it right, it removes polygons inscribed in a circumference smaller than snap distance (I guess diameter). To simplify how about "Minimum Polygon size" as a name and then add a suitable description?

**Comment by Ghostkeeper** [comment]
"Size" is indeed better. It's a bit vague but perhaps intuitive enough.

I'm still thinking that the setting is perhaps a bit too detailed for a user to be fiddling with. It may be applicable for SLA but Cura is primarily intended for FFF. This piece of code was intended as a sort of pre-filter as well to not work with degenerate shapes that would fall away in the first inset anyway. Perhaps it's more logical to hard-code this to always be equal to the outer wall line width times 4 (which would remove pieces smaller than a square of one outer wall wide).

I'll discuss this with the Cura team tomorrow though, see what they think about it.

**Comment by ianpaschal** [comment]
My opinion is that we're already deep in the deep end when it comes to settings users probably don't need to mess with; after all, that's why we have recommended mode.

Considering what a small and clean tweak this is, and removes a magic hard-coded value from the engine (a `TODO` anyway, apparently) I'm in favor of a merge, @Ghostkeeper.

**Comment by ianpaschal** [comment]
See my comments in https://github.com/Ultimaker/CuraEngine/pull/818

**Comment by mypeopoly** [comment]
Hi, this is Mark from Peopoly.  I was the one who started a post about rounding error in Cura (https://github.com/Ultimaker/Cura/issues/1696) after Tim Kuipers mentioned it in a Facebook group.   In the attempt to preserve as much polygons in Cura for SLA printing, our tests led us to the snapdistance variable.  We felt this could be a useful tweak for other users who need more polygons.  It worked quite well and we created a special version of Cura with this variable modded.

Matteo is a Peopoly Moai user and he was interested about getting as more resolution from Cura while minimizing artifacts.  After some tests, we would able found combinations of snapdistance / resolution that improve the print results while keeping the resolution high.  It worked so well that we felt this would likely to be useful for other users. This led to the pull request.  

If there is a concern about users being confused about what this "snap distance" does or enter a number that is not practical, perhaps we have a drop down box with 2 options, one is for Default Cura, and the other is Higher Polygon (0.1) without giving any option to manually enter a value.

**Comment by jackha** [comment]
Discussed this in the team. We renamed it to Minimum polygon circumference and merged it :-) Thanks @cubiq

**Pull request closed without merging**
