### PR TITLE
4.8

### PR DESCRIPTION
**Pull request by omega-regulus**
Hello, I was on windows and I become a Mac user recently and I have "recommandation" for you, your software is so cool but can you put different tabs like a web browser to switch between printers and stl files without make a new project and keep a sliced stl while slicing another for example.

### CODE REVIEW

**Comment by nallath** [comment]
Please don't create pull requests for feature requests.

**Comment by omega-regulus** [comment]
I’m sorry for this but where can I pull a request for a feature ?
________________________________
De : Jaime van Kessel <notifications@github.com>
Envoyé : Wednesday, November 4, 2020 2:50:04 PM
À : Ultimaker/Cura <Cura@noreply.github.com>
Cc : omega-regulus <omega_regulus@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [Ultimaker/Cura] 4.8 (#8691)


Please don't create pull requests for feature requests.

**Comment by nallath** [comment]
https://github.com/Ultimaker/Cura/issues/new/choose

**Comment by omega-regulus** [comment]
Ok thank you
________________________________
De : Jaime van Kessel <notifications@github.com>
Envoyé : Wednesday, November 4, 2020 2:54:33 PM
À : Ultimaker/Cura <Cura@noreply.github.com>
Cc : omega-regulus <omega_regulus@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [Ultimaker/Cura] 4.8 (#8691)


https://github.com/Ultimaker/Cura/issues/new/choose

**Pull request closed without merging**
