### PR TITLE
Add 'Scale Fan Speed From 0 to 1' Setting.

### LINKED ISSUE #11264: RRF Fan Speed Bug
### Application Version

>4.10.0 

### Platform

Windows 10

### Printer

RRF

### Reproduction steps

generate RRF gcode using regular fan speed 0%
Maximum fan speed 5%

### Actual results

Fan blows crazy speeds at times

### Expected results

RRF can use 2 Fan speed scales
0.0-1.0 (with decimal place)  and 0-255 (without decimal place)

cura generates M106 commands like below using the low flow settings I am using and appears to be a combination of both of RRF scales.

Please see the lines below pointed at with Arrows
Cura needs to use either the 0.0-1.0 scale or 0-255 scale not a combination of both, 
The resulting fan on the highlighted lines below destroyed my print with expensive material

	Line 994075: M106 S3.7
	Line 994455: M106 S2.3
	Line 994837: M106 S0.6    <--- RRF sees this as 60%
	Line 995228: M106 S1.4
	Line 995624: M106 S3.7
	Line 996005: M106 S2
	Line 996371: M106 S2.3
	Line 997099: M106 S3.3
	Line 997808: M106 S4.2
	Line 998159: M106 S3.6
	Line 998821: M106 S3
	Line 1000806: M106 S0.3    <--- RRF sees this as 30%
	Line 1001142: M106 S5.7
	Line 1001448: M106 S5.4
	Line 1001747: M106 S5.9
	Line 1002053: M106 S5
	Line 1002377: M106 S4.5
	Line 1002987: M106 S1.7
	Line 1003289: M106 S2.1
	Line 1003581: M106 S3
	Line 1003856: M106 S5.6
	Line 1004127: M106 S3.1
	Line 1004404: M106 S3.4
	Line 1004678: M106 S3.7
	Line 1005227: M106 S4.1

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CFFFP_RR_motormount.zip](https://github.com/Ultimaker/Cura/files/7873868/CFFFP_RR_motormount.zip)

### PR DESCRIPTION
**Pull request by rburema**
Will help fix #11264 

See also backend (CuraEngine) PR with the same branch-name: https://github.com/Ultimaker/CuraEngine/pull/1564

### CODE REVIEW

**Comment by unknown-loser** [comment]
RRF views the 0-1 range in decimal places

eg. 0.1 = 10%, 0.5 = 50% and 0.9999 = 99.99% etc.

Therefore `"type": "bool"` should rather be set to a floating point value :)

**Review by unknown-loser — COMMENTED** [review]
RRF uses 0-1 values for PWM control of fans

Therefore the 0-1 is in floating point format and a type of bool will not be able to hold the values necessary. 

For example 0.45 is 45% but bool only allows for 0 or 1 (off or on) so RRF prints will fail if a lower fan speed is required 

Therefore `"type": "bool"` should rather be set to a floating point value

**Comment by rburema** [comment]
@unknown-loser Please read carefully. Bool is not the type of the fan speed itself. Bool is the type of the switch: Whether to switch to 0..1 mode or PWM mode. Please also read the engine PR.

**Comment by unknown-loser** [comment]
> @unknown-loser Please read carefully. Bool is not the type of the fan speed itself. Bool is the type of the switch: Whether to switch to 0..1 mode or PWM mode. Please also read the engine PR.

My apologies, I see that I did end up reading that a bit too fast. I will also go read the engine PR.... carefully this time lol

Sorry again @rburema for not reading carefully :)

**Comment by rburema** [comment]
@unknown-loser No worries.

**Comment by unknown-loser** [comment]
> @unknown-loser No worries.

I just went through the engine PR again and  I realize my miss understanding 

Your code is all good :D

**Pull request merged**
