### PR TITLE
New Deltacomb Models and updates

### PR DESCRIPTION
**Pull request by kaleidoscopeit**
New Deltacomb Models  DC-20, DC21, DC30

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Current users of the "deltacomb" definition would see their configurations go corrupt, since their printer suddenly doesn't exist any more. What update path should we make for them? Should they be transferred to a new printer? With which profiles active?

**Comment by kaleidoscopeit** [comment]
If it's possible the users has to be transferred to "deltacomb_dc20.def.json" profile. Thankyou.

**Comment by Ghostkeeper** [comment]
Cura has a version upgrading system that will change the users' configuration folder. If they had a Deltacomb printer active in Cura 4.5 they will have a file in their `machine_instances` folder that looks something like this:

```
[general]
version = 4
name = Deltacomb 3D
id = Deltacomb 3D

[metadata]
setting_version = 12
type = machine
group_id = 413ff2f2-d5fc-46c3-be36-ad14d30c670e

[containers]
0 = Deltacomb 3D_user
1 = empty_quality_changes
2 = empty_intent
3 = normal
4 = empty_material
5 = empty_variant
6 = Deltacomb 3D_settings
7 = deltacomb
```

And another in their `extruders` folder that loos like this:
```
[general]
version = 4
name = Extruder 1
id = deltacomb_extruder_0 #2

[metadata]
setting_version = 12
type = extruder_train
position = 0
machine = Deltacomb 3D

[containers]
0 = deltacomb_extruder_0 #2_user
1 = empty_quality_changes
2 = empty_intent
3 = empty_quality
4 = generic_pla_175
5 = deltacomb_040_e3d
6 = deltacomb_extruder_0 #2_settings
7 = deltacomb_extruder_0
```

Those files are container stacks. They tell Cura which profile the user had active in this printer. In position 7 of the machine instance you see that it has the `deltacomb` profile active, referring to `deltacomb.def.json`. It also has the `normal` quality profile active, and there is no material. This sort of thing would have to be changed.

For an example of a version upgrade that changed that sort of thing, we can look to this example in the upgrade from 4.3 to 4.4:

https://github.com/Ultimaker/Cura/blob/07e6cfa6936d0b2d08c1ddee2777df431e37087b/plugins/VersionUpgrade/VersionUpgrade43to44/VersionUpgrade43to44.py#L82

This function updates some containers that were renamed (listed at the top of the file). It also split up the UM2 and UM2+Olsson into two different printers.

**However** in order to apply a version upgrade you'd need to:

* Create a version upgrade plug-in.
* Update the version numbers. In your case the setting version needs to be adjusted.
* Update Cura's existing profiles in this repository too (also applying the version upgrade).

This is quite a big change, so perhaps it's easier to wait a bit until we develop a version upgrade plug-in for you. Then we can just add to this version upgrade plug-in that it also changes the stacks to use the new profiles. We're planning to create this version upgrade for this PR: https://github.com/Ultimaker/Cura/pull/7247 I expect it'll take a day or two, and it would save you a lot of work.

The profile system is quite complex, so if you need help maybe one of us finds some time to help you with it. We can't really justify spending a lot of Ultimaker's time on it though so it'd need to be a small change we can make in a few minutes or we'd need to do this in our own time.

**Comment by kaleidoscopeit** [comment]
Ok, in order to let the operations easier, never mind about the version upgrading, I'll manage the issue directly with the Deltacomb users.

Futhermore, I've notice there are conflicting files. Those file where deleted in my push request, why they still conflicts?

Thank you very much

**Comment by Ghostkeeper** [comment]
In the meanwhile we've added a new version upgrade plug-in for the next release: https://github.com/Ultimaker/Cura/blob/master/plugins/VersionUpgrade/VersionUpgrade46to47/VersionUpgrade46to47.py

This makes it a lot easier for this PR because the boilerplate is there now. We just need to change the profiles in the container stacks. It's a bit technical, so I'll see what I can do for you in my spare time one of these evenings.

The files are conflicting now since you edited them for this PR, but we also edited them to apply this version upgrade. Resolving the conflict shouldn't be very difficult: Just take your version but use our `setting_version`. If you override the `maximum_resolution` setting that will now need to be halved for the next version to achieve the same result.

**Comment by Ghostkeeper** [comment]
I've made a version upgrade for you in this pull request: https://github.com/kaleidoscopeit/Cura/pull/3

Once you merge that, the merge conflicts here should also disappear.

**Comment by Ghostkeeper** [comment]
@konskarm @ninovanhooff @nallath @rburema Need someone else to review my code for this PR then. Can one of you pick this up?

**Comment by kaleidoscopeit** [comment]
There's any furter action I've to do with this PR in order to let the merge?

**Comment by rburema** [comment]
@kaleidoscopeit Hi! Sorry for the wait. This slipped between the cracks. In order to prevent this from happening (again) going forward, I've created an internal ticket (devs; please see jira: CURA-7433).

@Ghostkeeper Code looks fine (where do you find the time...), I'll try to find out why there are still conflicts & do some component tests next week.

**Comment by Ghostkeeper** [comment]
Conflicts are there now since we moved the 4.6->4.7 upgrade to 4.6->4.6.2. We'd need to move my code on top of the new plug-in, undo all of the setting_version updates and make sure the new Deltacomb profiles have the correct setting_version and maximum deviation.

**Comment by kaleidoscopeit** [comment]
Can I make something, i.e. upgrade the setting in my fork version and make a new pull request ?

**Comment by Ghostkeeper** [comment]
Preferably don't make a new pull request but update this one. All of the `setting_version`s now need to be 15. My changes in the VersionUpgrade46to47 that relate to Deltacomb need to be moved to the VersionUpgrade462to47 plug-in.

**Comment by kaleidoscopeit** [comment]
Ok, I've fixed the setting_versions for the existing files, the other conflicting files where deleted in the initial original PR. I've also got the opportunity to make small upgrade to End gcode and PETg profiles. Hope I did the job correctly.

**Comment by Ghostkeeper** [comment]
Thanks for the change! We cleaned up the rest and it's now in for Cura 4.7.

**Comment by kaleidoscopeit** [comment]
Thank you for your help!

**Pull request merged**
