### PR TITLE
Adding Erzay3D machine definitons

### PR DESCRIPTION
**Pull request by Robokinetics**
Hello,

I want to share my machine definitions of Erzay3D with the community.

Robokinetics.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
(Developers, see issue CURA-6451.)

**Comment by Robokinetics** [comment]
How long to wait before being merged?

**Comment by Robokinetics** [comment]
> (Developers, see issue CURA-6451.)

How long to wait before being merged?

**Comment by Ghostkeeper** [comment]
It seems we had an administrative error with this one. It got assigned higher priority because of the low risk, but then wasn't put in the sprint where we can see it. Thanks for the bump.

**Comment by Ghostkeeper** [comment]
Works. Thanks!

**Pull request merged**
