### PR TITLE
Add new Mingda printers model(X,Max,Pro)

### PR DESCRIPTION
**Pull request by jianshu-du**
Add the printers for Magician X, Magician Max and Magician Pro.

### CODE REVIEW

**Comment by eGit** [comment]
Also please add Ender 3 Max.

**Comment by Ghostkeeper** [comment]
Sorry if you closed it because it took too long. It takes us quite a while to work through backlog of pull requests most of the time. We try to do one PR per developer per day, but it's always busy.

**Comment by eGit** [comment]
Should I open a seperate issue for the Creality Ender 3 Max? Those printers are very popular and are on the market since at least Cura 4.10

**Comment by Ghostkeeper** [comment]
If you've made profiles, please do.

Don't create a feature request to add it though. We can't implement it, so it's likely to be closed.

**Pull request closed without merging**
