### PR TITLE
Add valueFromContainer() functions for profiles

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds CuraFormulaFunctions to get a value for a key from a stack starting at a specified container index. This enables a writer of profiles to eg refer to inherited values for a key from a formula for the same setting, eg:

A quality profile can use this formula to specify a temperature 5 degrees higher than the temperature specified in the material container:
`material_print_temperature = = valueFromContainer("material_print_temperature", 4) + 5`
A setting referencing itself without this function will create an infinite loop.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Did I break things, or were they already broken?

**Comment by Ghostkeeper** [comment]
You broke things, it seems. It's the type checking that's failing:

    cura/Settings/CuraFormulaFunctions.py:153: error: Cannot determine type of 'extruder_position'

**Comment by fieldOfView** [comment]
Fixed it, thanks.

**Comment by nallath** [comment]
It doesn't quite seem to work for me. 

I've added the `material_print_temperature = = valueFromContainer("material_print_temperature", 4) + 5` to um3_aa0.4_PLA_Draft_print.inst.cfg. Once I enable that profile, I get no value for printing temperature at all 
NoPrintingTemperature

**Comment by fieldOfView** [comment]
I'll look in to it.

**Comment by fieldOfView** [comment]
I made two mistakes in my example:
* there's a space after the second `=` that causes an unexpected indent error making the formula not work
* `material_print_temperature` should be taken from the extruder, not the global stack

@nallath, could you try the following instead?
`material_print_temperature = =extruderValueFromContainer(extruder_nr, "material_print_temperature", 4) + 2.1`
The 2.1 value should make it clear that the formula is working, and changing the material should show the value updating.

**Comment by fieldOfView** [comment]
For testing I prefer using the formula in a `user` profile, so it is still used when I switch materials.

**Pull request merged**
