### PR TITLE
Use a single draggable range slider in Layerview 

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR combines the two sliders in the LayerView with a single rangeslider. The rangeslider has three draggable handles: lower, upper and range. By dragging the range it is possible to always display eg 5 layers.

See #1444

TODO:
* ~fix keyboard control~
* ~use PointingRectangle for the layernumber box~
* ~cleanup~

This is a followup to https://github.com/Ultimaker/Cura/pull/1472, which was against master

### CODE REVIEW

**Comment by fieldOfView** [comment]
Might I suggest a couple of changes to the legend?

* Remove the words "Show"; the checkboxes already suggest this (and you're not adding "Show" to the extruders) 
* Rename "Travels" to "Travel Moves"
* Change the order so the interesting things are on top (Shell, Infill, Support, Travel Moves on the bottom).

I could include these in the PR.

**Comment by fieldOfView** [comment]
In order for the large-step layer navigation (ctrl+shift+ up/down) to work, this PR in Uranium needs to be merged:
https://github.com/Ultimaker/Uranium/pull/226

**Comment by nallath** [comment]
Is the pull request ready to be reviewed / tested by us?

**Comment by fieldOfView** [comment]
Yes

**Comment by fieldOfView** [comment]
Aww, now layer_view3_layout is merged. Shall I resubmit the PR (again) against master?

**Comment by jackha** [comment]
I'll look at the stuff and make sure it is in the master soon.

**Comment by maukcc** [comment]
Also, is it possible to add the actual layerheight of the layer that is being viewed?
some thing like: 243@12.2mm
This is very helpfull if you want to add some code at a particular layer

**Pull request merged**
