### PR TITLE
prusa i3 filament diameter to 1.75

### PR DESCRIPTION
**Pull request by guigashm**
prusa i3 filament diameter to 1.75

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
I'll cherry-pick this to the 2.1 branch as well so it will be included in the next release. Thanks for the contribution!

**Comment by guigashm** [comment]
So.. should I add my changes to the 2.1 branch?

**Comment by fieldOfView** [comment]
The 2.1 branch is pretty much on feature freeze, only bugfixes and stability changes should go in from now on. Any new features should go in branch, which will then be split off into a 2.2 branch before that gets released.

Your Prusa i3 fixes were deemed important enough, and at the same time safe enough (no risk of regressions), to be brought into 2.1.

**Comment by Ghostkeeper** [comment]
I've already brought it over to 2.1. It's just a tweak so of no risk of breaking 2.1 (unless I did the cherry-pick wrong of course, but that seems to have gone well).

**Pull request merged**
