### PR TITLE
add 2nd extruder to Tevo Tarantula printers

### PR DESCRIPTION
**Pull request by paalex**
addressing #3345 issue

### CODE REVIEW

**Comment by paalex** [comment]
@TheAssassin @FN5969

**Comment by TheAssassin** [comment]
Is there a reason you ping me?

**Comment by paalex** [comment]
@TheAssassin you are marked as the author for the Tevo Tarantula config file ```"author": "TheAssassin"```
If it's not the case, or it's not relevant, my apologies

**Comment by TheAssassin** [comment]
@paalex ah, right, that can well be.

I got the printer nearly 3 years ago, I don't know if there's even an "official" two-printer-head kit or something like that. I never really liked the printer, and right now it's even out of order as I don't have time to fix its extruder.
I don't think I can contribute a lot to this PR. Please feel free to take any changes you want to the config file.

**Comment by paalex** [comment]
@TheAssassin got it, thanks.
I still use and the Tarantula and even got a 2nd extruder for it
I tested these config files with latest stable version of Cura and it loads well and works as expected. Hopefully it would get merged

**Comment by konskarm** [comment]
When adding a second extruder, I would expect to see at least some distance from the first extruder e.g. "machine_nozzle_offset_x": { "default_value": x.x }. Currently I see that both in the tevo_tarantula and the tevo_tarantula_pro extruders 0 and 1 are identical. Are you sure this is correct?

**Comment by konskarm** [comment]
> When adding a second extruder, I would expect to see at least some distance from the first extruder e.g. "machine_nozzle_offset_x": { "default_value": x.x }. Currently I see that both in the tevo_tarantula and the tevo_tarantula_pro extruders 0 and 1 are identical. @paalex are you sure this is correct?
> 
> Also, the second extruder is an upgrade, right? If we accept this PR, it means that the the second extruder will exist for all Tevo Tarantula users, which will cause confusion if they have only one extruder.

Alright, I see that the default number of extruders is 1 and it can be changed in the Print Settings window, similar to the Nozzle offsets, so this PR works fine.

**Pull request merged**
