### PR TITLE
Create creality_ender5.def.json

### PR DESCRIPTION
**Pull request by PDBeal**
Every release I copy this file into my resource folder for the Ender-5.  Figured I should add it to the repo for future updates.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
This is about to collide with the Creawsome merge: https://github.com/Ultimaker/Cura/pull/5809

**Comment by Ghostkeeper** [comment]
Perhaps you can see what you can contribute to that pull request over at https://github.com/Ultimaker/Cura/pull/5809?

**Comment by PDBeal** [comment]
This won’t collide with any of his changes. Besides that pull request looks like his own setup for some of these machines, not the true Creality setup that matches what is already included in Cura.

If it’s not wanted, that’s fine, moving forward I’ll continue to add it to my Cura installations. I’d rather use the Creality provided definition that someone’s custom definitions.

I didn’t write this definition, it was downloaded from Creality as part of the software package for the Ender-5.

**Comment by Ghostkeeper** [comment]
The reason of how I know it's more battle-tested is because at the release of version 4.1 we were getting thousands of crash reports from that mod because it caused Cura to crash upon start-up.

If it doesn't collide with those changes, maybe you could rebase it on his branch?

**Comment by trouch** [comment]
@PDBeal existing Creality machines definition has been community provided AFAIK
However I can't find original source except `Michael Wildermuth` as the original CR-10 definition author as well as your Ender-5 one. I have no clue who is he, but he doesn't seem to be a Creality employee.

Having said that, I can only just suggest to give a try to my Creawsome machine definition. And let me know how it goes. I'm willing to improve and adjust for Ender-5 eventually !

https://github.com/trouch/CreawsomeMod

**Comment by PDBeal** [comment]
The file was part of the download package from Creality for the Ender-5.  They have links for the SD card images that is at https://www.creality3d.cn/download/sd-card-file_c0005.  Within the Ender-5 download link you'll find the Cura definition 
https://www.dropbox.com/s/1d0ygffu7i13yg1/Ender-5.rar?dl=0&file_subpath=%2FEnder-5+%E9%9A%8F%E6%9C%BA%E8%AF%B4%E6%98%8E%EF%BC%88%E8%8B%B1%E6%96%87%EF%BC%89%E5%BA%95%E7%A8%BF20181007%2F2.Software+and+USB+Driver%2FCURA%2FCura3.4.1

Granted the definition was from Cura 3.4.1, but thats the original source for the json.  Perhaps he does not work for Creality, or perhaps he does.  All I know is the definition was part of the Ender-5 SD image from Creality.

I personally do not use user created mods because I don't trust them.  If it's not supplier provided, I'll create my own.  There are too many well documented cases of usermods containing malicious code.  in this case it may not be true, but as a general rule of thumb, I don't have any inclination to even trial a usermod.

**Comment by trouch** [comment]
I confirm CreawsomeMod has malicious configuration that makes prints better, but nothing else 😅

**Comment by nallath** [comment]
We do actually check what is merged into Cura. It's by no means a guarantee that there is no malicious code, but i think the quality of the files as provided by @trouch is orders of magnitude better than the old profiles.

The file you provided is also not a full definition. If you want the original profile in, that can be discussed, but we need all the required files in order to do so.

**Pull request closed without merging**
