### PR TITLE
Update DisplayProgressOnLCD.py

### PR DESCRIPTION
**Pull request by inigoml**
Support for Octoprint via M118 A1 P1 action:notification command when using BTREETECH TFT
- ETA
- % advance

Replace this script at %CURA_HOME%\plugins\PostProcessingPlugin\scripts\DisplayProgressOnLCD.py

Octoprint support implemented on the [BTT TFT](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2241).

### CODE REVIEW

**Comment by inigoml** [comment]
Functionality related with: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2241

**Review by Ghostkeeper — APPROVED** [review]
Looks good to me. I'll test it a bit, although I don't have Octoprint to actually print with.

**Comment by Ghostkeeper** [comment]
Example output I'm getting: `M118 A1 P0 action:notification Time Left 0h10m03s`

Looks good to me. Thanks for the contribution!

**Comment by Guilouz** [comment]
@inigoml Can you update plugin to support new parameters added in BigTreeTech TFT firmware, to display number of layer please ?

| **print layer progress**    | `M118 A1 P0 action:notification Layer Left <XXXX>/<YYYY>`

**Comment by inigoml** [comment]
> @inigoml Can you update plugin to support new parameter added in BigTreeTech TFT firmware, to display number of layer please ?

Cool. Will merge. I've not tested last Digant modificacion but will do it! :-)

**Comment by Guilouz** [comment]
@inigoml Waiting for your changes to test digant73 new PR.

**Comment by Guilouz** [comment]
I can test it if you want.

**Comment by inigoml** [comment]
Je, je. On Saturday I will come back home. I forgot to commit yesterday and
not at home right now. ;-)
Count with you!

**Comment by inigoml** [comment]
Not yet! This weekend will try to get some time to finish and testing before your real QA. ;-)

**Comment by inigoml** [comment]
@Guilouz , new PR created for this fuctionality
https://github.com/Ultimaker/Cura/pull/11846

**Pull request merged**
