### PR TITLE
portuguese

### PR DESCRIPTION
**Pull request by CoderSquirrel**
Started to make translation for portuguese

### CODE REVIEW

**Comment by fieldOfView** [comment]
Without looking at the work sofar: That's awesome, thanks! Not only for our portugese users, but also to help us convince management that crowdsourced translations can work.

**Comment by Ghostkeeper** [comment]
Thanks for the great work, CoderSquirrel! We'll definitely be looking into getting this translation in, if Uranium is done as well. We're going to need a green light from our boss first though, since including this might mean that we need Portuguese translations in the future, too.

A few pointers:

* Please make sure that the spaces at the end (and beginning) of strings are the same. For example, when the original string says "Min endstop x: " the translation needs to be "Fim de curso minimo X: ", not "Fim de curso minimo X:", otherwise the value after that colon will be spaced too closely to your translated text.
* In some places the capitalisation is different. This is important too.
* It looks like you tried to have all the ampersands (&) in the menu items at the same characters, which was not always possible in the translation. The ampersands can be placed at a character of your liking, as long as the character is unique in that menu.
* The newlines don't matter. Sometimes there will be a mistake in the template where it puts `""` on the first line and then the actual string on the second line. I see you tried to copy that, and tried to make your lines approximately equally long, but they should be ignored by the compiler.
* Feel free to add your name to the top of the files :smile:

If you're not fixing these, we'll try to do that for you (if the language is included).

**Comment by CoderSquirrel** [comment]
Thanks @Ghostkeeper i will look ahead to make this adjusted, i just can

**Comment by Patola** [comment]
Are there any remaining strings to be translated? If @CoderSquirrel is busy I can finish these translations. Does this PR have to be merged for me to add to it or I can freely add into it before it is merged?

**Comment by CoderSquirrel** [comment]
I had stoped to worked at it about 8 months :( but i'm planning to... the code at my fork is the same here. so you can do as you please. @Patola  Brasileiro ou Portugues?

**Comment by Patola** [comment]
Brasileiro! Will try and check your fork.

**Comment by Ghostkeeper** [comment]
Before we can add this translation, we'd need a complete translation of the current .pot files in Cura as well as Uranium. If a translation is just for Uranium we can add that translation for different applications that use Uranium, but if a translation is just for Cura (without Uranium) there will be no application that uses the translation so adding it has no use.

Right now we're at the cusp of releasing Cura 2.4 final. This means that you'd need to translate the .pot files located in the 2.4 branches of Cura and Uranium. However, I'm not quite sure that we can merge your translations in time for 2.4 any more. 2.4 is more or less frozen since there is no time for our QA team to test any changes any more before the release of 2.4. It'd need special permission to get this in on time for 2.4 and I don't think we'd get that permission. The Russian translation we got was on time, but this will probably be too late.

So that means that it's probably better to translate for 2.5 right now. But strings are bound to change for the 2.5 release. So that means that we'll need to have you update the translation after the string freeze for 2.5 in a few months.

**Comment by Ghostkeeper** [comment]
Note that CoderSquirrel's fork is still on the 2.1 release. If you complete the translation there, the translation will be outdated.

**Comment by Patola** [comment]
@Ghostkeeper yes, that's my dilemma. I plan to compare her translation to the current version of cura.pot and other files and adapt accordingly. Thanks for the information. What are the files involved? cura.po, fdmprinter.json.po and Uranium/resources/i18n/* ? Do you recommend a particular tool, or editing the text files directly?

**Comment by Ghostkeeper** [comment]
There are four files: cura.po, fdmprinter.json.po, fdmextruder.json.po and uranium.po. The last one is located in the Uranium repository: https://github.com/Ultimaker/Uranium/blob/master/resources/i18n/uranium.pot

I'd recommend PoEdit but any tool will do. I must admit that I've only ever used PoEdit (besides manual text file editing).

**Comment by Patola** [comment]
@Ghostkeeper I found no fdmextruder.json.po nor fdmprinter.json.po but I found fdmextruder.def.json.po and fdmprinter.def.json.po, I guess they are the ones, right?
@CoderSquirrel I apologize, the files are quite different, I am doing it from scratch although a few of the translations I copied from your PR. I will keep you as first translator, hope that is ok.

**Comment by Ghostkeeper** [comment]
> I found no fdmextruder.json.po nor fdmprinter.json.po but I found fdmextruder.def.json.po and fdmprinter.def.json.po, I guess they are the ones, right?

Ah yes, sorry. That's what I meant.

**Comment by Patola** [comment]
Done. Uranium PR 217 and Cura PR 1379. For disclosure, I am writing a brazilian portuguese book with about 350 pages (300 already written) teaching Simplify3D, Slic3r and the newer Cura and I have done an awful lot of research regarding the correct translation of the technical terms. Some of them have no historically accepted translation but I used expressions which infer or imply the same meaning. The book will be made available online and in print using a copyleft license (CC-BY-SA). I hope this information does not convey any kind of conflict of interests, since I think there aren't any.

**Comment by awhiemstra** [comment]
I do not think that is a conflict of interest. In fact, I think it is awesome to have someone who has proper knowledge of the domain translating things. We could use someone like that for other languages as well. :)

**Comment by CoderSquirrel** [comment]
@Patola i know that problably a lot in structure must have chaged, but at least u can use the sentences i think.  i wanna comeback, and also i just stopped because o got a new job in a new city, life kind went upside down, thats why i stoped. But i wanna comeback to it soon :P

**Comment by ChrisTerBeke** [comment]
Closing this PR as the other one was merged and Brazilian Portuguese is already in Cura now.

**Pull request closed without merging**
