### PR TITLE
Further improvements of the Support Eraser

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR is a small followup to #3492, which parents the added meshes to the clicked node instead of putting both the added meshes and the parent into a group. This prevents an extra convex hull from being drawn, and a wireframe cage from appearing. It does require a small change in PlatformPhysics, or otherwise the added mesh would still drop down to the buildplate.

### CODE REVIEW

**Comment by ianpaschal** [comment]
Yeah this feels a lot nicer to me. Do you think so too, or were you just humoring me, haha

The only last change I'd recommend is that if I select a support blocker and then click the support tool, and click it again it, removes. Then if I click another support blocker with the support tool still selected, it selects that one instead of removing it. To me, the tool should stay selected like other tools and and then remove any cubes you click like... bam bam bam rapid fire, vs. click to select and click again to erase.

**Comment by fieldOfView** [comment]
I  agree this feels nicer. It was just the patch to PlatformPhysics that stopped me before.

I'll try to reproduce your findings to see if I can fix it; rapid-fire was the idea.

**Comment by ianpaschal** [comment]
Here I will make a quick gif.

kapture 2018-03-16 at 14 31 20

**Comment by fieldOfView** [comment]
Fixed that. Also, ctrl-clicking a node will now switch to the translate tool so it there is a quicker way to reposition added nodes.

**Comment by ianpaschal** [comment]
giphy-downsized

Tested and works really great. Thanks so much Aldo!

**Comment by ianpaschal** [comment]
@fieldOfView This may need some more changes. @Vandrasc has discovered a few issues:

1. When grouping and then ungrouping a mesh with blockers, the blockers will fall to the build plate. This is expected but possibly confusing to users who don't know what the feature is doing under the hood.
2. When importing and then ungrouping a project with blockers, the non-blocker meshes will just... vanish. This is of course not the expected behavior, even given what's under the hood.

This gives us two options as far as I can tell:

A. Fix the bug with importing and leave the ungrouping behavior as expected but possibly unintuitive (and see what our users have to say about it).
B. Use another mechanic to "stick" the blockers to their parent.

Personally B sounds more correct since the grouping feature is quite solid/stable when used for its intended purpose and I feel funny "fixing" it so it can do something that I don't think it was originally intended for.

What do you think? Do you know of another way to stick the blockers to their parent without putting them in a group?

**Comment by fieldOfView** [comment]
1. is not expected (I did not expect it), but is caused by grouping not respecting the pre-existing parenting.
2. sounds to me like project saving or loading is broken

I have been considering adding a "FloatDecorator" to anti-overhang, infill and cutting meshes that exempts them from dropping to the buildplate. That would mitigate the issue, but wont make behavior less confusing. I feel strongly that the parenting in the current implementation is the best way to stick the objects to the model.

I will see if I can fix 1 properly, by fixing the grouping/ungrouping code. Expecto pee-errum.

**Comment by ianpaschal** [comment]
1. Oh. Well I expected it. I know a lot of other software which prevents you from making a group consisting only of a group and figured Cura was just ignoring it and then performing the ungroup on the parent and its blockers.
2. Yeah that's a tricky one. Grouping = normally very reliable, project loading = not so much.

The FloatDetector would help with dropping to build plate, but wouldn't when moving the parent to the side a bit. If I were doing this in Three.js, it's a simple matter of adding the children to their parent in the scene graph so that their positions in the scene are relative to the parent, and then if the parent moves they move too. But that's separate from "grouping."

Do you think that could be done with Cura? I will take a look at the grouping code and if that's what grouping does already, in that case I might suggest that we add/use something like an "isGroup" decorator that lets the user ungroup things and not apply it to the relationship between a normal mesh and anti overhang meshes.

**Comment by fieldOfView** [comment]
>  it's a simple matter of adding the children to their parent in the scene graph 

That is exactly what the code does now.

**Comment by fieldOfView** [comment]
Here's a WIP branch that fixes the ungrouping issues:
https://github.com/Ultimaker/Cura/compare/master...fieldOfView:fix_grouping

I am checking to see if I can also fix the issue that multiplying a model that has support erasers attached does not copy the support erasers. If that is a similarly simple fix I will include both in one PR.

**Comment by ianpaschal** [comment]
> That is exactly what the SupportEraser code does now.
Interesting. So I take it grouping adds a new container style node which the children are then added to?

Either way, thanks for working on a fix. You'll make Mark very happy if this all gravy by 3.3.

**Comment by fieldOfView** [comment]
> You'll make Mark very happy

That's what we do this for, right?

Note: I'm not working on importing projects. That's someone else's mess.

**Comment by ianpaschal** [comment]
> That's what we do this for, right?

Yes. Our benevolent dictator. Praise be.

> Note: I'm not working on importing projects. That's someone else's mess.

Yeah of course. But I think if the issue of ungrouping support blockers from their parent isn't possible in the first place, that bug will won't occur anyway.

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/pull/3524

**Pull request merged**
