### PR TITLE
Green theme

### PR DESCRIPTION
**Pull request by BagelOrb**
I've made a green theme and I like it.
Been using this theme for the past week and haven't found any wrong colors any more the last few days.

### CODE REVIEW

**Comment by fieldOfView** [comment]
image

I would choose either a darker color for the background of the tooltips, or a dark color for the tooltip text.

**Comment by fieldOfView** [comment]
For reference and inspiration, here's another green-ish theme:
image

**Comment by nallath** [comment]
Oh god that mint green for the tooltip.

**Comment by fieldOfView** [comment]
I don't mind the mint green in itself (my teeth are getting whiter just looking at it), but the white text does not work well on top of it.

**Comment by nickthetait** [comment]
I have a sudden urge to consume ice cream.

**Comment by BagelOrb** [comment]
Is it because my theme is so hot?

**Comment by BagelOrb** [comment]
I agree about the lightness of the description box (the rectangular arrow), but I've checked and the lightness value is the same as the normal box when you add up the r + g + b values.

I thought the human eye was better at discerning green colors, so this doesn't make any sense.

I'll look into making the color darker..

**Comment by BagelOrb** [comment]
I've made the tooltip (and all thigns with the same color) darker. What do you think?

**Comment by Ghostkeeper** [comment]
Devs, see CURA-4020.

**Comment by nallath** [comment]
I'm not a big fan of adding a lot of themes. The current selection box isn't that well suited for a lot of themes. 
I can see the appeal of having the dark theme, but no so much in just switching around some colors.

**Comment by fieldOfView** [comment]
Ideally, themes would be downloadable like plugins.

**Comment by nallath** [comment]
Yeah, that would be a lot better.

**Comment by Ghostkeeper** [comment]
We've decided to not merge this one. At least not for now.

Once we have a theme repository it would make sense to give the user more freedom to use this kind of themes, but up until then, just a hue shift of the current theme is not something we really need to provide for our users.

**Pull request closed without merging**
