### PR TITLE
add KOONOVO Pyramid end KOONOVO ELF 3D printer 

### PR DESCRIPTION
**Pull request by KOONOVO3DPrinter**
[KOONOVO-ELF.zip](https://github.com/Ultimaker/Cura/files/5249442/KOONOVO-ELF.zip)
[KOONOVO-Pyramid.zip](https://github.com/Ultimaker/Cura/files/5249415/KOONOVO-Pyramid.zip)

### CODE REVIEW

**Comment by konskarm** [comment]
@KOONOVO3DPrinter in order to create the pull request, you need to fork the Ultimaker Cura master branch, add your printer changes inside the resources folder (e.g. koonovoelf.def.json should be in the resources/definitions folder, the extruder should be in the resources/extruders folder and so on) and after you have commited these to your own fork, you can make a pull request in the official Ultimaker/Cura repository in the master branch. 

In addition, I see you have materials. These materials should be commited in the https://github.com/Ultimaker/fdm_materials/ repository.

If you follow the above, our automated CI system will run some necessary tests to check if your files are ok. Then we will be able to properly review it and let you know if something needs to be changed.

The pull request you have created is a clone of the master branch which you are trying to push into the 4.7 branch. This is a very dangerous operation, since the master branch has changes that are not meant for the 4.7.

**Comment by KOONOVO3DPrinter** [comment]
thanks
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Konstantinos Karmas"; 
Date: 2020年9月21日(星期一) 下午3:12
To: "Ultimaker/Cura"; 
Cc: "KOONOVO3DPrinter"; "Mention"; 
Subject: Re: [Ultimaker/Cura] add KOONOVO Pyramid end KOONOVO ELF 3D printer  (#8412)

&nbsp;


 
@KOONOVO3DPrinter in order to create the pull request, you need to fork the Ultimaker Cura master branch, add your printer changes inside the resources folder (e.g. koonovoelf.def.json should be in the resources/definitions folder, the extruder should be in the resources/extruders folder and so on) and after you have commited these to your own fork, you can make a pull request in the official Ultimaker/Cura repository in the master branch.
 
In addition, I see you have materials. These materials should be commited in the https://github.com/Ultimaker/fdm_materials/ repository.
 
If you follow the above, our automated CI system will run some necessary tests to check if your files are ok. Then we will be able to properly review it and let you know if something needs to be changed.
 
The pull request you have created is a clone of the master branch which you are trying to push into the 4.7 branch. This is a very dangerous operation, since the master branch has changes that are not meant for the 4.7.

**Comment by KOONOVO3DPrinter** [comment]
Hello, I am a newcomer, I don't know why the previous submission was successful, but the subsequent submission has been unsuccessful, could you please tell me the reason? Thank you very much
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Konstantinos Karmas"; 
Date: 2020年9月21日(星期一) 下午3:12
To: "Ultimaker/Cura"; 
Cc: "KOONOVO3DPrinter"; "Mention"; 
Subject: Re: [Ultimaker/Cura] add KOONOVO Pyramid end KOONOVO ELF 3D printer  (#8412)

&nbsp;


 
@KOONOVO3DPrinter in order to create the pull request, you need to fork the Ultimaker Cura master branch, add your printer changes inside the resources folder (e.g. koonovoelf.def.json should be in the resources/definitions folder, the extruder should be in the resources/extruders folder and so on) and after you have commited these to your own fork, you can make a pull request in the official Ultimaker/Cura repository in the master branch.
 
In addition, I see you have materials. These materials should be commited in the https://github.com/Ultimaker/fdm_materials/ repository.
 
If you follow the above, our automated CI system will run some necessary tests to check if your files are ok. Then we will be able to properly review it and let you know if something needs to be changed.
 
The pull request you have created is a clone of the master branch which you are trying to push into the 4.7 branch. This is a very dangerous operation, since the master branch has changes that are not meant for the 4.7.

**Comment by Ghostkeeper** [comment]
Github does not accept attachments via e-mail, presumably because people's e-mail software often puts attachments like logos and such in.

Your previous submission was also not successful. You made a request that we merge our unstable master branch into the stable 4.7 branch, which is not something we want to do because that would bring untested features into the 4.7 release if we'd need to make a patch version.
Instead, please follow these instructions: https://linuxhint.com/pull_request_github/ But instead of changing some header colour you would need to add the files in your zip archive.

**Pull request closed without merging**
