### PR TITLE
Add open source projects to the About dialog

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds a list of projects, their description and licenses to the About dialog, similar to how legacy had it (except this PR adds an actual hyperlink).

The list of projects may have to be expanded, it could very well be that I missed some project(s).

### CODE REVIEW

**Comment by thopiekar** [comment]
Thanks!

I personally find it correct and fair to add all the used projects into the about dialog, but I personally would only add projects, which are needed by the core.
For example Cura could be used without any usage of USB (PySerial) or network connection (Python-ZeroConf). If it was possible I would tend to give our the plugins the possibility to append entries to the dialog. So USB printing will add PySerial to this list unless it is activated, for example.

However, this is just an idea/improvement I see here. Apart from this I'm fine and think it is better then not to mention these projects.

**Comment by Ghostkeeper** [comment]
Should we also include SIP?

**Comment by Ghostkeeper** [comment]
When I try to pull this, it says there are "no common ancestors" and proceeds to download 50MB of commits, and then proceeds to refuse unrelated histories.

**Comment by fieldOfView** [comment]
This seems to have been merged. Shall I close the PR?

**Comment by Ghostkeeper** [comment]
Uh, yeah. I'd expect Github to show it as being "merged"...

**Pull request closed without merging**
