### PR TITLE
Definition: Pulse XE E444M

### PR DESCRIPTION
**Pull request by randyzwitch**
# Description

This PR submits the bare minimum of settings needed for the Matterhackers Pulse XE E444M. This supersedes #12730, which seems to be abandoned.

## Type of change

- [x] Printer definition file(s)

# How Has This Been Tested?

- [x] Benchys
- [x] Ninja Turtle action figure
- [x] Misc guitar tools 

**Test Configuration**:
* Operating System: Windows 11 and direct from memory card on machine

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by randyzwitch** [comment]
The only concern I have about this is that by convention, MatterControl keeps all the machine settings via software. On my machine, I always run the following line of code to change the Z offset:

`M851 Z-3.13`

I didn't want to hard-code that into the profile G-code, since it would be hard to find. At the same time, this won't work unless 1) the user runs this code or 2) the user has set this permanently on their machine.

Is there a canonical way to handle this situation, or a way via documentation I can give users the heads-up about this?

**Comment by randyzwitch** [comment]
Is there anything else I need to do before this can be reviewed?

**Comment by saumyaj3** [comment]
> The only concern I have about this is that by convention, MatterControl keeps all the machine settings via software. On my machine when using Cura, I always run the following line of code to change the Z offset:
> 
> `M851 Z-3.13`
> 
> I didn't want to hard-code that into the profile G-code, since it would be hard to find. At the same time, this profile definition won't work unless 1) the user runs the above line of code or 2) the user has set the offset permanently on their machine.
> 
> Is there a canonical way to handle this situation, or a way via documentation I can give users the heads-up about this?

Hi randyzwitch!

If this behavior is consistent over all the printers, perhaps you would want to include this in the start g-code. Otherwise, other users have to find or do the offset themselves. I hope this helps.

**Comment by randyzwitch** [comment]
Now that I've thought about it, I think it's more reasonable to not have this inside the g-code. At least in my case, not having the value means the head will be too high off the plate, which I think is better than possibly crashing into the plate and people not knowing why

**Comment by saumyaj3** [comment]
Hey Randy! Thanks for your contribution. Your changes are now part of Cura.

**Comment by randyzwitch** [comment]
Awesome, thanks!

**Pull request merged**
