### PR TITLE
Add Generic Voron V0 Printer Profile

### PR DESCRIPTION
**Pull request by jgehrig**
Adds a generic Voron V0 printer profile to Cura.

The profile is closely related to the existing Voron V2 printer profile.

The bed STL is based on the VoronDesign CAD files. Some modifications were made to reduce STL size.

Please let me know if this requires any modification. I am happy to make changes.

### CODE REVIEW

**Comment by jgehrig** [comment]
Screenshot:
Cura_VoronV0_Screenshot

The STLs available in the VoronUsers repository, and VoronDesign CAD were too large.

I simplified some of the geometry to reduce the STL size to ~700KB.

**Comment by Ghostkeeper** [comment]
This seems to be the printer in question: https://vorondesign.com/voron0

The website is a bit unclear on whether the printer would be called Voron 0, Voron v0.0 or somewhere in between (Voron v0 is currently in the definition here).

Dimensions can be taken from here: https://github.com/VoronDesign/Voron-0/blob/Voron0.1/Firmware/printer.cfg . Seems to match with these printer definitions.

**Review by Ghostkeeper — APPROVED** [review]
Looks good to me. Thanks for the contributions! I'll give it a quick test and merge it for the next release (not 4.10 sadly, but after).

**Comment by jgehrig** [comment]
Happy to follow up with a "Voron V0" to "Voron 0" PR.

Also happy to let you handle this, trivial one-line change :)

**Comment by Ghostkeeper** [comment]
I'll just change the name myself. Indeed, a trivial change. Thanks for investigating!

**Pull request merged**
