### PR TITLE
Fusion3Design 3D printers and their F410 machine for 5.1.1

### PR DESCRIPTION
**Pull request by 64bittuning**
Adding support for the Fusion3Designs F410 machine. Later the F400, F306 and Edge will follow.

My business owns a Fusion3 F410 and using it has been difficult. The manufacturer originally shipped the machine with a license for Simplify 3d. We originally purchased the machine about three years ago, and the S3D license was lost when the previous controlling employee left the organization. I have spent a long time trying to get this machine operational and unfortunately my employer will not replace the S3D license. Enter Ultimaker Cura...

I have been using Cura since 4.4 and have spent a LONG time building and updating profiles. In 2020 I added Tronxy support, and recently performed a major overhaul on the profiles package. This brought me back to my attempt at adding support for our F410.
The vast majority of the profiles used here are a culmination of things I have learned through building other profiles, as well as using data points extracted from the large repository of S3D profiles that were released by Fusion3Design. The profiles all work, they produce good results, and use all of the original settings placed fourth by the manufacturer.

There are unfortunately some limitations that I felt were important to work around. Fusion3Design has a large list of certified materials. With such, in an effort to help prevent users from voiding the warranty on their machine, materials that do not match the approved materials list have been omitted from the machine profile at this time. The Generic profiles provided by Fusion3Design have been incorporated in order to provide support for PLA, PETG, ABS, ASA, PC, PA, CPE, and TPU. There are many brand name and specialty filament specific profiles available, however since Ultimaker Cura does not already "support" these materials with specific selectable profiles, the best option was to leave them for a future update.

Please view the certified materials lists below.
https://www.fusion3design.com/wp-content/uploads/2020/11/Fusion3-Certified-Materials-List-updated-10.28.2020-Simplify3D.pdf

https://www.fusion3design.com/list/

Fusion3Design can be found at https://www.fusion3design.com/

### CODE REVIEW

**Comment by 64bittuning** [comment]
@nallath @Ghostkeeper 
Can either of you two shed some light on what this template error is and why multiple users are running into the issue?

Error: .github/workflows/unit-test.yml (Line: 175, Col: [2](https://github.com/Ultimaker/Cura/actions/runs/3324004513/jobs/5495137165#step:7:2)2):
Error: The template is not valid. .github/workflows/unit-test.yml (Line: 175, Col: 22): Error reading JToken from JsonReader. Path '', line 0, position 0.

**Comment by erich-nushores** [comment]
How soon do you expect to be working on the printer profile for the Fusion3 Edge? I'm absolutely baffled by the lack of features available to advanced users in the paid-license Reactor software, especially coming from an open-source tool like Ultimaker Cura. I'd be very interested in figuring out how to create a proper config for the Edge in Cura to gain more control over the printing process and access some of the smarter tools I've grown used to.
Let me know if you are starting work on this, or if I can help.

**Comment by 64bittuning** [comment]
> How soon do you expect to be working on the printer profile for the Fusion3 Edge? I'm absolutely baffled by the lack of features available to advanced users in the paid-license Reactor software, especially coming from an open-source tool like Ultimaker Cura. I'd be very interested in figuring out how to create a proper config for the Edge in Cura to gain more control over the printing process and access some of the smarter tools I've grown used to. Let me know if you are starting work on this, or if I can help.

I will not be putting any additional effort into doing any kind of development work on Cura, until a simple answer can be provided on why there is a fault with my profile. 
That being said, I doubt the Edge will deviate too far from the F410, as its simply a reproduction of the same machine, except running a newer Duet mainboard with a Raspberry Pi SBC.

**Comment by Joeydelarago** [comment]
> > How soon do you expect to be working on the printer profile for the Fusion3 Edge? I'm absolutely baffled by the lack of features available to advanced users in the paid-license Reactor software, especially coming from an open-source tool like Ultimaker Cura. I'd be very interested in figuring out how to create a proper config for the Edge in Cura to gain more control over the printing process and access some of the smarter tools I've grown used to. Let me know if you are starting work on this, or if I can help.
> 
> I will not be putting any additional effort into doing any kind of development work on Cura, until a simple answer can be provided on why there is a fault with my profile. That being said, I doubt the Edge will deviate too far from the F410, as its simply a reproduction of the same machine, except running a newer Duet mainboard with a Raspberry Pi SBC.

Hey, @64bittuning this error in the "unit test / publish-test-results" action is unrelated to your profile, it's an issue that happens when trying to run tests of PRs from forks. We are working on a fix. I'll review your PR in the coming week.

**Comment by jellespijker** [comment]
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

**Comment by 64bittuning** [comment]
> Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter
> 
> If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

Done.
Seems to be green

**Comment by jellespijker** [comment]
Sorry that you have to be our guinea pig, something in the auto-formatting workflow seems to be faulty. It added a commit in which it formatted to much. Can you revert commit https://github.com/Ultimaker/Cura/pull/13355/commits/65719a19eb1afc6c1323f33f17e9c9484556abd0

**Comment by 64bittuning** [comment]
> Sorry that you have to be our guinea pig, something in the auto-formatting workflow seems to be faulty. It added a commit in which it formatted to much. Can you revert commit [65719a1](https://github.com/Ultimaker/Cura/commit/65719a19eb1afc6c1323f33f17e9c9484556abd0)

Actually what it did, and unfortunately didnt identify properly, was identify multiple line items that were in my individual printer definition which were not an over-ride, but rather a duplicate of what was listed in "fdmprinter" and "fdmextruder". I have checked each item individually and found them to be redundant.

**Comment by jellespijker** [comment]
Yes, but can you still revert https://github.com/Ultimaker/Cura/commit/65719a19eb1afc6c1323f33f17e9c9484556abd0 This is an autogenerated commit which changes over 500 files. Which was due to a fault in the auto-formatting workflow

**Comment by jellespijker** [comment]
It is also important that you resync from our `main` branch I still see the old "broken" workflow in your repo

**Comment by 64bittuning** [comment]
> It is also important that you resync from our `main` branch I still see the old "broken" workflow in your repo

Literally not worth it anymore.

I already didnt want to put any more time into this. 

Closing this PR because it has become too much of a hassle to keep doing something that doesnt benefit myself.

**Comment by 64bittuning** [comment]
Literally just done with this nonsense.

**Comment by jellespijker** [comment]
Sorry you feel that way

**Comment by jellespijker** [comment]
Would you still be willing if I take a look at it, clean it up a bit and fix the mistake I introduced and make a PR against your fork (or co-author the commits with you).
It would be such a waste if your efforts resulted in only frustrations instead of a new printer profile?

**Comment by 64bittuning** [comment]
> Would you still be willing if I take a look at it, clean it up a bit and fix the mistake I introduced and make a PR against your fork (or co-author the commits with you). It would be such a waste if your efforts resulted in only frustrations instead of a new printer profile?

I dont want anything to do with this anymore. I have spend countless hours building one of the most comprehensive profiles I have ever created, and it has sat here in pending publishing hell for MONTHS. I literally just cannot put fourth any more effort into this when it turns into being constantly bombarded by errors and flags, which then have me chasing my tail because I do not fully understand how all of the python environment works.

I have this working flawlessly in 4.13.1, and since Fusion3 wont update the machine further, there is no longer any reason for me to persue further action.

I'll give you the files, or access, if you tell me how... but I do not care to do this anymore.

**Comment by jellespijker** [comment]
fair enough and I understand your frustration. We have a huge backlog to process and limited resources,  that is the reason why we created those new checks.

I will take a look at your suggested changes and I will try to implement them during the weekend,  because we/I do appreciate you putting the effort in.

**Pull request closed without merging**
