### PR TITLE
Draw grid lines using shader

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR removes the grid line geometry from the buildplate, and instead draws grid lines using a glsl shader. This is much more efficient, especially for printers with large buildplates*. Nice anti-aliasing is also much cheaper to achieve using this shader than using line-geometry.

*: I am working on a printer that has a basically endless buildplate depth. The geometry-based approach that was recently introduced takes half a minute to just set up the geometry, whereas the proposed GLSL shader does it instantly.

### CODE REVIEW

**Comment by LipuFei** [comment]
For Dev, see CURA-4317

**Comment by nallath** [comment]
I'm getting a bit of a weird result in certain angles. 

weirdshaderresult
I think that overall, the change is definitely for the better.

**Comment by fieldOfView** [comment]
Does it look/behave like z-fighting? I'll try to reproduce and fix this.

**Comment by fieldOfView** [comment]
Should be better now

**Comment by nallath** [comment]
Whoo, i'll test it again :)

**Comment by fieldOfView** [comment]
That was quick!

**Pull request merged**
