### PR TITLE
Added Liquid 3D printer configurations

### PR DESCRIPTION
**Pull request by alexgrigoras**
LIQUID is an open-source 3d printer. More details for the printer can be found at https://liquid3d.site. Cura is the slicer that we chose for optimal printing results.

### CODE REVIEW

**Review by konskarm — CHANGES_REQUESTED** [review]
Please change the "setting_version = 15" to "setting_version = 16" for all your qualities.

**Comment by konskarm** [comment]
I also see you the printer is inheriting from the "ultimaker" instead of fdm_printer. Is there a specific reason for that?

**Comment by alexgrigoras** [comment]
I changed the settings_version to 16. I corrected the 'inherits' parameter to fdmprinter. The reason for the setting was that I started from 'ultimaker' profile.

**Comment by fieldOfView** [comment]
Could you change the tabs to space in your def.json files? That would fix indentation issues.

**Comment by alexgrigoras** [comment]
Sure, I changed the tabs with spaces.

**Comment by fieldOfView** [comment]
Your platform mesh is too large. It is 35 MB. Please try keeping it under 1 MB.

**Comment by alexgrigoras** [comment]
I reduced the quality and removed some parts to get a smaller size. Now it has 585KB.

**Comment by fieldOfView** [comment]
Our CI has no further complaints.

**Comment by konskarm** [comment]
Seems to be working fine now. The printer slices fine, so I am accepting this PR.

**Pull request merged**
