### PR TITLE
[3.6] Fix memory leak in print monitor

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR fixes a memory leak in Cura Connect, which uses a QML Image to show subsequent frames of a mjpeg stream. In Qt 5.9+ QML Image seems to have a leak whenever the source is (re)set. See CURA-5821 and https://github.com/Ultimaker/Cura/issues/4626#issuecomment-432937248 for discussion.

The PR is a more performant implementation of https://github.com/Ultimaker/Cura/tree/CURA-5821_fix_camera_memory_leak; By merging the functionality of NetworkCamera, CameraImageProvider and the Image QML widget into a single widget, it prevents signals being handed back and forth between Python and QML and QML objects being initialised again and again.

### CODE REVIEW

**Comment by LipuFei** [comment]
tag: JIRA-5821

**Comment by fieldOfView** [comment]
I fixed the remaining references to NetworkCamera and OutputDevice.activeCamera.

The PR has the additional benefit of solving confusion between the *ActiveCamera in Controller.py (which refers to the camera that navigates the 3d scene) and what used to be *ActiveCamera for OutputDevice (which refers to a mjpg stream of a physical camera); the latter has now been changed to use ActiveCameraUrl.

**Comment by rburema** [comment]
Hi @fieldOfView, Thanks for the quick reply/work. Unfortunately, I can't do much over the weekend (when it comes to disucssing things with team-mates) & I'm not in on monday. If you really want to have this in sooner, I suggest to ping @LipuFei and he can discuss it with the rest of the team. cheers, Remco.

**Comment by rburema** [comment]
I've put a sticky on the board so it'll very probably be discussed monday morning. Just don't forget to cherry-pick the commits (to 3.6) instead of (also) pulling in master (to 3.6) with this branch if we do decide this!

**Comment by LipuFei** [comment]
New JIRA ticket: CURA-5866

**Comment by fieldOfView** [comment]
Working on it

**Comment by fieldOfView** [comment]
CI is acting up.

Note that I don't have a legacy UM3 device to test this with. Testing is needed (and some fixes may be required still).

**Comment by fieldOfView** [comment]
Hmm, seems I have merged a couple of master changes into my branch. I will rebase those out.

**Comment by LipuFei** [comment]
Looks good this time. Previously I got some type conversion errors.

**Pull request merged**
