### PR TITLE
Add CR-M4 printer definition

### PR DESCRIPTION
**Pull request by kixell**
# Description

This is to add the Creality CR-M4 printer definition. 

## Type of change

- [x] Printer definition file(s)

# How Has This Been Tested?

- [x] Test the definition is OK

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by Jojo09092007** [comment]
You still need the extruder.def file

**Comment by kixell** [comment]
> You still need the extruder.def file

Is that correct? Or does the creality_base this inherits include it?

**Comment by Jojo09092007** [comment]
> > You still need the extruder.def file
> 
> Is that correct? Or does the creality_base this inherits include it?
You need this line in your code, the example is for 2 extruders
Look into my Project with Kodak...
"machine_extruder_trains":
{
"0": "extruder_0",
"1": "extruder_1"
},

**Comment by kixell** [comment]
> > > You still need the extruder.def file
> > 
> > 
> > Is that correct? Or does the creality_base this inherits include it?
> > You need this line in your code, the example is for 2 extruders
> > Look into my Project with Kodak...
> > "machine_extruder_trains":
> > {
> > "0": "extruder_0",
> > "1": "extruder_1"
> > },

I have not contributed to this project before and I'm am not 100% sure about file inclusions and inheritance.  
None of the other Creality printers include this or have seperate extruder files. 

see https://github.com/Ultimaker/Cura/blob/main/resources/definitions/creality_cr10.def.json


The key value pair for "machine_extruder_trains"  is assigned on line 21 of https://github.com/Ultimaker/Cura/blob/main/resources/definitions/creality_base.def.json and this is included on line 4 of this printer's file.

Do I still need to include and assign a KVP for "machine_extruder_trains" when it is included in the creality_base.def?

**Comment by Jojo09092007** [comment]
Should work, because it inherets the creality base, if the extruder is defined there, I dont know, if Cura can fall back on a default extruder?

**Pull request merged**
