### PR TITLE
BQ printer profiles update

### PR DESCRIPTION
**Pull request by nicanor-romero**
Renamed the meshes to match the other names and modified Hephestos' mesh. Also ordered the overwrites and changed some values for the settings.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Looks good to me.

**Comment by awhiemstra** [comment]
Any chance you can update after https://github.com/Ultimaker/Cura/commit/8c629c511c17ced0ff91ce011d4ddb527ab4eeb6 got pushed? The changes there conflict with those in your PR.

**Comment by awhiemstra** [comment]
Oh, and I am very happy with your continued work on these profiles. Please keep it up! :)

**Comment by nicanor-romero** [comment]
Okay, it appears the conflict is solved now ;)

**Comment by awhiemstra** [comment]
And merged, thank you :)

**Pull request merged**
