### PR TITLE
reduce flow for 100% density parts

### PR DESCRIPTION
**Pull request by rijkvanmanen**
Overextrusion needs to be avoided to main high quality. More info: PP-86

### CODE REVIEW

**Comment by rijkvanmanen** [comment]
I just checked the combing behaviour with for the top surface skin layer (roofing layer). I did saw minor differences between 0 and 1 roofing layer, but nothing strange. Can you @pkuiper-ultimaker do a double check as well?

**Comment by pkuiper-ultimaker** [comment]
> I just checked the combing behavior with for the top surface skin layer (roofing layer). I did saw minor differences between 0 and 1 roofing layer, but nothing strange. Can you @pkuiper-ultimaker do a double check as well?

Old situation (no roofing):
image

New situation (1 roofing layer):
image

There are way to many unretracted travel moves in the top surface layer. NOK

**Review by pkuiper-ultimaker — CHANGES_REQUESTED** [review]
See comments. This changes produces a lot of travel moves in the top layer. NOK

**Comment by pkuiper-ultimaker** [comment]
> > I just checked the combing behavior with for the top surface skin layer (roofing layer). I did saw minor differences between 0 and 1 roofing layer, but nothing strange. Can you @pkuiper-ultimaker do a double check as well?
> 
> Old situation (no roofing): image
> 
> New situation (1 roofing layer): image
> 
> There are way to many unretracted travel moves in the top surface layer. NOK

Latest commit with te removal of the roofing layer now produces an OK result:
image

**Review by pkuiper-ultimaker — APPROVED** [review]

**Pull request merged**
