### PR TITLE
CURA-5613 Set the focus in the upper handle in the layer view

### PR DESCRIPTION
**Pull request by diegopradogesto**
Previously it was set to the text field. That makes it easier to release the focus by clicking in the main view and use the arrow keys to rotate the view.

### CODE REVIEW

**Comment by ianpaschal** [comment]
Note, this now contributes to CURA-5613

**Comment by ianpaschal** [comment]
I think this is for the best. It's also inline with typical OS behavior: text boxes only are affected by arrow keys once you give them focus.

**Comment by fieldOfView** [comment]
Does this also solve the issue that if you are in Layer View and you are making changes in the sidebar (with auto slicing enabled), that the focus can "stolen" from the sidebar while typing in values?

**Comment by ianpaschal** [comment]
I didn't think about that, but yes probably.

**Pull request merged**
