### PR TITLE
Dagoma DiscoUltimate profile

### PR DESCRIPTION
**Pull request by 0r31**
Hi,

This PR introduces Dagoma DiscoUltimate profile and add minor changes on other Dagoma printers profiles.

Regards,
Orel

### CODE REVIEW

**Comment by dagorel** [comment]
Hi again,

I don't really understand why the CI failed. Any idea?

Regards,
Orel

**Comment by 0r31** [comment]
Hi,

It seems the last CI failure was an internal issue. Adding a commit triggered another CI action and it succeeds.

Regards,
Orel

**Comment by Ghostkeeper** [comment]
Yeah we've been making changes to the CI system recently. You may have caught it at a moment when it was down in general.

**Comment by Ghostkeeper** [comment]
The model files don't seem to be aligned well to the build volume:

image

I'll shift the build volume a bit then.

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-7270.

**Pull request merged**
