### PR TITLE
2.5 nozzle size

### PR DESCRIPTION
**Pull request by Aurarum**
Hi, is there any chance to get the nozzle back into the settings?
it is not really convenient to recreate the printer json in order to change the nozzle size.

### CODE REVIEW

**Comment by fieldOfView** [comment]
See "Machine Settings" in the "Printers" pane of the preferences

**Comment by Aurarum** [comment]
am I missing something? we are talking about 2.5, right?
there is only configure Cura under preferences

**Comment by fieldOfView** [comment]
In the preferences window, go to the Printers pane/page. Or from the printer dropdown in the sidebar, choose Manage Printers...

**Comment by Aurarum** [comment]
where?
image

**Comment by fieldOfView** [comment]
Select the active printer

**Comment by fieldOfView** [comment]
Aw, wait. The active printer is a dual extrusion printer, and in 2.5 Machine Settings does not work with dual extrusion printers. If does in Cura 2.6

**Comment by Aurarum** [comment]
oh ok. is there a Windows compiled version to download somewhere?

**Comment by fieldOfView** [comment]
No, not yet

**Comment by Aurarum** [comment]
thanks for that. so I would have to compile myself? right?

**Comment by fieldOfView** [comment]
Well, it is python, it does not strictly need to be compiled. But yeah, you would need to download the source repositories and all the dependencies, and get it running from there. Not a trivial thing.

**Comment by Aurarum** [comment]
thanks for your time. I haven't done this before thus the questions

**Comment by awhiemstra** [comment]
Note that the 2.6 beta was just released: https://ultimaker.com/en/blog/49492-announcing-cura-26-beta
That should contain the new multi-extruder machine settings.

**Pull request closed without merging**
