### PR TITLE
Adding support for Elegoo Neptune 4 Pro

### PR DESCRIPTION
**Pull request by Ev1dentFir3**
# Description
This adds support for the Elegoo Neptune 4 Pro printer. Created elegoo_neptune_4pro.def.json for Neptune 4 Pro profile.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Printer definition file(s)
- [ ] Translations

# How Has This Been Tested?
- [x] Test A - Setup as Custom FFF printer, and used the g-code provided by Elegoo in their skinned version of Cura.
- [x] Test B - Printed multiple parts with Custom FFF profile to test g-code.

**Test Configuration**:
* Operating System: Windows 11 Cura 5.4. 

# Checklist:
- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by mordilion** [comment]
I tried to use the definition with Cura 5.4.0, but it didn't work. Somehow the Nozzle setting is missing. What am I overseen here? @Ev1dentFir3

**Comment by BremerButjer** [comment]
tested the json on my cura 5.4:
Printhead settings are not correct. (i thik this is probably because of elegoo base)
and can´t use a profile because missing nozzle size.

**Comment by jg506** [comment]
To fix empty nozzle list, need to create n4p folder under resources/variants. I simply copied the n3p folder, then renamed the folder, each file name and text inside each cfg file. Changed 3 to 4. @mordilion @BremerButjer

**Comment by jg506** [comment]
@2eQTu the PR cannot be merged yet. @Ev1dentFir3 need to add the missing resources/variants/elegoo//elegoo_neptune_4pro folder which I attached here. 
[elegoo_neptune_4pro.zip](https://github.com/Ultimaker/Cura/files/12651497/elegoo_neptune_4pro.zip)

**Comment by ToasterUwU** [comment]
Excited for this.
Elegoo doesn't have a Linux version of their (pretty old) cura version. Using it trough wine works, but isnt ideal for obvious reasons.
So having a version that is not only up to date, but also has a native Linux version would be awesome.

**Comment by fuji97** [comment]
The author @Ev1dentFir3 hasn't updated this PR for one month. Should we wait or fork and update it ourselves?

**Comment by jg506** [comment]
I'm using this without issues for about 30 prints now.

**Comment by ToasterUwU** [comment]
> The author @Ev1dentFir3 hasn't updated this PR for one month. Should we wait or fork and update it ourselves?

i think someone else needs to take this over. Since the original creator has not interacted with this even once since they made it.

**Comment by fuji97** [comment]
I forked the PR at #16608 and added the missing variant files. 
@Ev1dentFir3 if you want to take back the PR just tell me and I'll remove mine.

**Comment by repomanz** [comment]
> @2eQTu the PR cannot be merged yet. @Ev1dentFir3 need to add the missing resources/variants/elegoo/elegoo_neptune_4pro folder which I attached here. [elegoo_neptune_4pro.zip](https://github.com/Ultimaker/Cura/files/12651497/elegoo_neptune_4pro.zip)

Will this work with the neptune 4 max?

**Comment by saumyaj3** [comment]
implemented here: https://github.com/Ultimaker/Cura/pull/16819

**Pull request closed without merging**
