### PR TITLE
New definition was again faulty

### PR DESCRIPTION
**Pull request by velbn**
Somehow moving the default value of the material diameter fixed the definition

### CODE REVIEW

**Comment by nallath** [comment]
There are conflicts in your branch. Could you resolve them?

**Comment by velbn** [comment]
Ok should be fixed now

**Comment by fieldOfView** [comment]
As far as I can tell, this PR can be closed because the fix was already done in https://github.com/Ultimaker/Cura/commit/637d1a1da30ec312efcdd69696ed0b41910b18fe

**Comment by ChrisTerBeke** [comment]
Looks the same indeed.

**Comment by velbn** [comment]
Well i fixed it locally (removed the comma) but still it didn't worked. 
Somehow if i move the setting, it is fixed =/

**Comment by Ghostkeeper** [comment]
The Vertex Delta K8800 seems to load fine on my side.

That commit https://github.com/Ultimaker/Cura/commit/637d1a1da30ec312efcdd69696ed0b41910b18fe seems like it actually fixed something, but this PR doesn't. I think we'll close this PR for that reason.

Maybe it was a caching issue? Perhaps you need to delete your cache? On Windows it's over at `C:\Users\<You>\AppData\Local\cura`. On Linux at `~/.cache/cura`. Not sure about MacOS.

**Pull request closed without merging**
