### PR TITLE
Display info on lcd

### PR DESCRIPTION
**Pull request by GregValiant**
# Description

Added the option for M73 lines to update the time and percentage on the LCD.
Made some changes to tooltips.

This fixes... OR This improves... -->

## Type of change

- [ X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Test A - Unable to properly debug as my printer doesn't support M73

**Test Configuration**:
* Operating System:  Windows 10 Pro and Cura 5.5.0

# Checklist:

- [ X] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [ X] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by GregValiant** [comment]
Remco,
I've added the M73 options and made some tooltip changes.  There was a glitch in the conversion from Cura time in seconds to hr-min-sec and that's been fixed.

**Comment by rburema** [comment]
Hi Greg, thanks for the quick turnaround on the `M73` issue, and the other updates.

**Comment by GregValiant** [comment]
You need to talk to me before you jump in here and merge something.  I'm always tweaking these things.
Yesterdays thought was "what if someone uses both Pause at Height and Filament Change in the same Gcode?"  The "Time to Pause" function only searched for "Pause at Height".  I know it's a little thing, but it's still a thing.

You want last nights update (the user enters the actual Pause commands) or should we call this "Close enough"?

**Comment by rburema** [comment]
Sorry, these days I assume that if a PR isn't marked as 'draft', I should be able to merge it.

(As an aside; you can mark a PR as Draft either by opening it as a draft, with the drop-down menu opened by the button next to the green 'Create Pull Request' button at the bottom of the preview, or later, with the 'Still in progress? _Convert to draft_' link underneath the Review section in the upper left.)

Are all the other PR's are also 'not ready to merge unless I ask'? Or are the ones on the list you gave me 'safe'?

Let's see last night's update, there should me more than enough time before 5.7 is out.

**Comment by GregValiant** [comment]
The rest should be fine but I'm going to turn them all into drafts and I'll
go through them today to insure that they are indeed ready to be merged.

In my defense and in regards to "DisplayInfoOnLCD" - I was using M600 for a
print and realized that it constitutes a pause but there was no search for
M600 in DIsplayInfoOnLCD so the "countdown to Pause" function didn't
trigger.  There were also no searches for M25, @pause, or the others.  I've
added the search option for whatever command might pause the print and the
user can enter multiple pause commands into the box in case they mixed
something like a PauseAtHeight to insert nuts and a Filament Change in the
same project.  I had my blinders on and missed a trick there.

BTW I haven't made any changes to AddCoolingProfile in months.  I know it's
long and involved but it has been requested many times.  You and Casper
were properly horrified when you looked at it but it does work (and at the
very least a lot of the typing is done).

**Pull request merged**
