### PR TITLE
Strateo3D_profiles_update

### PR DESCRIPTION
**Pull request by KOUBeMT**

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-6930.

**Comment by Ghostkeeper** [comment]
These changes look like they work fine, so I'll merge them.

But by the way, it looks like the preferred material (`emotiontech_pla`) is not compatible with the preferred quality type (`e`) with the preferred variant (`Standard 0.6`). Shall we change the preferred quality type to something that is supported, such as `d`?

**Comment by KOUBeMT** [comment]
Yes let's change it to (c).... would you like me to do it then request a pull?
thanks

**Comment by Ghostkeeper** [comment]
Nah, I'll do that for you.

**Comment by Ghostkeeper** [comment]
Done: 2abb9842d2ed75ca587fb7ed980bc5b7154f63a8

**Comment by KOUBeMT** [comment]
thank you !

**Pull request merged**
