### PR TITLE
Fix watching for changes in 3mf files

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR fixes the 3MF reader to support watching the filesystem for modified files.

This PR is a followup to #7205

### CODE REVIEW

**Comment by nallath** [comment]
I've found one thing that's perhaps a bit weird with this. 

**Steps:**
1. Start up two instances of Cura.
2. Create a project file in Cura A. 
3. Load the project in Cura B.
4. Make a change in Cura A (Rotate the model), save it again.
5. Check Cura B

**Expected:** 
Cura B shows "File has been changed, do you want to reload" message 
After re-load, the model has the same orientation as cura A 

**Actual:**
Message is shown (OK)
Model does not have the same orientation (Maybe ok? IDK?)

Alternatively, you can similar weird-ish results if you remove / add an object to the 3mf. In that case the changes are also not executed (So instead of orientation step, you multiply the object). 

So what to do with this? In some cases, it does improves the behavior (eg; the mesh data is changed), but it's not quite there yet.

**Comment by Ghostkeeper** [comment]
When reloading an STL, it also keeps the current orientation. That's probably why it's also kept for 3MF. There is no disambiguation between the transformations obtained from the project and the transformations applied by the user later.

I don't think there is an easy way to solve this.

**Comment by nallath** [comment]
For our reference; CURA-7309

**Comment by nallath** [comment]
Decided to merge this since it is an improvement over the default behavior (even if it's not completely the right one)

**Comment by BagelOrb** [comment]
So it will be in 4.6?
Awesome!

This should fix my workflow. I should then be able to export from SolidWorks to 3mf and have my files updated without having to reposition and redo all of my support blockers. Or is that still not working?

**Comment by BagelOrb** [comment]
> I don't think there is an easy way to solve this.

We're just talking about saving two transformations: one from the original source file and one from Cura. Saving two transformations in the project file shouldn't be that difficult, right?

**Comment by Ghostkeeper** [comment]
It's in 4.6. We're still working out some kinks though. It's not reloading properly with multiple objects in the 3MF file.

**Comment by Ghostkeeper** [comment]
> Saving two transformations in the project file shouldn't be that difficult, right?

It would also need to be saved in the scene.

**Comment by BagelOrb** [comment]
Ah yes. Although you could also merge the matrices before, and when saving to file, apply the inverse of the original matrix to separate the two matrices again. All in all still not so easy.

**Pull request merged**
