### PR TITLE
Adding printer definition for Anycubic i3 Mega & Tevo Black Widow

### PR DESCRIPTION
**Pull request by thetobby**
Adding Definition for _Anycubic i3 Mega_ and  Tevo Black Widow from the user manual and community information.

Two very popular 3D printer that i think beginners will appreciate that have definitions.

### CODE REVIEW

**Comment by thetobby** [comment]
Added quality profiles and material for Anycubic i3 Mega :)

**Comment by thetobby** [comment]
Added 3D Platform for Anycubic i3 Mega

**Comment by thetobby** [comment]
Decided to put has_material = false and focus on Quality profile and definition. Materials is to much work, but might get added in a later revision after merge. Have to tweake profiles and create 3D model for Tevo, so soon done. Will have a look at other printers after. Please give me some feedback on the layout of what settings is written where.  Oh and, writing something = Enable (instead of True crashes the whole application). Been there, done that :)

**Comment by thetobby** [comment]
Good news regarding model for Tevo Black widow.
Roel Versteeg (Rovex) has kindly agreed to let us use his model of the printer, https://www.thingiverse.com/thing:1933864
Since the model is a bit to detailed for our use I have spoken with Jon MC (security0051) that had already modified the model https://www.thingiverse.com/thing:2592417. He has also agreed to let us use his version. Thank you guys.

**Comment by jackha** [comment]
Thanks! 
Devs, see: CURA-4752

**Comment by Ghostkeeper** [comment]
That Tevo model is a bit big of a file size. I'll see what I can do to decimate. Our guideline is 1MB.

**Comment by Ghostkeeper** [comment]
Oh and it was also unused. Did this get tested?

**Comment by thetobby** [comment]
The models show in the editor at least for me when testing locally here with a clean 3.1 on windows, I retested it now. Any idea what the cause is? (perhaps open issue ticket or PR if you find it).
I was not aware of any guidelines for file size. If you can, please see what you can do.

**Comment by Ghostkeeper** [comment]
Like if you search for "tevo_blackwidow.stl" in this PR you get no results other than the file itself. Also the model in this PR is 4.13MB.

The file is now 845kB since I've decimated it (see this commit: https://github.com/Ultimaker/Cura/commit/8aa51658e28c96f8fd6d41049af3a9fedb2c6089). It's now also used in the proper definition since I fixed it (in this commit: https://github.com/Ultimaker/Cura/commit/39aec54a56b566e4f08fa5ccd0fc476d8d1ceb79)

**Pull request merged**
