### PR TITLE
Added the Artillery Sidewinder X1 and Genius

### PR DESCRIPTION
**Pull request by cataclism**
Added the Artillery Sidewinder X1 and Genius.
Hope everything right.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
These files are 5 releases out of date. Please update them to setting_version 15 and make sure that the print quality is the same. In particular, the Maximum Resolution setting has changed meaning since then.

The automated tests are also complaining that the JSON structure is incorrect.

**Comment by cataclism** [comment]
@Ghostkeeper how do i fix the JSON files? Why the structure is incorrct and how do i make it correct? I'm sorry but i'm a newbie here in git

**Comment by PAPPL** [comment]
Hope this will somehow fixed.
Atm Artillery Sidewinder X1 users are basically stuck to downloading 3DN Settings and Profiles for Cura.
https://3d-nexus.com/resources/file-archives/download/8-artillery-evnovo/32-3dn-artillery-swx1-and-genius-cura-4-6-1-machines-and-profiles-installation-package
They work fine with my Sidewinder X1, as many other users report too.

**Comment by Ghostkeeper** [comment]
> @Ghostkeeper how do i fix the JSON files? Why the structure is incorrct and how do i make it correct? I'm sorry but i'm a newbie here in git

It's admittedly pretty hard to read through the noise. In the [test output](https://github.com/Ultimaker/Cura/runs/1092971559) it does say why it's failing:

```
----------------------------- Captured stdout call -----------------------------
[MainThread] UM.Settings.DefinitionContainer._preprocessParsedJson [299]: Unable to override setting machine_head_polygon
```

The setting `machine_head_polygon` doesn't exist any more, but your definitions still try to give it a value.

Today we also upped the `setting_version` for the 4.8 upgrade, which means that `setting_version` now needs to be 16. Sorry about that. The changes we made are to the unit of the `material_shrinkage_factor` setting, which I don't think you are using.

**Comment by cataclism** [comment]
@Ghostkeeper I finally passed the pytest ahahha

**Comment by Ghostkeeper** [comment]
Artillery's printers are the ones I see the most errors from coming in from people who mod it in their own Cura installations. So hopefully this PR would make all of those mods unnecessary ;)

**Comment by cataclism** [comment]
@Ghostkeeper I hope so too. I hope that everything is correct. How do I know if it will be added in the next cura release?

**Comment by konskarm** [comment]
Hi @cataclism. I just noticed a couple of things. 

- You have put all generic materials in the "exclude_materials" field, even though you have qualities for some of them (e.g. generic_abs and generic_pla). 
- In the generic ABS, PETG, and TPU your 0.4mm nozzle has qualities 0.12-0.28 which makes sense, but then your 0.6mm nozzle has only for 0.2, which seems a bit strange. PLA properly has qualities for layer heights 0.2-0.32mm in the 0.6 nozzle.

Are the above done on purpose?

**Comment by cataclism** [comment]
@konskarm I'll add again generic_pla,generic_abs,generic_petg,generic_tpu. 

For 0.8mm and 1.0mm nozzle i've left only 0.2 because I thought that they are not often used, and so if someone wants to use it he can change the layer height by himself.

And i'll add more layer heights for 0.6mm nozzle.

If something is wrong or if I have to make changes please let me know

**Comment by konskarm** [comment]
> @konskarm I'll add again generic_pla,generic_abs,generic_petg,generic_tpu.
> 
> For 0.8mm and 1.0mm nozzle i've left only 0.2 because I thought that they are not often used, and so if someone wants to use it he can change the layer height by himself.
> 
> And i'll add more layer heights for 0.6mm nozzle.
> 
> If something is wrong or if I have to make changes please let me know

Don't get me wrong, it may be fine for your printers, I was just wondering if my observations were done intentionally on your end. It doesn't mean that they are wrong or they won't work!

**Comment by cataclism** [comment]
Hi@konskarm 
Yeah, I did it intentionally. Since most of users use 0.4mm nozzle and everything worked like a charm, I didn't ask myself the problem and I didn't want to change too many things, risking not to make everything work anymore.

And if you swap the nozzle with a different one I thought that you are able to work yourself with the profile. 
Tell me if I am wrong.

Anyway, tell me if everything works and if CURA slices correctly (and if it can be merged)
If I have to introduce any modification please let me know. =)

**Comment by konskarm** [comment]
Hi @cataclism. Sometimes PRs are a bit slow due to built-up work that we have. I'll try to get around to it as soon as possible. Be sure that I will definitely do it in time for 4.8!

**Review by konskarm — CHANGES_REQUESTED** [review]

**Comment by cataclism** [comment]
@konskarm 
I really hope that everithing now is right. I'm sorry but i'm a newbie and i'm not pratctical here in GitHub.
I hope I don't waste ou time

**Comment by PAPPL** [comment]
Hi, i'm so happy reading this conversation. Thanks for your work!

**Comment by cataclism** [comment]
> Hi, i'm so happy reading this conversation. Thanks for your work!

@PAPPL Thank you! I really hope everything is right! 🤞

**Comment by ark-** [comment]
I wondered if anyone knew the config for the X2? I believe all you need to add is the auto level command to the G code.

**Pull request merged**
