### PR TITLE
Add DXU UMO+ definition for UMO+ printer frame

### PR DESCRIPTION
**Pull request by ansonl**
Updated Ultimaker community DXU mod definition with correct values for UMO+ frame.

### CODE REVIEW

**Comment by nallath** [comment]
Did you intentionally leave this PR in draft?

**Comment by ansonl** [comment]
The empty nozzle selection issue is resolved when using the printer definitions in Cura 5 or later.

**Comment by jellespijker** [comment]
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

**Comment by ansonl** [comment]
@jellespijker Sure , I have synced my fork with the Cura main.

**Comment by jellespijker** [comment]
Could you do that again, one of the workflows seemed to have an error, which resulted in auto formatting of to much files. I applied a fix, such that it shouldn't happen

**Comment by ansonl** [comment]
@jellespijker I synced my fork again.

**Comment by jellespijker** [comment]
@ansonl don't commit the suggested fixes straight from the GitHub GUI, but do these locally.Otherwise you will have an ill-formed json. This is a bug in the printer-linter I will investigate

**Comment by ansonl** [comment]
@jellespijker Okay, I've made the changes as suggested by the linter.

**Comment by jellespijker** [comment]
LGTM;

Thanks for helping me test this new PR workflow, I will make a quick fixes tomorrow morning, for the GitHub GUI commit option.

I'm gonna press merge, Your printer should be in Cura 5.3

**Pull request merged**
