### PR TITLE
Update our machine DUAL600 & IDEX420

### PR DESCRIPTION
**Pull request by eMotion-Tech**
# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Printer definition file(s)
- [ ] Translations

# How Has This Been Tested?

- [x] Test A
- [x] Test B

**Test Configuration**:
* Operating System:

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by eMotion-Tech** [comment]
Hi, I can't pass the unit-test and I don't know why ?
I have only change définition file of my printer can you help me ?
My pr it's ok to pass or not ?
thank you very much

**Comment by eMotion-Tech** [comment]
I think we have found our problems.
Waiting from you now.

**Comment by eMotion-Tech** [comment]
We think the clang-tidy is fix

**Comment by qleboeuf** [comment]
No help about this ?

**Comment by qleboeuf** [comment]
hi @MariMakes we don't have update from you since a while ? There is something that we can do ?

**Comment by saumyaj3** [comment]
Hi!
Thankyou for your contribution. I was reviewing the PR and found material "emotiontech_pa6cf" not present in fdm_materials (https://github.com/Ultimaker/fdm_materials). Can you also add it there? Also, if you have created a PR there, please tag it here.

**Comment by QuentinADM** [comment]
Hi @saumyaj3 We have add file and fix PR on https://github.com/Ultimaker/fdm_materials/pull/227 and we have click on button "Ready for review" like asking. It's ok for you ?

**Comment by saumyaj3** [comment]
> Hi @saumyaj3 We have add file and fix PR on [Ultimaker/fdm_materials#227](https://github.com/Ultimaker/fdm_materials/pull/227) and we have click on button "Ready for review" like asking. It's ok for you ?

Hi @QuentinADM,
I see the comments in the PR :https://github.com/Ultimaker/fdm_materials/pull/227 are not fixed yet. Can you make sure to undo deleted file and update PR?

**Comment by saumyaj3** [comment]
New Pr for fdm materials: https://github.com/Ultimaker/fdm_materials/pull/249

**Review by saumyaj3 — APPROVED** [review]

**Pull request merged**
