### PR TITLE
Add Creality Ender 3 V3 SE definition and nozzles

### PR DESCRIPTION
**Pull request by dim1triy**
Hi. This PR add printer Creality Ender 3 V3 SE

### CODE REVIEW

**Comment by RichardMawdsley** [comment]
Great work @dim1triy - Looking forward to this.

**Comment by nima3333** [comment]
Great work, I would suggest to add retraction (```retraction_amount": { "value": 0.8 }```) and speed settings in the json to match the default settings provided by the manufacturer.
I am still doing some adjustments on my side so I cannot help.

**Comment by manugildev** [comment]
@github-actions @dim1triy requested changes have been made. How can we get this merged?

**Comment by dim1triy** [comment]
@manugildev Hi. This PR is completed. What more can I do?

**Comment by doubledare704** [comment]
Looking for this PR too

**Comment by ytsipun** [comment]
Can it be merged, please?

**Comment by Silicon7921** [comment]
if you really need these cfg files,you can open Ultimaker Cura\share\cura\resources
and put them into correct folders.

**Comment by Silicon7921** [comment]
how to add your own configuation:
1.Launch Cura
2.click Help(H)
3.show configuation folder
4.put def file into "definitions" folder  (DO NOT RENAME FILE)
5.put variants files into "variants" folder
6.colse Cura and open it again
7.add your printer in the "Add printer" menu.
i tried and it works

**Comment by scotty6435** [comment]
@saumyaj3 this PR should be clear to merge but the github-actions bot is not re-reviewing. As an owner of a new Ender 3 V3 SE I know I'd rather more owners don't have to patch in support from this PR

**Review by saumyaj3 — APPROVED** [review]

**Comment by saumyaj3** [comment]
Hey @dim1triy Thanks for your contribution! These changes will be now available in the next Cura version. 
If anyone wants to use these machines before please check:
https://github.com/Ultimaker/Cura/pull/16796#issuecomment-1748634700

**Comment by pcalej** [comment]
Hi! Just got my v3 SE. Fingers crossed the new profile gets added soon!

**Comment by phamaralbr** [comment]
The profile is not available in the new 5.5.0 version. I had to add it manually.

**Comment by tijsrx** [comment]
I have some problems with this:

1) clicking on 'show configuation folder' does nothing, I had to go manually to this folder
2) adding the def file does nothing, it doesn't show up in the list of printers (neither custom or creality) after restarting Cura
3) I have no variants folder, so I added this manually, but the printer still isn't showing up

**Comment by 9sixty9** [comment]
can someone please guide me on installing this into cura 5.50

**Comment by joddoc** [comment]
> can someone please guide me on installing this into cura 5.50

I can! In the commit above you can see all the files which will be added in the next version. 

Direct link to the commit is here:
https://github.com/Ultimaker/Cura/commit/7d9d6cbf6abd7b66a8d3a1d40f1b58f90e07d889 : open this link. 
- You can see that there are several files in the commit: 1 in the "variants" folder and 7 in the variants/creality (sub)folder. We need to download all files and manually get it into your Cura program folder. 

For each file: Click on the 3 dots on the right hand side, then select "View File": 
grafik
In the file view in github, click on the download icon and store each file on your computer. 
grafik
Repeat for each file in the commit link above.

Then, follow instructions from [Silicon7921](https://github.com/Silicon7921) (slightly adapted..):
1.Launch Cura
2. click Help(H)
3. show configuation folder
4.put the downloaded file ending with  _**.def.json**_ into "definitions" folder (DO NOT RENAME FILE)
5. go to folder "variants" and create a new subfolder "creality"
5.put variants files (all downloaded files ending with _**.inst.cfg**_ into "variants/creality" folder
6.close Cura and open it again
7.add your printer in the "Add printer" menu.
:)

**Comment by 9sixty9** [comment]
Thank you, I’m just going out for a couple of hours but will try this when I get home, again thank you very much Regards,AdamM: 0411199694E: ***@***.*** 13 Nov 2023, at 7:53 am, joddoc ***@***.***> wrote:﻿

can someone please guide me on installing this into cura 5.50

I can! In the commit above you can see all the files which will be added in the next version.
Direct link to the commit is here:
7d9d6cb : open this link.

You can see that there are several files in the commit: 1 in the "variants" folder and 7 in the variants/creality (sub)folder. We need to download all files and manually get it into your Cura program folder.

For each file: Click on the 3 dots on the right hand side, then select "View File":

In the file view in github, click on the download icon and store each file on your computer.

Repeat for each file in the commit link above.
Then, follow instructions from Silicon7921 (slightly adapted..):
1.Launch Cura
2. click Help(H)
3. show configuation folder
4.put the downloaded file ending with  .def.json into "definitions" folder (DO NOT RENAME FILE)
5. go to folder "variants" and create a new subfolder "creality"
5.put variants files (all downloaded files ending with .inst.cfg into "variants/creality" folder
6.close Cura and open it again
7.add your printer in the "Add printer" menu.
:)

**Comment by jusvit** [comment]
Can you add the platform back in? You can either use the existing one for Ender 3 or tailor it to fix better.

All you have to do is add this to the meta data:


```json
{
 "metadata": {
   "platform": "creality_ender3.3mf"
  }
}
```

image

**Comment by mindaugazzz** [comment]
Hello, with this 3v3 se profile I have a hole in my bed.  After printing 2 or 3 layers I hit "pause" on the printer and the nozzle went back to the front left corner leaving a hole in it. Cura 5.6.0

**Comment by dim1triy** [comment]
Hi. https://github.com/Ultimaker/Cura/pull/17669 if need to add too else, please write to pr

**Comment by Liionboy** [comment]
> > can someone please guide me on installing this into cura 5.50
> 
> I can! In the commit above you can see all the files which will be added in the next version.
> 
> Direct link to the commit is here: [7d9d6cb](https://github.com/Ultimaker/Cura/commit/7d9d6cbf6abd7b66a8d3a1d40f1b58f90e07d889) : open this link.
> 
> * You can see that there are several files in the commit: 1 in the "variants" folder and 7 in the variants/creality (sub)folder. We need to download all files and manually get it into your Cura program folder.
> 
> For each file: Click on the 3 dots on the right hand side, then select "View File": grafik In the file view in github, click on the download icon and store each file on your computer. grafik Repeat for each file in the commit link above.
> 
> Then, follow instructions from [Silicon7921](https://github.com/Silicon7921) (slightly adapted..): 1.Launch Cura 2. click Help(H) 3. show configuation folder 4.put the downloaded file ending with _**.def.json**_ into "definitions" folder (DO NOT RENAME FILE) 5. go to folder "variants" and create a new subfolder "creality" 5.put variants files (all downloaded files ending with _**.inst.cfg**_ into "variants/creality" folder 6.close Cura and open it again 7.add your printer in the "Add printer" menu. :)

An a G-Code start forr Klipper you have? because is on Marlin G-Code Flavour and not working very well

Thanks

**Pull request merged**
