### PR TITLE
[CURA-1445] SliceInfo: Using HTTPS again

### PR DESCRIPTION
**Pull request by thopiekar**
The problem seems to be related to our HTTP(S) server.
It is expected that the problem will be solved after the weekend.

Contributes to CURA-1445

### CODE REVIEW

**Comment by fieldOfView** [comment]
I think you meant to commit a bit more...

**Comment by thopiekar** [comment]
Nope, it is a server issue as far as I analysed with Jordy @ YM. There is no HTTPS request the YM server answers to.
All the SliceInfo (only <= 14.x) doesn't get into the server. So respecting privacy I just made this PR.
On Monday Wilco should care about it..

**Comment by fieldOfView** [comment]
Then what's the use of this PR? All it does is add a newline at the end of a file.

**Comment by thopiekar** [comment]
Oh, looks like Jack only applied his HTTP workaround only on master.
Well, then you don't see any changes here. I changed the URL on master and cherry-picked it on 2.3, because I thought it will be needed here, too..

**Comment by thopiekar** [comment]
So you can git merge or just close it. Feel free..

**Pull request closed without merging**
