### PR TITLE
CURA-7240 De-emphasize bundled packages

### PR DESCRIPTION
**Pull request by rburema**
... because users probably want to manage their own installed plugins and materials, not the already bundled ones.

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
image

Looking a bit funny if one of the sections is empty

**Comment by fieldOfView** [comment]
I always sort of dislike the "My" moniker; it is a bit Windows XP. Can I suggest "Marketplace plugins" or "Plugins installed from the Marketplace" ?

**Comment by rburema** [comment]
> Looking a bit funny if one of the sections is empty

> I always sort of dislike the "My" moniker; 

@Yian-Lai If you have some time, can you give your opinion about these?

**Comment by Yian-Lai** [comment]
> > Looking a bit funny if one of the sections is empty
>
> > I always sort of dislike the "My" moniker;
> 
> @Yian-Lai If you have some time, can you give your opinion about these?

Can we hide the whole section if there is no materials/plugins?

I think "My installed XX" is more straightforward, it also covers cases of user manually install plugins/materials, like PPA.

**Comment by fieldOfView** [comment]
> I think "My installed XX" is more straightforward,

But it is semantically incorrect. The plugins/materials are not mine. What is meant is that I installed them. But that is not what it says. If anything it should be "Plugins installed by me". 

> Jaime and I agreed to

Oh. I agree with that too, and like it much better.

**Comment by rburema** [comment]
Closing this in favour of https://github.com/Ultimaker/Cura/pull/7378 (which is the same, but with all the kinks ironed out).

**Pull request closed without merging**
