### PR TITLE
Adding support for Elegoo Neptune 4 Pro (#16608 follow-up)

### PR DESCRIPTION
**Pull request by fuji97**
# Description
This adds support for the Elegoo Neptune 4 Pro printer. Created elegoo_neptune_4pro.def.json for Neptune 4 Pro profile.

This is a follow-up of #16608 with the missing variants since the author of the original PR hasn't posted since they made it. I left the original author's name in the definition since they made it.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Printer definition file(s)
- [ ] Translations

# How Has This Been Tested?

- [x] Test A - Setup as Custom FFF printer, and used the g-code provided by Elegoo in their skinned version of Cura.
- [x] Test B - Printed multiple parts with Custom FFF profile to test g-code.

**Test Configuration**:
* Operating System: Windows 11 Cura 5.4.

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by cvanelteren** [comment]
Thanks! The default nozzle is 0.2 mm correct?

**Comment by ToasterUwU** [comment]
> Thanks! The default nozzle is 0.2 mm correct?

If you mean for the printer, yes. The built in nozzle from Elegoo is 0.2mm

**Review by cvanelteren — COMMENTED** [review]
The Neptune 4 default nozzle 0.2mm is labeled as Neptune 3 pro.

**Comment by fuji97** [comment]
Ok, I fixed the name and now the CI/CD has passed correctly

**Comment by cvanelteren** [comment]
Great!

**Comment by ToasterUwU** [comment]
Very new to Cura and 3D printing in general.

If I wanted to test this, in theory I would just copy the files to the right place, start Cura and the option shows up, right?

**Comment by cvanelteren** [comment]
It does @ToasterUwU. You can also clone the repo above and change nothing. Just follow the build instructions on the cura website.

**Comment by ToasterUwU** [comment]
@cvanelteren I checked again, the standard nozzle is 0.4mm in the elegoo Cura version. I'm not skilled or equipped enough to measure the physical nozzle, and as far as I can see, there aren't any labels on it. So the software they ship having 0.4mm configured is the best I have. I also corrected my earlier comment.

**Comment by cvanelteren** [comment]
Ok thanks! For posterity, you can run the PR locally as:

```
git fetch origin #16819:definitions/neptune4pro
git checkout definitions/neptune4pro
```

**Comment by ToasterUwU** [comment]
I tested the config, and I obviously don't know why, but it was worse then whatever elegoo does in their custom cura version.

Specifically prints that work fine with custom cura, got spaghetti nests in challenging parts with this. Also for some odd reason the z movement seems different, because with this it keeps scratching the last layer and even ripped a tree support so hard it clean broke like 30 layers down. Meanwhile with elegoo cura this doesn't happen at all.

I can't be 100% this wasn't just unlucky or even user error, but I'm at least pretty certain it's not my fault, I just setup the printer, left the default settings be, loaded the stl, configured the support options like I need them, done.

**Comment by cvanelteren** [comment]
I had similar issues initially with this version of cura(5.5 beta 1). I believe there is no one to one translation of the old cura settings into the new one. For example the print speed is set lower with the new cura than the custom version cura provided by elegoo. I'm also not sure what causes the changes. I got it to print now with this newer version but can't really provide pointers as to what caused the major change in the print quality. The major outline is the standard bed leveling, I also changed the rotation distance and some pressure advance settings. I haven't been able to get to the same quality as the g code provided by the usb stick. But this is a bit off topic in general.

**Comment by ToasterUwU** [comment]
At least im not alone.

I will keep coming back to normal cura and testing the current stuff, but for now I will stick to elegoo cura trough wine

**Comment by mastercaution** [comment]
I'm also working on a Neptune 4 profile (non-pro, but they are almost identical) for Cura 5.4. However, I took a different approach than #16608 and this PR:

Since the `elegoo_base` definition and its profiles have many settings that are specific to previous models (Neptune 3, 2, ...), I decided to build a new definition and corresponding profiles based on `fdmprinter`. The `elegoo_base` quality profiles contain acceleration and speed values that are way below the capabilities of the Neptune 4/Pro.

The best way probably would be to redesign `elegoo_base`, so that it does not contain _any_ printer specific setting ... well, but theoretically all settings are printer specific. Since we don't know what printers will be released in the future, we might end up fixing `elegoo_base` for every new generation and trying to not break previous models. Therefore, I think it's best to create a new definition that not depends on `elegoo_base`.

My approach was to combine the settings from `elego_base` and settings from the custom Elegoo Cura for the Neptune 4. I tested them on my Neptune 4 and they work fine, without any catastrophic issues (yet). Currently, I'm only fine-tuning the quality presets (suggestions are very welcome :wink:)

You can test the profiles from my fork: https://github.com/mastercaution/Cura/tree/elegoo_neptune_4_series
(I will add a zip later, for easy copy-pasting)

@fuji97 what are your thoughts about that?

**Comment by cvanelteren** [comment]
Isn't it possible to override these settings rather using a different base?

**Comment by mastercaution** [comment]
> Isn't it possible to override these settings rather using a different base?

I didn't find a way to do that, because the quality profiles seem to have a higher priority and overwrite the settings from the definition file.

**Comment by cvanelteren** [comment]
There are some different default settings from these files. You said these are directly from the Cura version provided by Elegoo? i guess they should take priority over the once proposed here. They are more conservative and print fine on my end but faster is better.

**Comment by fuji97** [comment]
@mastercaution That's not a bad idea, if settings between printers differ to much a base `elegoo_base` definition is not particularly useful. I can't test configurations right now because I'm having some issues with the Z-axis and bed leveling, when I resolve those I will test them.

**Comment by mastercaution** [comment]
> There are some different default settings from these files. You said these are directly from the Cura version provided by Elegoo?

Yes, things like the gcode flavor, acceleration and the `maximum_value_warning` for the speeds settings are from Elegoo, as well as some settings in the presets.

I set `machine_depth` to 230 instead of 235 because my Y can only move to a maximum of approx. 233, where it hits the limit. Most end-gcode moves Y to `machine_depth` to present the print, which in my case results in the bed crashing into the limit. Although, Elegoo has set a `machine_depth` of 235, their end-gcode moves Y only up to 230 ... so they also had this issue? My brother's printer has the same issue. Are there Neptune 4/pros out there that can move Y all the way to 235? The firmware limit is also set to 235.

The `retraction_amount` (0.5) is from Elegoo but I increased the `retraction_speed` from 30 to 45 as suggested by the Youtuber mpoxDE in his [profiles](https://mpox.gumroad.com/l/nptn4pro) for Cura <5.4.

**Comment by cvanelteren** [comment]
Just applied just the new definition file on a neptune 4 pro. So far no issues.

**Comment by mastercaution** [comment]
The problem with `"quality_definition": "elegoo_base"` is that some quality presets have speed and acceleration values which are tune for a Neptune 3. Here are some examples showing the issues with the profiles:
- "Default Fast": Wall acceleration changed to 2000, N4 can easily do 3000. Reason: https://github.com/Ultimaker/Cura/blob/24e1cfa2b7b8db480cf8992ca92e31c8d9c7963f/resources/quality/elegoo/base/pla/nozzle_0_40/elegoo_pla_nozzle_0.40_layer_0.20.inst.cfg#L14-L15
- "Draft Extra Fast": Should be extra fast, right? But print speed is set to 50 mm/s ... this is not "fast" for a N4 at all. Reason: https://github.com/Ultimaker/Cura/blob/24e1cfa2b7b8db480cf8992ca92e31c8d9c7963f/resources/intent/elegoo_base/PLA/elegoo_base_aa0.4_pla_0.3mm_quick.inst.cfg#L22

There is no way of overwriting these quality definitions, only to create new ones.

This is my take on using `elegoo_base` in the definition: https://github.com/mastercaution/Cura/releases/tag/v0.4
Unfortunately, I think it's not possible to reduce the redundancy in the quality definition files. It seems impossible for the N4 definition to update quality presets from the base definition.

**Comment by cvanelteren** [comment]
@machinekoder  your version keeps crashing for me  when I add the printer

**Comment by mastercaution** [comment]
Oh, thanks! I forgot to remove the `machine_extruder_trains` ^^

[v0.5.1](https://github.com/mastercaution/Cura/releases/tag/v0.5.1) should be working now :wink:

(do you mean `@mastercaution` instead of `@machinekoder`?)

**Comment by cvanelteren** [comment]
Ah wrong ping my bad @mastercaution. I have done a few prints with your PR, works great! Initial layers are bit funky and flimsy, but after its goes fine.

**Comment by mastercaution** [comment]
> Initial layers are bit funky and flimsy, but after its goes fine.

Is there something I can improve? Maybe, increasing the initial layer height? Currently, the setting for the initial layer height is identical to the Elegoo base quality presets, and they work perfectly fine on my N4 (good adhesion and everything).

> Perhaps after the full Neptune 4 line is released, a refactor can pull out a Neptune 4 base.

Yes, exactly! I already use the Neptune 4 definition as a base for the Neptune 4 Pro :smile:

> perhaps we can merge with the PR above?

If it's okay for you @fuji97 and @cvanelteren, I would prefer to open a new PR because my profiles are not based on this PR or #16608 and differ quite a bit :sweat_smile:

**Comment by cvanelteren** [comment]
I believe for me there is an issue with the z-axis offset being too close to the bed initially and later being fine. I am still trying to figure out what the exact issue is.  

My two cents are that another PR would be unecessary. This is already the second, whereas we could just merge them. This also makes it clear where the discussion was (for future reference).

**Comment by ToasterUwU** [comment]
Yeah, please let's not make a third PR. A second one (even if needed like in this case) is already bad enough

**Comment by fuji97** [comment]
Okay, I finally fixed the main issues with my Neptune 4 Pro, and so I was able to test @mastercaution settings. I did some prints and, apart from printing issues unrelated to the settings (I'm currently printing PLA in an environment with about 68% humidity), they are pretty good, so no issue with them for me.

For the PR, since @cvanelteren and @ToasterUwU (and me too) think that we already have enough duplicate PRs if @mastercaution gives his approval, I will merge his branch with this PR

**Comment by mastercaution** [comment]
@fuji97 You're good to go! :smile:

**Comment by mastercaution** [comment]
> Are there Neptune 4/pros out there that can move Y all the way to 235?

What about the maximum Y value? Can someone test it on their printer?
I tested it via the fluidd console:
1. Home Y axis
2. `G0 Y230` to move it to 230mm
3. Increase millimeters one by one (`G0 Y231`, `G0 Y232`, ...) until it reaches the limit (you can hear it)

Mine is 232 (it cannot move to 233)

**Comment by ToasterUwU** [comment]
Can we also make sure to use the bed mesh out of the box? As far as I know, currently the bed mesh is not used by Elegoo Cura. But there is a thing to enable it, that if I understand right (as the noob I am) its a thing you can add to the starting GCode.

Source of this (maybe wrong) info: https://www.reddit.com/r/ElegooNeptune4/comments/16zjdjg/comment/k3f4x3l/?utm_source=share&utm_medium=web2x&context=3

**Comment by cvanelteren** [comment]
The post says there is a setting inside cura can add to make the z axis
retract more. The bed mesh (I am assuming) is handled by the firmware not
by cura.

**Comment by fuji97** [comment]
@mastercaution I've directly merged your branch and reverted the old changes. If you want, you can fix the issues and I'll merge the branch again. Alternatively, I can try to fix them, but this will diverge from your branch

**Comment by mastercaution** [comment]
@ToasterUwU It's handled by firmware (like @cvanelteren assumed). You should find `BED_MESH_PROFILE LOAD=default` in the gcode macro `PRINT_START` inside your printer.cfg.

**Comment by mastercaution** [comment]
@fuji97 Thank you for merging! I (hopefully) fixed the `clang-tidy` issues. You can merge again :smile:

**Comment by ToasterUwU** [comment]
@fuji97 please don't bail on us like the other guy did, not thinking you are actively trying to, but still. 
We need your input here.

**Comment by fuji97** [comment]
@ToasterUwU Sorry, I was on vacation for 3 days and I forgot to watch this thread

**Comment by ToasterUwU** [comment]
@fuji97 ohh OK, in that case I'm sorry for bothering you, was just worried we will have a third PR soon

**Comment by fuji97** [comment]
@mastercaution Ok, I merged your last changes, sorry for the delay

**Comment by mastercaution** [comment]
Aargh, one more test was still failing. It said: 
```
Unnecessary default_values for ['infill_line_width', 'speed_layer_0', 'speed_topbottom', 'speed_travel', 'speed_travel_layer_0', 'speed_wall', 'speed_wall_0', 'speed_wall_x']
```
So, I removed the default values for those settings (ae50a047f5da79f77abc0ae36133a7609fb02547). They had indeed no effect.
@fuji97 let's give it another try :sweat_smile:

**Comment by kristian** [comment]
Looking forward seeing this one merged! Thanks for all the efforts! =)

**Comment by cvanelteren** [comment]
Some tests are still failing. Fiy orca-slicer has neptune 4 profiles already implemented (1.7.0).

**Comment by kristian** [comment]
@fuji97 and @mastercaution I tried this PR with a clean profile, on my slices, I get a backend exception:

> Backend exited abnormally with return code 3221226505!

The error is:

[error] Trying to retrieve setting with no value given: group_outer_walls

I did not make any changes to the profile, is there anything wrong with the profile or my setup?

**Comment by kristian** [comment]
I think it is in regards to this new setting: https://github.com/Ultimaker/CuraEngine/commit/ec8bcfc3ad346fa21dde94b188caa84e18fcae06 Does it have to be reflected in the new profile maybe?

**Comment by kristian** [comment]
> @fuji97 and @mastercaution I tried this PR with a clean profile, on my slices, I get a backend exception:
> 
> `Backend exited abnormally with return code 3221226505!`
> 
> The error is:
> 
> `[error] Trying to retrieve setting with no value given: group_outer_walls`
> 
> I did not make any changes to the profile, is there anything wrong with the profile or my setup?
> 
> I think it is in regards to this new setting: [Ultimaker/CuraEngine@ec8bcfc](https://github.com/Ultimaker/CuraEngine/commit/ec8bcfc3ad346fa21dde94b188caa84e18fcae06) Does it have to be reflected in the new profile maybe?

I meanwhile rebased the commit to the latest commit on the main branch, which seems to have solved the `group_outer_walls` issue, now I get another error:

```[error] Trying to retrieve setting with no value given: wall_0_material_flow_roofing```

Again I think it is related to a recent change in the CuraEngine: https://github.com/Ultimaker/CuraEngine/commit/3787b2c73369052182ea2b359f372f38f5dc5fe5

Anything I can do to fix this temporarily? Thanks!

**Comment by mastercaution** [comment]
> I meanwhile rebased the commit to the latest commit on the main branch, which seems to have solved the group_outer_walls issue

Yep, the profiles inherit from the `fdmprinter` definition, which now provides a default value. The same should be true for `wall_0_material_flow_roofing`: https://github.com/Ultimaker/Cura/blob/dcd01db7c4e129e8e9bd88dc91339b4afb0b7f72/resources/definitions/fdmprinter.def.json#L2865-L2872)

Maybe it helps to clear Cura's cache to delete previously compiled but outdated definitions?

**Comment by kristian** [comment]
Thanks for the hint @mastercaution! After cleaning Cura's AppData and the Conan compile cache, I was able to slice a model with the new Elegoo Neptune 4 Pro profile! 👍 Thanks so much! Hope to see this one merged soon 👍

**Comment by flixhsw** [comment]
Hi, I just recently got a Neptune 4 pro and have little experience.
Still, I want to confirm, that the files from this PR work fine for me with Cura 5.4.0.

There is a small improvement, I would like to see: After printing, the print head should move like 20mm upwards (z-axis). Then it would be much easier to remove the magnetic floor bed (this at least is true for models, with only little height).

As I am on ubuntu linux, I asked elegoo for a config file for cura on linux. They sent me a PDF listing all the parameters (for cura 4.8.0).

**Comment by cvanelteren** [comment]
You can add this in the machine end gcode in cura and save as a new config.

**Comment by mastercaution** [comment]
> Quick comparison showed, that the Printhead settings differ quite a bit. According to the Elegoo PDF they should be x min=-20, y min=-10, x max = 10, y max = 10, gantry height=270. However, they are -40, -30, 40, 50, 250.

Thanks for testing! I changed the print head polygon to values I measured myself (from nozzle 40mm to the sides, 50mm to the front and 40mm to the back including the sensor). More documentation on the setting [here](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/machine_settings/machine_head_with_fans_polygon.md).

**Comment by gaima8** [comment]
Thanks all for this, I got my Neptune 4 Pro yesterday and within an hour or so was printing my first sliced model! Most of that was figuring out Conan and running Cura from git too.

Couple things if I may.

- https://github.com/Ultimaker/Cura/pull/16819#issuecomment-1735735754 didn't work out for me, git just didn't do anything. The following did though.
```
git fetch origin pull/16819/head:BRANCH_NAME
git switch BRANCH_NAME
```
- https://github.com/Ultimaker/Cura/pull/16819#issuecomment-1753062204 affected me too. To resolve it I just had to merge from main
```
git merge main
```
- The position of prints seems off by about 5mm to the front. Such that I have moved the PEI sheet off the front of the build plate a little. Printing an object that's 224mm long with a brim is longer than the build plate is deep, the brim at the front prints a few mm into thin air and the rear is cut off sharply about 5mm from the edge. In Cura the object is pushed right up to the back of the bed to get a good print. Overall my bed is 235mm deep (excluding the section to grab it by hand), and the machine appears to be able to reach all of that. 
- `machine_end_code` includes the following literal string causing an error at the end of a print.
```
G1 X0 Y{machine_depth} ;Present print
```
I haven't yet been able to dig down through the json to work out why the value of `machine_depth` isn't being interpolated. I also have no idea at all what I'm doing, but I do know the value `speed_travel` is interpolated somehow for an Anycubic Vyper.

**Comment by mastercaution** [comment]
@gaima8 I made a test print but I was not able to reproduce your issues. Nothing was printed into thin air and the print end-code worked as expected.

Here is my result: 
PXL_20231027_100350285
The brim is cut-off exactly at the edge of the print bed (except for the top edge) and the cut-off positions are exactly what Cura showed me in the preview.
The top gap exists due to the fact that on some printers Y is physically limited to ~232mm. Hence, `machine_depth = 230`.

To me, the issues you're experiencing sound more like firmware configuration issues.

**Comment by BremerButjer** [comment]
would like to try the changes. I don't know much about Github. What do I need to do to build the package?

**Comment by Wilaz** [comment]
> would like to try the changes. I don't know much about Github. What do I need to do to build the package?

See [Here](https://github.com/Ultimaker/Cura/wiki/Getting-Started)

**Comment by BremerButjer** [comment]
> > would like to try the changes. I don't know much about Github. What do I need to do to build the package?
> 
> See [Here](https://github.com/Ultimaker/Cura/wiki/Getting-Started)

Thank you... puh, it reads time consuming.

**Comment by Wilaz** [comment]
> > > would like to try the changes. I don't know much about Github. What do I need to do to build the package?
> > 
> > 
> > See [Here](https://github.com/Ultimaker/Cura/wiki/Getting-Started)
> 
> Thank you... puh, it reads time consuming.

I just downloaded [this](https://github.com/fuji97/Cura/tree/definitions/neptune4pro) and copied the resources folder into my existing cura installation at share\cura\resources

**Comment by mastercaution** [comment]
@Wilaz If you don't want to build Cura to try the profiles, you can also download the zip from [here](https://github.com/mastercaution/Cura/releases/tag/v0.6) and follow the included README. It is basically copying some files into the configuration folder of Cura.

You need at least Cura 5.4.0 (Cura 5.5.0 might also work, but I didn't test it yet)

**Comment by BremerButjer** [comment]
> @BremerButjer If you don't want to build Cura to try the profiles, you can do what @Wilaz did or download the zip from [here](https://github.com/mastercaution/Cura/releases/tag/v0.6) and follow the included README. It is basically copying the new printer files into the configuration folder of Cura.
> 
> You need at least Cura 5.4.0

Thank you @Wilaz @mastercaution ! Will try this

**Comment by Rottenbeer** [comment]
The printhead settings in this profile (
image
) differ from the settings in elegoos cura 4.8 (
image
)
Is this intended? Does it matter?

**Comment by BremerButjer** [comment]
> The printhead settings in this profile image differ from the settings in elegoos cura 4.8 image
> 
> Is this intended? Does it matter?

exactly what i mean! Thank you for the screenshots.

**Comment by mastercaution** [comment]
> > Quick comparison showed, that the Printhead settings differ quite a bit. According to the Elegoo PDF they should be x min=-20, y min=-10, x max = 10, y max = 10, gantry height=270. However, they are -40, -30, 40, 50, 250.
> 
> @flixhsw Thanks for testing! I set the print head polygon to values I measured myself (from nozzle 40mm to the sides, 50mm to the front and 40mm to the back including the sensor). More documentation on the setting [here](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/machine_settings/machine_head_with_fans_polygon.md).

@BremerButjer @Rottenbeer I already answered this question not too long ago ... just scroll up a few comments. Elegoo didn't customize this setting. Their definitions just inherit the base polygon from `fdmprinter`.

**Comment by Rottenbeer** [comment]
What's still needed to merge this?

**Comment by mastercaution** [comment]
Parallel heating would be nice indeed. If I understand it correctly, Cura will detect if the settings `material_bed_temperature` and `material_initial_print_temperature` are used in the start gcode and will not prefix it with the slower heating procedure. I'll add it, thanks for the suggestion @Rottenbeer ^^

**Comment by fuji97** [comment]
@Rottenbeer Yes, they are fixed. I don't know how to mark them fixed, I think that only a maintainer can dismiss the warning

**Comment by fuji97** [comment]
Also, @mastercaution since your release is not updated with the latest changes that you've made (I saw that the v0.6 release is 4 commits behind), I made a release with all the latest definitions so people can try them while waiting to be merged.
I think I copied everything, if something is missing please tell me and I will fix them.

You can find the release [here](https://github.com/fuji97/Cura/releases/tag/v1.0)

**Comment by ToasterUwU** [comment]
@saumyaj3 Just wanted to make you aware that the failing check has been fixed a long while ago but refuses to update.

In case you are waiting for the checks to pass.

**Comment by Rottenbeer** [comment]
> Parallel heating would be nice indeed. If I understand it correctly, Cura will detect if the settings `material_bed_temperature` and `material_initial_print_temperature` are used in the start gcode and will not prefix it with the slower heating procedure. I'll add it, thanks for the suggestion @Rottenbeer ^^
> 
> Also, I'll try to build Cura myself to find out if there are any clang-tidy related issues left. Here on GitHub, it seems that all issues pointed out by the bot are resolved and printer-linter does not complain as well.

What exactly did you add? Can you post your starting gcode maybe? Does it work as expected?

**Review by saumyaj3 — APPROVED** [review]

**Comment by saumyaj3** [comment]
Hey @fuji97 and @Ev1dentFir3 ! Thanks for your contribution. 
I'll be closing the PR: https://github.com/Ultimaker/Cura/pull/16608 as this already takes care of it.

**Comment by mastercaution** [comment]
@Rottenbeer See #17180 for parallel heating :wink:

**Comment by ArthurREGNARD** [comment]
Not in 5.6.0 ?
https://github.com/Ultimaker/Cura/releases/tag/5.6.0-beta.2

**Comment by mastercaution** [comment]
@driahva Do you have a N4 Plus/Max to test new profiles on?

**Comment by driahva** [comment]
> @driahva Do you have a N4 Plus/Max to test new profiles on?

I have an N4 Plus.  I may not be an authority on the results, but would be happy to test.  I have not owned this long, and my need for Cura 5 features has made me want to move away from their 4.8 custom build.

**Comment by si0ls** [comment]
Hi guys, thank for this awesome work!
I see that Neptune 4 (Pro) is not included in 5.6.0, do you know why?
I'm new to Cura, how can I help to setup Neptune 4 Plus (the printer I have) profiles?

**Comment by mastercaution** [comment]
I don't know why they are still not included in v5.6.0. However, I just updated the profiles and added definitions for the Plus and Max variant (see #17576) and I need testers especially for the Plus and Max.

@driahva @ArthurREGNARD @si0ls It would be awesome if you could test the new profiles with your printers :)

**Comment by ArthurREGNARD** [comment]
Hey @mastercaution,
Can you give us the procedure to have the best test. 

1. Remove all file in folders :
  - definitions
  - extruders
  - variants

2. Put configs files : how to find them and download them ?

3. Do we have to print a benchi ? How can we say that the test is succeded ?

**Comment by mastercaution** [comment]
1. There is no need to remove the previous profiles. The new ones overwrite the old ones.
2. Read the new PR. New profiles can be found at my [release page](https://github.com/mastercaution/Cura/releases/tag/v2.0).
3. Just print some models you wanted to print anyway and check that the start G-code works correctly and the print quality is not subjectively worse than before. The new PR lists the changes compared to the profiles merged here.

**Comment by BremerButjer** [comment]
> 1. There is no need to remove the previous profiles. The new ones overwrite the old ones.
> 2. Read the new PR. New profiles can be found at my [release page](https://github.com/mastercaution/Cura/releases/tag/v2.0).
> 3. Just print some models you wanted to print anyway and check that the start G-code works correctly and the print quality is not subjectively worse than before. The new PR lists the changes compared to the profiles merged here.

Tested the new profiles on my NP4Pro. Works well. Thank you

**Comment by ArthurREGNARD** [comment]
Hey, tested on my N4Pro.

I updated my printer with the latest firmware.
  - UI 1.2.11
  - Firmware 1.1.2.41

Auto-leveled before testing and added glue (looks like overflow filament ?!).

Got issues on the finishing touches :
IMG_2519
IMG_2520
IMG_2525

**Comment by mastercaution** [comment]
Hmm, there were no changes made to flow related things, only to acceleration. Maybe your z-offset is a little too low? :sweat_smile:

**Comment by MDeeApp** [comment]
I've got similar problems with the surface after updating my firmware.

**Comment by ArthurREGNARD** [comment]
Yes, it seems to be a z-offset issue, but on the last layer, this problem should normally fade away, but it persists.

As for the stringing, could it be due to a default retraction parameter that needs adjustment?

In any case, thanks for the gCode initiation; preventing filament from dripping during heating is top-notch!
IMG_2527

**Comment by marc-ferrer** [comment]
I haven't checked the official ELEGOO discord in quite a while, but a few months ago their firmware had an issue related to the z-offset and the recommendation was to not upgrade the firmware to the latest version.

**Comment by ToasterUwU** [comment]
@marc-ferrer I have upgraded my firmware to the current newest one from the official website a few hours ago, and it has been the fix for the offset issues i had and also brought some awesome improvements as well

**Comment by mastercaution** [comment]
> As for the stringing, could it be due to a default retraction parameter that needs adjustment?

Currently (in this PR and in the new updated one), the retraction amount is 0.5mm. Elegoo's profiles have 0.8mm. You can try 0.8, but I don't know how much of a difference this makes.

**Comment by ToasterUwU** [comment]
I personally have less stringing issues with this config compared to elegoo cura with the standard config

**Comment by mastercaution** [comment]
@ToasterUwU You are also invited to try the updated profiles over at #17576 :wink:

**Comment by ToasterUwU** [comment]
@mastercaution I see, i would absolutly love to, but need to print a few christmas gifts before i go to my family in a few days, so no time for experimentation right now.

**Comment by callimburg** [comment]
Hello! So the profiles works great, but what do I have to do to get the 0.2 nozzle to not give me "Not supported" after selecting it? Cause I'd like to use the smaller ozzle but seems like the profile are set only for the 0.4, also the 0.6 and 0.8 don't work

**Pull request merged**
