### PR TITLE
Fix Alfawise U30 to get more realistic print times

### PR DESCRIPTION
**Pull request by NicolasNSSM**
I can see a lot of complains about the print time being really different from what Cura says from the reality so here is a PR for the U30.  
I don't own an Alfawise **U20** printer but as they are almost the same, it may be duplicated to its definition too, (i won't do it)

### CODE REVIEW

**Comment by nallath** [comment]
For our reference; CURA-6402

**Comment by philippnj** [comment]
Hey Nicolas,
I cant get it running. created json file took your code, the printer is shown in custom printers-menu, but when clicking "add printer" cura (4 I am using) is crashing - willing to send a crash report. Any ideas?!  

BR

**Comment by NicolasNSSM** [comment]
Hey @philippnj ,
Did you created and copy the `resources/extruders/alfawise_u30_extruder_0.def.json` file too?

**Comment by philippnj** [comment]
That was it!!!  Thank you so much!

**Pull request merged**
