### PR TITLE
Implement material cost

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR implements the forgotten material cost feature.

In this PR, filament weight per spool and cost per spool are stored per material guid in the preferences (instead of in the material profile). It can be argues that the price (and to a lesser extend the spool size) is not a material property but something that is set eg by the reseller. Furthermore this enables editing these values for readonly materials without affecting the xml profile.

Filament length on the spool as well as cost per meter are calculated on the material view tab.

TODO:
* ~~use cost per meter to calculate print cost on the print stats area~~
* ~~make currency a settable preference~~ fixed

### CODE REVIEW

**Comment by nallath** [comment]
I'd love to add this, but i will need to discuss this first. We're technically in feature freeze right now...

**Comment by fieldOfView** [comment]
Ah damn, I seem to have misnamed the branch; I meant to name it "fix_missing_material_cost" ;-)

**Comment by fieldOfView** [comment]
Since this PR is not going to be merged for 2.4, I might as well mention a couple of deficiencies with the current implementation:
* changing the density or the filament diameter does not immediately update the cost per meter on the Materials page
* changing the cost per meter on the Materials page does not immediately update the print cost in the print specs area on the viewport

**Comment by Ghostkeeper** [comment]
A few things surface in my mind when testing this.

* It's really quite confusing that the cost per meter and the filament length don't update when you update the weight and cost of a spool. The cost of the current print in the main window is less pressing, since it doesn't serve to me as a validation of whether what I just entered is correct-ish.
* I think the tildes `~` at the computed filament length and cost per meter should be removed. At least in the latter case since it already says "(Approx.)" before it. Otherwise the "(Approx.)" should be removed.
* These two fields are editable regardless of the "Edit" button, which is inconsistent with the rest. Why did we have that "Edit" button anyway? If we have the "Edit" button as a sort-of "Apply Changes" mechanism, perhaps you can use that to signal when to update the calculations of filament length and cost per meter.

**Comment by fieldOfView** [comment]
> It's really quite confusing that the cost per meter and the filament length don't update when you update the weight and cost of a spool. 

Yes, as noted above. This needs to be fixed.

> These two fields are editable regardless of the "Edit" button.

This is by design; the user must be able to enter the amount of money spent on the spool; we cannot fill that in for them because the price may be different per reseller.

**Comment by fieldOfView** [comment]
I have fixed the updating of the filament length and cost per meter in the materials view, as well as the in the job specs area. 

Ready for review again.

**Comment by Ghostkeeper** [comment]
Will test tomorrow.

**Comment by Ghostkeeper** [comment]
I sort of found a bug, I think... Sorta. Not sure.

I had a copied material which I had completely modified: BLA (bollylactic acid), copied from PLA. It had a changed material type and a changed name. When I modify the material cost of BLA, it will also modify the cost of PLA accordingly. This is because these preferences-per-material are stored per GUID. That's logical, because the GUID is intended to point to a specific type of filament made by a specific manufacturer, and therefore this manufacturer has a specific cost for his material and all profiles for that material should have the same cost.

However if a user wants to create a wholly new type of material in Cura, such as BLA, then it's a bit annoying. This will be fixed by letting the user modify the GUID, so I don't think we have to tackle it now. That's why I'm still merging it. For the rest it works great. Thanks for the contribution!

**Comment by fieldOfView** [comment]
This is a logical consequence of https://github.com/Ultimaker/Cura/issues/1328, and a lack of a way to create a new material (as opposed to duplicating an existing material) and/or creating a new GUID for a material. For me this is a separate issue.

**Pull request merged**
