### PR TITLE
Fractal 3d infill (CURA-4095)

### PR DESCRIPTION
**Pull request by BagelOrb**
Cross infill for super flex

### CODE REVIEW

**Comment by BagelOrb** [comment]
Backend PR: https://github.com/Ultimaker/CuraEngine/pull/569

**Comment by nallath** [comment]
Can this branch be deleted?

**Comment by BagelOrb** [comment]
Uhhmm I think so, but let's keep it open for another week just to be sure ;)

**Comment by Ghostkeeper** [comment]
A week has passed now. I'll just keep a local copy. I have hundreds of local branches anyway.

**Pull request closed without merging**
