### PR TITLE
Hide adhesion & support options if they are disabled

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR hides the adhesion & support options from the ~~~Simple~~~ Recommended mode when they are disabled by the machine definition. One example of a machine that disables the support options is the Peopoly Moai. This hides the support options from the ~~~Advanced~~~ Custom mode sidebar, but they are still there on the Recommended mode tab. This PR removes the settings from the Recommended mode tab if they are removed from the Custom mode tab.

### CODE REVIEW

**Comment by nallath** [comment]
CURA-4255

**Comment by alekseisasin** [comment]
Please check your solution:
1) The margin between rows is changed. In your solution there is no more margin between “Generate Support” and “Build Plate Adhesion”.

2) Also I see it was before. By clicking on the “Build Plate Adhesion” checkbox, the check mark does not appear.

**Comment by fieldOfView** [comment]
I updated the fix to master, redoing the fix. This time around I did not try to clean up the code so it should look the same as before my changes.

**Comment by fieldOfView** [comment]
I also fixed the adhesion checkbox "for free", because @alekseisasin mentioned it above.

**Comment by LipuFei** [comment]
Hi @fieldOfView, sorry to tell you that the simple mode UI has been changed again... This PR needs to be updated after the change, again...

**Comment by fieldOfView** [comment]
Github says there are no conflicts between my branch and master

**Comment by fieldOfView** [comment]
Is there anything I can do to move this forward, or are we just waiting until there are conflicts again?

**Comment by fieldOfView** [comment]
I have updated my PR to master (after the merge of #2393). There were no merge errors.

**Comment by LipuFei** [comment]
@fieldOfView We are tired of the waiting too. This PR will be checked.

**Comment by fieldOfView** [comment]
Thanks. Sorry if sometimes some frustration and lack of sleep shine through.

**Comment by LipuFei** [comment]
No worries. I suffer the same. :)

**Pull request merged**
