### PR TITLE
Fix install directories for Python files on non-Debian Linux

### PR DESCRIPTION
**Pull request by ad1217**
uses similar code as in libArcus to pick the correct Python directory

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Hmm, we have a developer on Arch, who hasn't encountered this problem as far as I know.

**Comment by awhiemstra** [comment]
Probably because I disabled compilation of Cura translations on my machine.

**Comment by ad1217** [comment]
This isn't relating to translations, but to packaging. I maintain `cura-git` in the AUR (as well as the related `-git` packages), and have been patching `Cmakelists.txt` to use the correct directories when installing. This would remove the need for manual patching.

**Comment by thopiekar** [comment]
This PR is not needed at all. All we need to change is to install to /usr/lib/python{MAJOR}.{MINOR} because there are already tools inside debhelper (packaging tools) which handle this situation!

**Comment by thopiekar** [comment]
@ad1217 So if this is the layout Arch uses, you can (in my point of view) feel free to kill the case for Debian.

**Comment by ad1217** [comment]
Ah, that works too. Should it also be changed in libArcus as well then?

**Comment by thopiekar** [comment]
Yes, please. As we are updating now our build system, I'm sure we can take a look whether we can't get rid of this here, too.
@awhiemstra Isn't it? :wink:

**Comment by nickthetait** [comment]
Any developments on this? Is it still relevant or needed?

**Comment by Ghostkeeper** [comment]
Ah, yes there have been developments: https://github.com/Ultimaker/Cura/commit/6484df3e60d194e0d31f7704865b552e50423591

I think this is no longer needed, but could someone test on a non-Debian Linux installation?

**Comment by ad1217** [comment]
Yeah, this got fixed a while ago, sorry I forgot to close this PR.

**Pull request closed without merging**
