### PR TITLE
Render an indication of the origin of the machine

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds a small indication at the machine origin. This is especially important for those machines that don't have a machine mesh that shows which end of the buildplate is the front.

The PR renders three thin cubes, similar to how toolhandles draw thick lines. This way the origin axes draw with a bit of body, over the blue-ish buildvolume wireframe cube.

### CODE REVIEW

**Comment by thopiekar** [comment]
It sounds interesting 😃 
Do you have a screenshot around?

Regards 😉

**Comment by fieldOfView** [comment]
No, but I can make one:
origin

**Comment by thopiekar** [comment]
Very kind, thanks. Looks cool.

I can imagine that there could be the argument that this could confuse beginners or whatever.. In that case it should be very easy to add an option to dis-/enable it 😉

**Comment by fieldOfView** [comment]
I don't understand, what could be confusing about it?

Note that the screenshot is fairly zoomed in on a fairly small custom machine. For most normal printers the effect is more subtle.

**Comment by thopiekar** [comment]
Don't ask me. There are also many things, which don't disturb me, but others.
In my point of view there is nothing wrong with it.

Just had this idea in mind, no criticism, only brainstorming..

**Comment by Ghostkeeper** [comment]
@nallath was just adding this feature, recently. Don't know what became of his implementation though.

What happens when `machine_center_is_zero` is activated?

**Comment by fieldOfView** [comment]
When machine_center_is_zero is activated, the origin-indication moves to the center of the buildplate. In this case it still functions as an indication of the orientation as well, because the axes point towards positive x,y & z (with the same colors that are used for the x,y,z axes that are used elsewhere, i.e. in the tools)

**Comment by Ghostkeeper** [comment]
The indicator should still be part of the build. Last I checked...

**Comment by Cyberman-tM** [comment]
Interesting. To clarify: I'm using the public build, 2.3.1 - I assumed that this would be already in there?
I've now downloaded 2.4 beta, but so far was unable to start it. It just disappears...
I should check the system logs, maybe something else is interfering.

**Comment by Ghostkeeper** [comment]
Possibly it had something to do with the settings folder. If it's getting an error during the process of upgrading your files from the format of 2.3 to the format of 2.4, Cura just tends to stop without warning.

**Pull request merged**
