### PR TITLE
Add profile for Creality Ender 3 S1 Pro and Plus

### PR DESCRIPTION
**Pull request by izilzty**
I have tested the profile on an Ender 3 S1 Plus and I think it should be correct.

### CODE REVIEW

**Comment by drbytes** [comment]
Thanks, this helped my configure my S1.

**Comment by 0xorial** [comment]
why not merge this?

**Comment by drbytes** [comment]
> why not merge this?

unit test fails, .. which is a shame since the profile works.

**Comment by izilzty** [comment]
I noticed that setting_version needed to be increased to 20, so I updated it.

**Comment by izilzty** [comment]
The `speed_travel` for S1 Pro and S1 Plus in Creality Slicer is calculated by the expression `120.0 if speed_print < 60 else 250.0 if speed_print > 100 else speed_print * 2.5` and does not use a fixed value, so use the expression to replace it.

**Comment by jellespijker** [comment]
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

**Review by Joeydelarago — APPROVED** [review]

**Comment by Joeydelarago** [comment]
Looks good! 

Thanks for the contribution 👍

**Pull request merged**
