### PR TITLE
updates cartesio

### PR DESCRIPTION
**Pull request by maukcc**
added quality types for arnitel

### CODE REVIEW

**Comment by nallath** [comment]
For our reference; CURA-3713

**Comment by Ghostkeeper** [comment]
You know, you can update more than one file in a commit :wink:

**Comment by maukcc** [comment]
Updated the quality profiles so they will work with 1.75mm filament
I am still pretty much a noob at this github thing :)

**Comment by Ghostkeeper** [comment]
They way I started committing with Git and taught other people is:
* Download Github Desktop, which is a desktop application for Windows and MacOS that implements Git.
* In Github Desktop, clone the repository you'd like to edit (in your case, the Cura version on Maukcc's profile). It'll ask you where to save the files.
* Edit the files using your favourite text editor.
* In Github Desktop, commit your changes. This allows you to type a message to indicate what has changed.
* If necessary, make more changes and commit them again. Splitting big changes up into multiple commits makes it easier to read, sometimes.
* When you're ready to publish, click on Sync. It'll put the commits up on Github for everyone to see.

**Comment by Ghostkeeper** [comment]
Seems to work now. We had a problem with the Cura profile framework for a while that prevented us from properly testing this as well, but those bugs are now dissipating.

We're getting some warnings that it tries to add the _2 and _3 extruders when you add a Cartesio printer. They can safely be ignored for now. That ties in with how Custom FDM Printer works with a variable amount of extruders.

**Comment by maukcc** [comment]
I am clicking my ass of with the online git, I am looking into a gui git client for linux right now :)
Thanks !

**Comment by Ghostkeeper** [comment]
Yeah there is no Github Desktop for Linux, which is a shame because that program makes most Git tasks very easy to use (especially line-by-line committing). I think they assume that Linux users know their way around the command line anyway.

**Pull request merged**
