### PR TITLE
 Creat new machine named Renkforce 10+

### PR DESCRIPTION
**Pull request by goofoo3d**
# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Printer definition file(s)
- [ ] Translations

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by goofoo3d** [comment]
What should I do next so we can be merged with Cura project?

**Comment by goofoo3d** [comment]
Hello

**Comment by MariMakes** [comment]
Hi 👋 

Sorry, it took us a while to get back to you 😞 
We are a bit behind on these pull requests, I'll ask the developers to take a look as soon as there is time. 

In the future, if you are stuck feel free to tag me 😉

**Comment by goofoo3d** [comment]
Thank you!

**Comment by MariMakes** [comment]
The PR looks good 😄, we are going to try to include it in the Cura 5.5 release 💪

**Comment by MariMakes** [comment]
Hey @goofoo3d,

Did you look at our change request, we cannot ship your suggested change. 

You can either:
1. remove the extra variants, or
2. Include tuned quality profiles for these nozzle sizes for Goofoo_base. You can take a look at how it is done for Creality 3D printers here: https://github.com/Ultimaker/Cura/tree/main/resources/quality/creality/base
3. Remove the reference to goofoo_near and add quality files for only this Renkforce 10+

Do you have a preference for one? Because than we can help you implement it.

**Comment by goofoo3d** [comment]
I have reopened a pull request 'Tuned quality profiles #16481'. Please check it! Thks!

**Pull request merged**
