### PR TITLE
SentrySDK: Turn on deep integration on demand

### PR DESCRIPTION
**Pull request by thopiekar**
Only whenever the sentry_sdk module is there functions of this module will be used.
The only changes, which were needed to be made, are done on cura_app.py and cura.CrashHandler.
Whenever the module is not available, it's functions will be omitted.

The if-clauses could happen earlier, but this at least the bare minimum, and, to be honest, on Ultimaker's distribution it won't speed up anything.
I expect the if-clause to take the same amount of runtime sooner or later. The check is the same and it should be on Ultimaker's distribution always be "True".

Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com> (github: thopiekar)

### CODE REVIEW

**Comment by nallath** [comment]
But why not use the sentry SDK? It's a rather big source of bug information for us (since a lot of people seem to be completely uninterested in writing bug reports, which is understandable but rather frustrating)

**Comment by thopiekar** [comment]
Well, first aspect would be privacy. The PR here is quick and dirty, but prevents sending data not only to Ultimaker (what I don't care much about), but sending it to a third-party.
Theoretically the data might be encrypted, but practically they could monitor the data as man-in-the-middle.
Secondly, don't need to maintain another new package in the PPA.

Technically seen.. Is the init in cura_app really needed at this point? Maybe we could move all the code to the crash handler first and then add an commandline option. :thinking:

**Comment by fieldOfView** [comment]
> But why not use the sentry SDK?

Do you really want all my crashes when I am developing my plugins?

**Comment by thopiekar** [comment]
Also in my case, I also doubt you want to see all the crashes and logs from PPA users, since you as Ultimaker want to focus on your distributed software.

**Comment by nallath** [comment]
I don't mind the crash data from the plugins, sentry is very easy to filter (hell, we already got some crash reports from the PPA that we could fix :)). 

We filter out any identifying data, so neither us or the people from sentry cant track any privacy-sensitive data.

**Comment by fieldOfView** [comment]
> We filter out any identifying data

They don't get an IP address?

Anyway, this Sentry integration is not critical to running Cura, so I think it should be optional when running from source. Even loading libCharon and libSavitar is surrounded by similar try/except statements.

**Comment by nallath** [comment]
> > We filter out any identifying data
> 
> They don't get an IP address?

Nope! The old system didn't store those either and I want to keep it like that. I'm a big proponent of strong privacy protection. 

> Anyway, this Sentry integration is not critical to running Cura, so I think it should be optional when running from source. Even loading libCharon and libSavitar is surrounded by similar try/except statements.

Yeah, fair enough.

**Comment by fieldOfView** [comment]
Off-topic: I fail to see how they don't get an IP address of the sender of the report. But if you say so...

**Comment by nallath** [comment]
Well, yeah they get one. But they aren't legally allowed to store it (in exactly the same as as that *every* website has your IP and can only use it to send a response back).

**Comment by thopiekar** [comment]
Thank you for merging the code!

@nallath Is there any intentions to share the error lines of plugins with the maintainers? I guess it won't happen soon, right?

**Comment by nallath** [comment]
Right now we still do this manually. It is something that we want to do at some point in time.

**Pull request merged**
