### PR TITLE
Add SOVOL printer

### PR DESCRIPTION
**Pull request by Joyce-lujunxu**
Sorry, this is my first pull request, I am a newcomer
I will pull the request again, but the build and test fails, I think I need help Thanks!

### CODE REVIEW

**Comment by fieldOfView** [comment]
You don't have to create a new pull request over and over. You can keep adding/changing files to your fork and the pull request will automatically update.

* `        "category": "Other",` should be removed from both printer definitions,
* `        "platform": "",` should be removed from both printer definitions,
* `        "wall_thickness": { "default_value": 1 },` should be removed from the SV02 definition,
* in the extruder definitions, the `machine` entry should match the exact file name without the extensions of the printer definitions (eg `"SV01"` instead of `"Sovol-SV01"`)

**Comment by Joyce-lujunxu** [comment]
> 您不必一遍又一遍地创建新的请求请求。您可以继续向派生文件添加/更改，并且拉取请求将自动更新。
> 
> * `        "category": "Other",` 应该从两个打印机定义中删除，
> * `        "platform": "",` 应该从两个打印机定义中删除，
> * `        "wall_thickness": { "default_value": 1 },` 应该从SV02定义中删除，
> * 在挤出机定义中，该`machine`条目应与确切的文件名匹配，而不带有打印机定义的扩展名（例如`"SV01"`而不是`"Sovol-SV01"`）

Sorry, I will modify it, thank you

**Comment by fieldOfView** [comment]
The CI is happy; that makes me happy ;-).

There are a couple of lines where you use tabs instead of spaces to indent. Please use 4 spaces consistently.

**Comment by fieldOfView** [comment]
Er... now the files are not in the folders `resources/definitions` and `resources/extruders` anymore. They really need to be in those folders.

**Comment by Joyce-lujunxu** [comment]
> 呃...现在的文件是不是在文件夹`resources/definitions`和`resources/extruders`了。它们确实需要放在这些文件夹中。

It seems I made another mistake

**Comment by Joyce-lujunxu** [comment]
> 呃...现在的文件是不是在文件夹`resources/definitions`和`resources/extruders`了。它们确实需要放在这些文件夹中。

I have finished modifying the file, but now I cannot put the file in the specified folder, I only know how to solve the problem with the new pull request, is there any other way?

**Comment by fieldOfView** [comment]
> but now I cannot put the file in the specified folder

Why not? You have moved (renamed) the file before. See your commits here: https://github.com/Ultimaker/Cura/pull/7898#commits-pushed-6bf370d

**Comment by Joyce-lujunxu** [comment]
> > 但是现在我无法将文件放在指定的文件夹中
> 
> 为什么不？您之前已移动（重命名）文件。在此处查看您的提交：[＃7898（提交）](https://github.com/Ultimaker/Cura/pull/7898#commits-pushed-6bf370d)

I don’t know what happened, I just edited the file, and the file moved

**Comment by Joyce-lujunxu** [comment]
> > 但是现在我无法将文件放在指定的文件夹中
> 
> 为什么不？您之前已移动（重命名）文件。在此处查看您的提交：[＃7898（提交）](https://github.com/Ultimaker/Cura/pull/7898#commits-pushed-6bf370d)

Because of my operation problems, there are too many errors in the branch I created, I am sorry, I can only create a new branch and extract the request

**Pull request closed without merging**
