### PR TITLE
Small tweaks on printer profile for two printers

### PR DESCRIPTION
**Pull request by thetobby**
Tweaks on Draft layer height and default temp for PLA as I have done some more testing on the profiles I submitted.
Ready for pull

### CODE REVIEW

**Comment by nallath** [comment]
For our reference; CURA-4826

**Comment by thetobby** [comment]
Ready for merge, please accept pull request 👍  Any ETA on when Cura 3.2 is versioned out?

**Comment by nallath** [comment]
Cura 3.2 will be in beta in about a week. But it's already in feature freeze, so new machines will be added for 3.3

**Comment by thetobby** [comment]
@nallath  These are just tweaks for printers I added in 2017. I hope this printer will be included, right?

**Comment by ChrisTerBeke** [comment]
The printers are added, just not these tweaks.

**Comment by thetobby** [comment]
Thank you @ChrisTerBeke  :)

**Pull request merged**
