### PR TITLE
Hephestos for Cura 15.06

### PR DESCRIPTION
**Pull request by CoretechR**
Platform offset is [110,128,81.5]

### CODE REVIEW

**Comment by quillford** [comment]
Is this profile necessary? Once editing machine properties from the GUI is added, the standard i3 profile should be close enough. The platform is the same as well.

**Comment by CoretechR** [comment]
OK, Sorry. Didn't know about the editing menu. From what I have read on the forums I thought this feature would not return.

**Comment by nallath** [comment]
What made you think that the feature would not return?

**Comment by CoretechR** [comment]
e.g. https://ultimaker.com/en/community/view/16409-thoughts-about-the-new-cura?page=8
you said you would rely on the community to upload profiles, so I assumed that would be a permanent solution.
But if the settings are coming back that's awesome.
Do you have an ETA on when this will be implemented?

**Comment by nallath** [comment]
We've always relied on the community to upload profiles. All profiles in the old cura (machine wise) were contributions. 
I don't know when this will be implemented but like i said, its not high on our list.

**Comment by nicanor-romero** [comment]
At the moment in BQ we are adjusting and testing the profiles for our printers to get the best results. We will soon be making a pull request to add the profiles for the BQ Witbox and BQ Prusa i3 Hephestos.

**Comment by nallath** [comment]
Allright. Just make a pull request when they are done.

**Pull request merged**
