### PR TITLE
Add support for Creality CR-6 SE

### PR DESCRIPTION
**Pull request by MathieuMH**
Based on the profile that was shared within the Creality CR-6 SE community I wanted to merge this with the main branch in order to have it available by default in upcomming releases.

### CODE REVIEW

**Comment by fieldOfView** [comment]
I don't think it is a good idea to make changes to `creality_base` under the guise of adding a new machine definition. These changes are applied to all creality printers.

**Comment by Sebazzz** [comment]
> I don't think it is a good idea to make changes to creality_base under the guise of adding a new machine definition. These changes are applied to all creality printers.

My guess is that these definitions were taken from Creality Slicer 4.2 and the Cura base profile has probably updated since then.

**Comment by nallath** [comment]
Even so, we won't accept these changes as they stand now (also because the CI failed on them) 

The added variants are not needed, since the creality-base already has them. As FieldOfView mentioned; changing the base profile when some changes are needed for a different machine is definitely not the way to do it.

**Comment by Sebazzz** [comment]
> Even so, we won't accept these changes as they stand now (also because the CI failed on them)

It was not an argument against or for this change 😄

**Comment by Ghostkeeper** [comment]
Indeed Sebazzz, I recognise some of those changes indeed as things we changed after 4.2 at the request of the community testing various Creality printers. These changes are assumed to apply to all of their printers. We can probably revert all changes to `creality_base` made here and you'd get better results out of the CR-6 SE too.
Needs testing though, of course.

**Comment by Ghostkeeper** [comment]
Aside from that the tests are failing because:
* Setting version is outdated (profiles meant for 4.7 instead of 4.8). Most likely there is no shrinkage compensation factor involved here so just incrementing those to 16 should work.
* The `machine_head_polygon` setting doesn't exist any more. Please remove it.

**Comment by Sebazzz** [comment]
> Needs testing though, of course.

If @MathieuMH did not fix the findings yet by the time I get my CR-6 ([which takes a while because Creality messed up shipping](https://damsteen.nl/blog/2020/08/29/3d-printers-incoming)) I will submit a new profile. I do hope that #8321 is fixed then otherwise I can't test it on Cura 4.7.1, the CR-6 has been affected by that issue.

**Comment by MathieuMH** [comment]
Sorry you had to wait on it.
I removed the `machine_head_polygon ` and update the nozzle cfg files to v16 instead of v15. Checks including CI passed now.

**Comment by konskarm** [comment]
Everything seems fine now. The CR-6 SE printer shows up in the list and it slices without issues. As a result, I am accepting this PR so that the printer is included in Cura 4.8.

**Comment by looxonline** [comment]
> Everything seems fine now. The CR-6 SE printer shows up in the list and it slices without issues. As a result, I am accepting this PR so that the printer is included in Cura 4.8.

@konskarm Is there any chance of you doing the same for my BIQU PR so that it is included in Cura 4.8? I'm currently using it and it works well. https://github.com/Ultimaker/Cura/pull/8276

**Comment by DreadKnight** [comment]
Not sure when the next release is, but would be cool if profile could be shared around as a file, if possible.
I've set up mine manually, but still trying to figure out if there are any major differences, as I'm new to this.

**Comment by MathieuMH** [comment]
@DreadKnight Yes you can. It is simply coping a the file at per PR. 
In this PR select at the top changes files. From the latest commit use the file "resources/definitions/creality_cr6se.def.json" and past it in the correct folder.
Same for the nozzle files. There I suppose you need to revert back the previous version v15 instead of v16.
For example the .4mm nozzle resources/variants/creality_cr6se_0.4.inst.cfg
For 4.8 it is:
`setting_version = 16`
For 4.7 you should use:
setting_version = 15

**Comment by Ghostkeeper** [comment]
> Not sure when the next release is,

No promises of course, but we normally release approximately every 2 months, which would place the stable release towards the end of October and the beta a few weeks before that.

**Comment by DreadKnight** [comment]
Sounds good, thanks for letting me know! Pretty agile development :+1:

**Pull request merged**
