### PR TITLE
Relocate locales to proper locations

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/Ultimaker/Uranium/issues/246
Fixes https://github.com/Ultimaker/Uranium/issues/277

See https://github.com/Ultimaker/Uranium/pull/278
See https://github.com/Ultimaker/cura-binary-data/pull/8

### CODE REVIEW

**Comment by hroncok** [comment]
Was this intentional?

**Comment by Ghostkeeper** [comment]
Uh, no. Sorry! I think I forgot to pull Master for this one before creating my `hroncok-localefix` branch. The other two seem to have worked better. Could you rebase that? I can cherry-pick my fixes anew if necessary. Only the last 6 commits were mine.

**Comment by hroncok** [comment]
Got some conflicts, so I'd be happier if you cherry-pick (I don't have time right now to look at this closely enough).

**Comment by Ghostkeeper** [comment]
There we go :)

**Comment by Ghostkeeper** [comment]
Devs, see CURA-4263.

**Pull request merged**
