### PR TITLE
Create printrbot_simple_metal_platform_extend.STL

### PR DESCRIPTION
**Pull request by samirabaza**
heated bed x axis upgrade for PrintrBot Simple Metal 250mmx150mm

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Aww, it wasn't ready?

**Comment by samirabaza** [comment]
Well Ghostkeeper the file is ready but I am still new at Github and I uploaded it to my fork
it is ready and tested on my Printerbot already

**Comment by Ghostkeeper** [comment]
I'll re-open these pull requests then. You seem to have accidentally closed them. That normally means they are no longer applicable.

**Comment by samirabaza** [comment]
ghost keeper
I combined all the files in on one pull.
https://github.com/Ultimaker/Cura/pull/1194 
now I think I under stand the pull system better

**Comment by Ghostkeeper** [comment]
Ah, indeed that will work better.

**Pull request closed without merging**
