### PR TITLE
Also check if base.selectedPrinter is null

### PR DESCRIPTION
**Pull request by Appesteijn**
Fix for https://github.com/Ultimaker/Cura/issues/2745

Not sure if 'undefined' is different from 'null' in qml

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
undefined means that a variable hasn't been initialised yet, null means it has and it explicitly has a null (empty) value. However comparing a value with null or undefined in a non-strict way (== rather than ===) both result in false, so these extra checks are not needed. Actually it would be better to use the short-hand `if (!base.selectedPrinter)` so we cover all cases, including a `false` value.

**Comment by fieldOfView** [comment]
+1 for the shorthand version.
Also, first checking if base.selectedPrinter doesn't exists (and returning "" when so) and then checking if it does exist in the next statement is a bit redundant. 

I would be much surprised if this actually fixes the segfault in #2745. It might fix an innocent qml warning, but it does not fix the bigger issue.

**Comment by LipuFei** [comment]
Agree with @fieldOfView that this has little chance fixing that segfault in #2745.

**Comment by LipuFei** [comment]
@fieldOfView Thanks! Fixed in 78456d5b. I guess I need some coffee...

**Pull request merged**
