### PR TITLE
fix of legacy importer

### PR DESCRIPTION
**Pull request by BagelOrb**

### CODE REVIEW

**Comment by fieldOfView** [comment]
Dude, this you're writing Python!

**Comment by BagelOrb** [comment]
Meh. Copy-paste :P

**Comment by BagelOrb** [comment]
In c++ this would have given a compiler error, btw.
In Python I had to find out by running the legacy importer :S

**Comment by Ghostkeeper** [comment]
Is already fixed in a slightly different way: https://github.com/Ultimaker/Cura/blob/master/cura/Settings/CuraContainerRegistry.py#L175

**Comment by BagelOrb** [comment]
My first frontend code didn't get merged 

D':

**Pull request closed without merging**
