### PR TITLE
Include additional machine defaults for Dagoma DiscoEasy / DiscoUltimate

### PR DESCRIPTION
**Pull request by Sophist-UK**
Values taken from [Dagoma Marlin source code](https://github.com/dagoma3d/Marlin-By-Dagoma/blob/Dagoma-Development/LinuxAddons/Dagoma/conf/serie/E200/Base). Same values are in Marlin for DiscoUltimate.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
I created using examples from other CURA machine profiles and values from the Dagoma Marlin repo. However I note that some examples used `default_value` and some `value` which seems odd.

Can someone please enlighten me about whether these are correct and how you can find out which to use?

**Comment by Ghostkeeper** [comment]
`value` overrides `default_value`. So if there is already a `value`, the `default_value` won't have any effect. The `value` can contain a Python expression, while the `default_value` cannot. In practice, always overriding `value` is the safest.

The purpose of `default_value` is so that CuraEngine can be provisioned with a value as well when ran from the command line, which is not an issue when running Cura normally. It's also slightly more efficient at start-up.

There is some documentation about this here: https://github.com/Ultimaker/Cura/blob/master/docs/profiles/setting_properties.md

**Comment by Sophist-UK** [comment]
> Changes look good to me! Hopefully they'll result in more accurate printing time estimates for those printers.

They do - I entered them manually into Cura and I noticed that the time estimate was significantly more accurate.

Given the comment about `value` vs. `default_value` do we need to change any of these to the other type?

**Comment by Ghostkeeper** [comment]
No I think those are fine. We also have automated checks to test if any of the setting overrides aren't working.

**Comment by 0r31** [comment]
Hi @Sophist-UK , goot idea, i will do the very same for Dagoma delta printers.

**Pull request merged**
