### PR TITLE
Add Builder Premium

### PR DESCRIPTION
**Pull request by Builder3D**
Add definitions for the Builder Premium Small, Medium and Large printers.

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Devs: CURA-4436

**Comment by alekseisasin** [comment]
Builder3D, I would like to ask you to make some changes:
-> in quality profiles set "setting_version = 3"
-> in machine definitions align settings, ( example: in builder_premium_large.def.json file line 11 is used tabs, please use spaces, same as line 10.)
-> in "metadata" you defined "has_machine_quality": true. In your pull request is defined PLA quality profiles. Will you use only PLA material?

**Comment by Builder3D** [comment]
I am pretty new to this all so correct me if I'm wrong :)

@alekseisasin when I change "setting_version = 3" in the quality profiles, Cura do not show the profiles anymore?

**Comment by ChrisTerBeke** [comment]
@alekseisasin The Builder Premium is only advertised to work with PLA, so I think the material info is correct.

**Comment by ChrisTerBeke** [comment]
@Builder3D for us it's exactly the other way around for the setting_version parameter. Are you sure you changed "setting_version"  and not "version"?

**Comment by Builder3D** [comment]
@ChrisTerBeke Found it. Was using Cura 2.7 to check the profiles. Now it's working.

**Comment by ChrisTerBeke** [comment]
Great! We'll review the changes tomorrow. There's a behaviour in the software related to overriding the quality profiles (the has_machine_quality field) that we want to discuss internally first. Once we reach a decision on that we can merge this PR or suggest changes.

**Comment by ChrisTerBeke** [comment]
@Builder3D It would be great if you can add 'not supported' profiles for other materials so the user doesn't see an empty drop down list when selecting for example ABS material. Have a look at https://github.com/Ultimaker/Cura/search?utf8=%E2%9C%93&q=Not+supported&type= for examples. This covers not supported materials until we've made a change in Cura itself to automatically show this when a quality profile is not available for a certain material. You can either wait for us to make that change or add these profiles to have the PR merged asap. Let us know if you have any questions!

**Comment by Builder3D** [comment]
Added the 'not supported' profiles and quality profiles for new fdm materials BVOH and Innoflex 60

**Comment by ChrisTerBeke** [comment]
@Builder3D We've added a functionality to not need the "not supported" profile anymore and removed them from this PR as well. Now that it is merged the Builder Premium printers will show up in the next major release (3.1 Beta scheduled for early December).

**Pull request merged**
