### PR TITLE
Change renderType for TextInput elements

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR changes the renderType of TextInput elements to be the same as other text elements (Label and native elements such as comboboxes).

Unlike Label elements, which are defined to use Text.NativeRendering, TextInput uses Qt text rendering by default. This can lead to differences in font rendering between input fields and other texts.

Probably fixes https://ultimaker.com/en/community/51334-cura-fonts-garbled-on-macos-high-sierra?page=1#reply-190665

Edit: it also fixes one more occurrence of a fractional pixel offset affecting the placement of text: the Recommended/Custom switch.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Would be good if this could be cherry-picked to 3.0 still.

**Comment by Appesteijn** [comment]
CURA-4452

Let's see tomorrow if this can be added for 3.0

**Comment by ChrisTerBeke** [comment]
Code changes look good.

**Comment by ChrisTerBeke** [comment]
@fieldOfView we're testing the changes now. If all is good it will be cherry picked into 3.0.

**Comment by ChrisTerBeke** [comment]
Done.

**Pull request merged**
