### PR TITLE
Neptune 4 / 4 Pro: Heat Bed and Extruder in Parallel

### PR DESCRIPTION
**Pull request by mastercaution**
# Description

Elegoo Neptune 4 / 4 Pro: Add a custom heating procedure into start gcode to heat the bed and the extruder in parallel. Bed and extruder are heated up to the temperature for the first layer (`material_bed_temperature_layer_0` and `material_print_temperature_layer_0`).

## Type of change

- [x] Printer definition file(s)

# How Has This Been Tested?

- [x] Neptune 4; Cura 5.5.0: Sliced and started a print without manual pre-heating. Parallel heating works as expected. The bed and extruder were correctly heated up to the temperature of the first layer.

**Test Configuration**:
* Operating System: Windows 10, Arch Linux (6.5.9)

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by ToasterUwU** [comment]
I tested it on my 4 Pro.

Works flawlessly.

**Comment by NovaScotianNorse** [comment]
Is it just the printer definition files that were changed? I have already downloaded and included the Neptune 4 files from the other PR, but I would like to also add the parallel heating. I just need to update those files?

**Comment by Wilaz** [comment]
what is still needed to merge this?

**Comment by ToasterUwU** [comment]
> Is it just the printer definition files that were changed? I have already downloaded and included the Neptune 4 files from the other PR, but I would like to also add the parallel heating. I just need to update those files?
> 
> EDIT: While I know very little about compiling and coding, I see that it's not even all the Neptune 4 files that changed, it's one line of code in the main definition file. I just edited that, made sure spacing stayed proper, and saved.

If you want it to apply to your currently added Printer, you need to also go to the Preferences, and edit the Starting GCode of your Printer. Replace all \n with a line break.
So "exa\nmple" becomes:
exa
mple

**Comment by ToasterUwU** [comment]
> what is still needed to merge this?

Nothing besides the attention of a Maintainer and a press on the merge button.

**Comment by NovaScotianNorse** [comment]
> > Is it just the printer definition files that were changed? I have already downloaded and included the Neptune 4 files from the other PR, but I would like to also add the parallel heating. I just need to update those files?
> > EDIT: While I know very little about compiling and coding, I see that it's not even all the Neptune 4 files that changed, it's one line of code in the main definition file. I just edited that, made sure spacing stayed proper, and saved.
> 
> If you want it to apply to your currently added Printer, you need to also go to the Preferences, and edit the Starting GCode of your Printer. Replace all \n with a line break. So "exa\nmple" becomes: exa mple

It would appear that there are no instances of '\n' in any of the starting GCode.

Correct me if I'm wrong here, but basically, I just edited the .json file for the Neptune 4 definition (since the Pro definition just inherits from that), and copied and pasted the updated section of code over the old section of code and saved the file. When I load Cura now, the starting GCode in the Preferences, under Machine Settings shows the updated code from the .json file. I'm assuming from here if I were to slice and start a print without preheating, that it would heat the nozzle and bed in parallel, then start with the print process.

**Comment by ToasterUwU** [comment]
> > > Is it just the printer definition files that were changed? I have already downloaded and included the Neptune 4 files from the other PR, but I would like to also add the parallel heating. I just need to update those files?
> > > EDIT: While I know very little about compiling and coding, I see that it's not even all the Neptune 4 files that changed, it's one line of code in the main definition file. I just edited that, made sure spacing stayed proper, and saved.
> > 
> > If you want it to apply to your currently added Printer, you need to also go to the Preferences, and edit the Starting GCode of your Printer. Replace all \n with a line break. So "exa\nmple" becomes: exa mple
> 
> It would appear that there are no instances of '\n' in any of the starting GCode.
> 
> Correct me if I'm wrong here, but basically, I just edited the .json file for the Neptune 4 definition (since the Pro definition just inherits from that), and copied and pasted the updated section of code over the old section of code and saved the file. When I load Cura now, the starting GCode in the Preferences, under Machine Settings shows the updated code from the .json file. I'm assuming from here if I were to slice and start a print without manually preheating, that the starting GCode would heat the nozzle and bed in parallel, then start with the print process.

OK then you are all good. I was sure cura doesn't take the json file changing into account, but it apperantly does.
Doesn't matter now, but I was talking about copy pasting the json content into the GUI start code field, and if you do that, you would have to replace the \n copied from the json stuff with actual line breaks in the preferences setting thing.
But if it already applied for you, that's not needed obviously

**Comment by NovaScotianNorse** [comment]
> > > > Is it just the printer definition files that were changed? I have already downloaded and included the Neptune 4 files from the other PR, but I would like to also add the parallel heating. I just need to update those files?
> > > > EDIT: While I know very little about compiling and coding, I see that it's not even all the Neptune 4 files that changed, it's one line of code in the main definition file. I just edited that, made sure spacing stayed proper, and saved.
> > > 
> > > 
> > > If you want it to apply to your currently added Printer, you need to also go to the Preferences, and edit the Starting GCode of your Printer. Replace all \n with a line break. So "exa\nmple" becomes: exa mple
> > 
> > 
> > It would appear that there are no instances of '\n' in any of the starting GCode.
> > Correct me if I'm wrong here, but basically, I just edited the .json file for the Neptune 4 definition (since the Pro definition just inherits from that), and copied and pasted the updated section of code over the old section of code and saved the file. When I load Cura now, the starting GCode in the Preferences, under Machine Settings shows the updated code from the .json file. I'm assuming from here if I were to slice and start a print without manually preheating, that the starting GCode would heat the nozzle and bed in parallel, then start with the print process.
> 
> OK then you are all good. I was sure cura doesn't take the json file changing into account, but it apperantly does. Doesn't matter now, but I was talking about copy pasting the json content into the GUI start code field, and if you do that, you would have to replace the \n copied from the json stuff with actual line breaks in the preferences setting thing. But if it already applied for you, that's not needed obviously

Ah, that does make perfect sense, and now I see why you wanted me to double check. Thank you, because I didn't realize if I had done it that way, it would have possibly cause an issue I wouldn't have noticed. I'm still really new to a lot of this, so trying not to muck things up too badly.

**Comment by ToasterUwU** [comment]
@saumyaj3 sorry for the direct ping, just wanted to let you know this exists. Since you took care of the related PR as well.

Would be sad to see this in a seperate release from the first PR

**Comment by Wilaz** [comment]
@nallath can you merge this PR?

**Comment by mastercaution** [comment]
#17576 Updates the start G-code with a new start procedure, so this is outdated now. It would be nice if some of you could test the new profiles :)

**Pull request closed without merging**
