### PR TITLE
Add Sovol 3D SV04 printer profile

### PR DESCRIPTION
**Pull request by Joyce-lujunxu**
# Description

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Printer definition file(s)
- [x] Translations

# How Has This Been Tested?

- [x] Test A
- [x] Test B

**Test Configuration**:
* Operating System:

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by Joeydelarago** [comment]
Nice PR, I was considering getting an SV04 myself. The mirror mode definition will be useful. 

Please address the comments from the bot and we will review. The comments are about you defining a setting that is already the default. We like to remove these so the profiles are less cluttered.

**Comment by x40-Community** [comment]
So many print profiles for a printer are completely unnecessary. We had already asked in Sovol to participate in Cura Idex Plugin, but apparently nobody is interested, which is a shame.
With the plugin, only one print profile is then necessary.

**Comment by eropple** [comment]
I , with some indirect help from @maxkreja, have recently added Sovol printers to mainline Cura. I think that it'd be better for users if this followed the pattern of the new, non-legacy profile set? As-is this is going to be more confusing and a worse UX for Cura users.

I would suggest inheriting from sovol_titan to get behavioral commonality with similar printers (SV01 Pro, SV05) and make necessary changes from there.

For the new profiles, Sovol was solicited for feedback during the process of developing those profiles and declined to participate. Candidly, it seems like poor open source behavior to throw this over the wall now without working to synergize with what's already there.

**Comment by eropple** [comment]
So, with some indirect help from @maxkreja, I have recently added Sovol printers to mainline Cura. I think that it'd be better for users if this followed the pattern of the new, non-legacy profile set? As-is this is going to be more confusing and a worse UX for Cura users.

For the new profiles, Sovol was solicited for feedback during the process of developing those profiles and declined to participate. Candidly, it seems like poor open source behavior to throw this over the wall now without working to synergize with what's already there.

The additional extruders and modes make a lot of sense, but I would suggest inheriting from sovol_titan to get behavioral commonality with similar printers (SV01 Pro, SV05) and make necessary changes from there.

(flag @Joeydelarago to make sure we've got general context across the board)

**Comment by Joeydelarago** [comment]
@Joyce-lujunxu as mentioned above these changes should be based on the existing Sovol definitions. These were standardized in this PR #13716 

A better alternative would be to contribute towards this plugin [http://www.x40-community.org/index.php/cura/cura-plugins/9-cura-workflow/85-cura-idex-plugins](http://www.x40-community.org/index.php/cura/cura-plugins/9-cura-workflow/85-cura-idex-plugins.) . This would result in a far better user experience in my opinion.

**Comment by eropple** [comment]
These changes are based on the `sovol_base` profiles now - they look good here, though I don't have a SV04 to check.

**Comment by jellespijker** [comment]
@Joyce-lujunxu I opened a PR against your fork https://github.com/Joyce-lujunxu/Cura/pull/1 , with some suggested changes. please review and test if possible. Once that PR is merged I can do a final review here and we can then merge it in main.

**Comment by jellespijker** [comment]
Closing this PR in favor of #15376 otherwise this PR will stall to much, since merging depends on first merging https://github.com/Joyce-lujunxu/Cura/pull/1 

The new PR #15376 will have the suggested changes. @Joyce-lujunxu thank you for your contribution. Your profile should be available in Cura 5.4 (please be sure to still check the suggested changes made by me on an actual printer.

**Pull request closed without merging**
