### PR TITLE
kor translation update Cura 5.7

### PR DESCRIPTION
**Pull request by crwusiz**

### CODE REVIEW

**Comment by wawanbreton** [comment]
Hi @crwusiz, thanks for the new PR ! However it is still based on `main` so I can't integrate it, otherwise we will have a lot of conflicts when merging back the current translations in 5.7-translations :grimacing: How do you want to proceed ?

**Comment by crwusiz** [comment]
> Hi @crwusiz, thanks for the new PR ! However it is still based on `main` so I can't integrate it, otherwise we will have a lot of conflicts when merging back the current translations in 5.7-translations :grimacing: How do you want to proceed ?

What should I do then?

**Comment by wawanbreton** [comment]
You should create a branch on your repository, based on the latest [5.7-translations](https://github.com/Ultimaker/Cura/tree/5.7-translations), then make a PR that targets it back. I hope this is not too much work for you.

**Comment by wawanbreton** [comment]
Sorry for that, I had the very same confusion with other contributors. We will try to find a way to make it clearer once we have done the faeture freeze.

**Comment by crwusiz** [comment]
> Sorry for that, I had the very same confusion with other contributors. We will try to find a way to make it clearer once we have done the faeture freeze.

i change 5.7 translation branch

**Pull request closed without merging**
