### PR TITLE
[CURA-7016] Add actual public key instead of dummy.

### PR DESCRIPTION
**Pull request by rburema**
You'll need https://github.com/Ultimaker/Uranium/pull/584 to properly test this.

### CODE REVIEW

**Comment by fieldOfView** [comment]
So the default build type is now "enterprise"?

**Comment by rburema** [comment]
> So the default build type is now "enterprise"?

That shouldn't be the case.

> Uhm, shouldn't we fix this instead by just setting the build type to "enterprise" in our build system?

That was the idea!

I'd like to revert that change (not the public key, the other commit). Any objections?

**Comment by ninovanhooff** [comment]
Wow, this is quite a wild mistake by me. Sorry people, I was under the impression that I only pushed the Uranium change, as indicated by the commit message mismatch.

**Comment by rburema** [comment]
No problem, don't beat yourself up over this, could happen to anyone!

**Pull request merged**
