### PR TITLE
adding tripod buildplate shape and assigning it to dagoma delta printers

### PR DESCRIPTION
**Pull request by DethCount**
allows to print 270mm instead of 200mm

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Maybe just "triangular" would be a better description for the shape of the build plate?

A new build plate shape also needs to be implemented in CuraEngine. This PR alone is not going to provide support for triangular build plates.

**Comment by DethCount** [comment]
ok for triangular.

I spent 2 days trying to build Cura on Mac OS but i couldn't make it work.
I'm getting issues with python sip import while on cura-build-environment
container.

Le jeu. 15 avr. 2021 à 23:30, Ghostkeeper ***@***.***> a
écrit :

**Comment by Ghostkeeper** [comment]
Sip is always a bit of a difficult one to deal with in the build system, for some reason. Myself I've just compiled Sip from source and then it's working fine by pointing CMake to the correct directories.

**Comment by nallath** [comment]
I'm closing this due to inactivity.

**Pull request closed without merging**
