### PR TITLE
CURA-4215 New splash window

### PR DESCRIPTION
**Pull request by LipuFei**

### CODE REVIEW

**Comment by fieldOfView** [comment]
Wew, that's a lot of different fonts on a single splash-screen: 4 in the bitmap alone, and then the font that gets added to show the version and messages. I think it would be better at least the slogan and developed by lines used the same fonts (preferably the same as the text that gets added programmatically).

**Comment by LipuFei** [comment]
@fieldOfView Well... It will be changed... again...

**Comment by fieldOfView** [comment]
That should be the slogan:
"Ultimaker Cura
It will change again"

;-)

**Comment by nallath** [comment]
Seriously considering putting it in there ;)

**Comment by Appesteijn** [comment]
'The only constant is change'.

I have added @fieldOfView his comments to the jira ticket.

**Comment by fieldOfView** [comment]
I hope you mean you added the helpful constructive criticism, and not the snarky wittiness..

**Comment by Appesteijn** [comment]
What snarky wittiness? :smile:

**Comment by fieldOfView** [comment]
I just noticed that the new splash has a hexagon in the background that has a 40 degree slope. The official background hexagon has a 30 degree slope: https://ultimaker.com/img/hexagon.svg

The slope in the current incarnation looks rather jagged, probably due to scaling.

**Pull request merged**
