### PR TITLE
Removed escape key binding from 'exit fullscreen' action

### LINKED ISSUE #7499: Minor but annoying UI issues
**Application version**
4.5.0

**Platform**
Windows

**Printer**
N/A

**Reproduction steps**
1. Maximise Cura window. Press ESC key. Window is un-maximised - this is unexpected and contrary to normal Windows style.

2. Although there are Maximise/Minimise buttons (top right hand corner of Cura window), and although the system menu has enabled maximise and minimise options when you use the mouse to activate it by clicking on the Cura icon at the top left corner of the Cura window, when you use Alt-Space to activate the system menu the maximise and minimise options are not enabled - which means that those of us who use the keyboard to avoid switching to the mouse and back again cannot minimise or maximise by Alt-Space and then n/m.

**Screenshot(s)**
Can be provided if needed.

**Actual results**
1. Esc de-maximises window.
2. Maximise / Minimise not enabled when system menu is shown using Alt-space.

**Expected results**
1. Esc should not de-maximise window.
2. Maximise / Minimise should be enabled when system menu is shown using Alt-space.

### PR DESCRIPTION
**Pull request by snoopen**
# Description

This removes the unexpected behaviour of the window size changing upon pressing the escape key. This fixes #7499.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] With main window maximised, press escape and observe no window size change
- [x] With main window maximised, click into numeric input field, press escape and observe no window size change

**Test Configuration**:
* Operating System: Linux (Ubuntu 22.04)

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by Joeydelarago** [comment]
Hey, thanks for the contribution. I agree this doesn't make much sense when we already have a key to toggle the fullscreen. 

Could you please search the project for other uses of _"exitFullScreen"/"exitFullScreenAction" _ and remove them and the surrounding code. I see a Connection in Cura.qml and an alias in Action.qml.

Thanks!

**Comment by snoopen** [comment]
@Joeydelarago sure thing, can do

**Comment by snoopen** [comment]
@Joeydelarago That's updated now, let me know if I need to action anything further to assist with this PR.

**Comment by onolox** [comment]
Cura 5.3 still has this behaviour, Esc  == exit fullscreen!

**Comment by fieldOfView** [comment]
> Cura 5.3 still has this behaviour

Correct. This PR is not merged into Cura yet.

**Review by Joeydelarago — APPROVED** [review]
Looks good, you removed the references I noticed when I reviewed this last time. I'm not working at Cura any longer though so someone else will have to merge.

**Comment by snoopen** [comment]
Let me know if there's anything I can do to get this moving along

**Comment by fieldOfView** [comment]
Why does this PR remove the `exitFullScreenAction` action entirely, instead of just removing the `hotkey` property? The `exitFullScreenAction` is still referenced in Cura.qml, via the `Cura.Actions.exitFullScreen` alias.

**Comment by onolox** [comment]
I think it's a shame that a simple bug like this is taking so long to be merged.

**Comment by snoopen** [comment]
> Why does this PR remove the `exitFullScreenAction` action entirely, instead of just removing the `hotkey` property? The `exitFullScreenAction` is still referenced in Cura.qml, via the `Cura.Actions.exitFullScreen` alias.

@fieldOfView This PR removes that entire action and its alias in Cura.qml as well. I can't see where else it could be bound. So with the hotkey removed there's nothing that would call that action. I suspect that's why @Joeydelarago had asked for it's removal in addition to just the hotkey.

Let me know if I'm missing something or if you think it needs to change regardless.

Actually... my original PR was just removal of the hotkey.

**Comment by fieldOfView** [comment]
Since @Joeydelarago no longer works for Ultimaker (and cannot merge this), perhaps it is best to get some more eyes on this. @MariMakes, who is the best person to ask for a new review?

Just as a TL;DR, this PR removes the hotkey AND the now vestigial action. #18081 just removes the hotkey. Merging either of these PR solves the original issue #7499

**Comment by nallath** [comment]
Closing this in favor of https://github.com/Ultimaker/Cura/pull/18081

**Pull request closed without merging**
