### PR TITLE
definitions: fix deprecated usage of travel_speed in rigidbot

### PR DESCRIPTION
**Pull request by ubitux**
Note: untested

### CODE REVIEW

**Comment by nallath** [comment]
We can't test this, so can anyone with a rigibot validate these changes?

**Comment by fieldOfView** [comment]
Wa can't test it, but we can see that the gcode created previously has a token that is not being replaced.

**Comment by ubitux** [comment]
fb92e50262c481d990c88904265aaf4987b31d63 replaced other `travel_speed` occurrences in that file, this one might have simply be forgotten.

**Comment by Ghostkeeper** [comment]
I'll just test this with the g-code rather than actually printing it.

**Comment by Ghostkeeper** [comment]
This is the g-code header it produces now for a 4x4x4cm cube:

    ;FLAVOR:RepRap
    ;TIME:4888
    ;Filament used: 7.66656m
    ;Layer height: 0.2
    ;Generated with Cura_SteamEngine master
    ;Basic settings: Layer height: 0.2 Walls: 0.8 Fill: 20
    ;M190 S60 ;Uncomment to add your own bed temperature line
    ;M109 S200 ;Uncomment to add your own temperature line
    G21 ;metric values
    G90 ;absolute positioning
    M82 ;set extruder to absolute mode
    M107 ;start with the fan off
    G28 X0 Y0 ;move X/Y to min endstops
    G28 Z0 ;move Z to min endstops
    M205 X8 ;X/Y Jerk settings
    G1 Z15.0 F120 ;move the platform down 15mm
    G92 E0 ;zero the extruded length
    G1 F200 E7 ;extrude 3mm of feed stock
    G92 E0 ;zero the extruded length again
    G1 F120
    ;Put printing message on LCD screen
    M117 Rigibot Printing...
    ;LAYER_COUNT:200
    ;LAYER:0
    M107
    G1 F1500 E-6.5
    G0 F3600 X101.623 Y101.349 Z0.3
    ;TYPE:SKIRT
    G1 F1500 E0
    G1 F1800 X102.222 Y100.834 E0.03941
    ...

Looks good. No unreplaced keys in there.

**Pull request merged**
