### PR TITLE
Modify the Ender 6 Profile.

### PR DESCRIPTION
**Pull request by GroovyDrifter**
Remove material temperatures from profile so they can follow those in the material seleced.

### CODE REVIEW

**Comment by GroovyDrifter** [comment]
New to all this GIT stuff, hope I did not mess anything

**Comment by GroovyDrifter** [comment]
I changed even more the code to the Ender 6 profile so it is like any other Creality printer, removing any additional settings. In my tests it prints better with this simpler profile if you have original firmware.

**Comment by nallath** [comment]
I don't think that the changes that you made are quite correct. You also seem to have changed the name of the printer to be creality3 and change the size of the printer.

**Comment by GroovyDrifter** [comment]
You're right, I messed things copyng and pasting for the wrong notepad++ tab, sorry... now i think it is fixed.

**Review by nallath — APPROVED** [review]

**Pull request merged**
