### PR TITLE
Adapt camera image to available space

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR makes sure the camera image adapts to the available size in the window. Cura 2.6 did the same thing, but this was missing since the refactor of the camera image in Cura 2.7.

Steps to reproduce the issue: 
switch to the monitor view and make the window as small as it will go.
Result:
the image will be cut off, and could even overlap the topbar (making it hard to return to the "prepare" tab. 

The issue is even more of a problem for users of the OctoPrint plugin, where the camera image can be much larger than the UM3 image (eg 1920x1080). A separate fix for the OctoPrint plugin is in preparation, but it relies on this PR.

It would be nice if this could be cherry picked for Cura 2.7.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Humble bump

**Comment by alekseisasin** [comment]
Devs, see CURA-4169

**Comment by fieldOfView** [comment]
Is there any chance this could get cherrypicked into 2.7?

**Comment by alekseisasin** [comment]
Yes, it will be added into 2.7

**Pull request merged**
