### PR TITLE
Malyan180 support

### PR DESCRIPTION
**Pull request by Ghostkeeper**
This is a translation of the machine that Malyan made for version 15.06. The settings should be the same as what Malyan provided back then.

See also https://github.com/Ultimaker/Cura/pull/582, which was not a pull request but a request for work. I just did the translation.

### CODE REVIEW

**Comment by BagelOrb** [comment]
The machine settings should be overrides if you want to merge this file to master...

**Comment by nallath** [comment]
My bad. I'll fix that.

**Comment by fieldOfView** [comment]
What's the point of having this profile if the Malyan M180 needs a .x3g file (instead of .gcode), which we don't create.

**Comment by BagelOrb** [comment]
There is a tool which converts .gcode to .x3g. People are free to use that tool however they like. 
https://github.com/whpthomas/GPX

**Pull request merged**
