### PR TITLE
Update Maker Made Maker 300 Printer Profile

### PR DESCRIPTION
**Pull request by skilescm**
Modified printer settings and added G90 to pre-print gcode to eliminate printing errors.

### CODE REVIEW

**Comment by skilescm** [comment]
We tested our printer in the beta and made these changes so everything will work properly in the full release. Please merge :)

**Comment by Ghostkeeper** [comment]
The beta is feature frozen since about a week before the beta, so it'd be merged in the next release then, not 4.9. Sorry! This is something our testers need in order to get a more stable release.

**Comment by nallath** [comment]
If you want to add machine quality profiles, you will also need to add quality profiles per extruder.

**Review by nallath — CHANGES_REQUESTED** [review]
If you want to change this printer so that it has specific profiles, you will need to also add quality profiles for the extruder as well.

**Comment by skilescm** [comment]
Closing due to being a duplicate of another PR.

**Pull request closed without merging**
