### PR TITLE
Add gyroid infill density variants

### PR DESCRIPTION
**Pull request by smartavionics**
Adds low and medium resolution gyroid infill variants.

See https://github.com/Ultimaker/CuraEngine/pull/1135.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Wouldn't it make sense to have one Gyroid option, and a second setting (Gyroid resolution) that is only visible when Gyroid is selected as infill pattern?

**Comment by smartavionics** [comment]
> Wouldn't it make sense to have one Gyroid option, and a second setting (Gyroid resolution) that is only visible when Gyroid is selected as infill pattern?

That would require more more code in the engine and another setting in the UI. I try hard not to add settings as the UI is already dog slow.

Personally, I don't care that there's now extra entries in the pattern menu.

**Comment by Ghostkeeper** [comment]
I agree though. Having an option "Gyroid (medium)" doesn't really tell me what's medium about that Gyroid.

**Comment by smartavionics** [comment]
> I agree though. Having an option "Gyroid (medium)" doesn't really tell me what's medium about that Gyroid.

Agree with what? Having the extra menu entries or having a new gyroid resolution setting? Actually, that would be two new settings one for the infill and one for the support.

It's true, "medium" isn't very descriptive. Adding "resolution" would be informative but would make the menu wider.

**Comment by smartavionics** [comment]
Closing this for now, may open again in the future or replace with another PR.

**Pull request closed without merging**
