### PR TITLE
Printjob icon

### PR DESCRIPTION
**Pull request by saumyaj3**
Printjob icon updated

### CODE REVIEW

**Comment by wawanbreton** [comment]
Shouldn't you remove the FoodBeverages.svg as it is not used anymore ? And/or register it in the deprecated_icons.json ?

**Comment by saumyaj3** [comment]
I was considering to remove it, but decided not to do it, as the icon's size is relatively small, and it may still be of use to the plugins. what do you think?

**Comment by wawanbreton** [comment]
Oh sorry I didn't read your message carefully.. You're right about the plugins. We could consider that they should now use the new icon, but some old plugins may not. Then I don't know what should be done...

**Comment by wawanbreton** [comment]
@saumyaj3 Can you add an entry to resources/themes/cura-light/icons/deprecated_icons.json ?

**Comment by saumyaj3** [comment]
> @saumyaj3 Can you add an entry to resources/themes/cura-light/icons/deprecated_icons.json ?

On it!

**Pull request merged**
