### PR TITLE
Remove incompatible plugins

### PR DESCRIPTION
**Pull request by thopiekar**
All of the plugins where not updated for about half a year. Haven't tested them on my own, but I guess they are all incompatible now.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
I have tested X3G writer more recently and as far as I know it still works.
Turns out that I locally incremented the API version without having committed it. Did that now.

The Barbarian Plug-in still works as far as I know. Haven't tested it since 2.3.0.

Don't know about the print cost calculator.

**Comment by nallath** [comment]
The barbarian plugin isn't that impressive, so it should work without a hitch.

**Comment by thopiekar** [comment]
What about the Print Cost Calculator? It is now more or less integrated into Cura since we have materials support, isn't it?

**Comment by fieldOfView** [comment]
It would be great if Print Cost Calculator could be deprecated, but the materials support still is not complete; I cannot enter spool weight and cost, and print cost is not calculated.

**Pull request closed without merging**
