### PR TITLE
CURA-1511: Adding section to the general settings

### PR DESCRIPTION
**Pull request by thopiekar**
This commit adds a section to the general page to set the log-level for the console output.
It depends of a PR made for Uranium (https://github.com/Ultimaker/Uranium/pull/172).

Contributes to CURA-1511

### CODE REVIEW

**Comment by nickthetait** [comment]
Bumping this PR as it is over a year old now :open_mouth: but never got a response :cry:

**Comment by Ghostkeeper** [comment]
When it has a Jira ticket number attached I tend to assume that it's some ticket in our current sprint and will be handled in our day-to-day workflow, so I won't do anything with it.

This Jira ticket was not in our current sprint and was eventually closed by our project manager for being older than 3 months. I'll duplicate that ticket and put it up so that we can judge whether or not we want this added.

**Comment by LipuFei** [comment]
I think the logging level should be passed through either a parameter (e.g. argv) and/or an environment variable, or something similar. Putting this in preferences is even less convenient because you need to run Cura first in order to set the logging level, then close and start again.

**Comment by ChrisTerBeke** [comment]
We have decided not to implement this. Developer features are best triggered via a command line argument.

**Pull request closed without merging**
