### PR TITLE
Hopefully Adding the Key3D Tyro to 4.3 Release 

### PR DESCRIPTION
**Pull request by DragonJe**
I created definition, extruder, and profiles for the Key3D Tyro. I added it to the newest 4.3 Branch, in the hope that it could be in the latest release of Ultimaker Cura!

If I'm too late and you'd rather have me add it to the Master Branch, let me know.

Thanks for all you do!

### CODE REVIEW

**Comment by fieldOfView** [comment]
Once a Cura version goes into beta no new features are allowed in (only bugs are fixed). A new printer definition is seen as a new feature.

Your quality profiles have a lot of duplication. It is better to include these settings that are the same for each quality profile in the printer profile instead of in the quality profile.

**Comment by diegopradogesto** [comment]
Yes, sorry, no new printers are allowed to go into a release branch. I will change the target branch to avoid possible errors.

**Comment by DragonJe** [comment]
Ok, I understand. I'll add the duplicate settings to the printer profile in a future update. Thank you the help and advice!

**Comment by diegopradogesto** [comment]
Devs. CURA-6815

**Pull request merged**
