### PR TITLE
CURA-7162/Replace the default logobot.svg with a new placeholder

### PR DESCRIPTION
**Pull request by DonExo**
Replace the old logobot.svg with a new placeholder.

### CODE REVIEW

**Comment by nallath** [comment]
RIP

**Comment by fieldOfView** [comment]
goodbye

I know of at least 1 place where Ultibot still rules. I'm not telling where, because then he'll get hit with the anti-toy-hammer.

**Comment by nallath** [comment]
> I know of at least 1 place where Ultibot still rules. I'm not telling where, because then he'll get hit with the anti-toy-hammer.

It still lives within my heart :'(

**Comment by ChrisTerBeke** [comment]
It's not as if developers have left UltiBot easter eggs throughout the ecosystem....

**Comment by ChrisTerBeke** [comment]
The new image doesn't seem to render very sharp when enlarged:
image

**Comment by DonExo** [comment]
> The new image doesn't seem to render very sharp when enlarged:
> image

I've added some property to the Image object in QML. It should be better now.

**Comment by diegopradogesto** [comment]
> It's not as if developers have left UltiBot easter eggs throughout the ecosystem....

Including some snowflakes for next XMas XDDDD

**Comment by DonExo** [comment]
@konskarm you might also want to remove the old logobot.svg file from the system.

**Pull request merged**
