### PR TITLE
Tuned quality profiles

### PR DESCRIPTION
**Pull request by goofoo3d**
# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Printer definition file(s)
- [ ] Translations

# Checklist:

- [ ] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [ ] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by goofoo3d** [comment]
Your understanding is absolutely correct! Thank you for validating my work - I really appreciate it. If there are no other issues, I hope my pull request can be merged into Cura 5.5! Thank you very much!

**Comment by MariMakes** [comment]
Hey @goofoo3d,

I had one of the developers take a look and they spotted a potential problem. 
A number of the already existing filenames have been renamed. This could cause some trouble for users who upgrade but have 
the configuration still selected.

For example
`/goofoo_far_0.40_abs_standard.inst.cfg → /goofoo_far_0.4_abs_standard.inst.cfg`

Do you have a strong reason why you would like to rename the files? Because our developers have to write an upgrade script for people to start using these new settings and that might take some time.  If it's not too important and too much work you can remove the renames, and then I could probably merge the change and we could include it in the 5.5 release. 

How would you like to proceed?

**Comment by goofoo3d** [comment]
There is no particular reason, I just thought having a consistent naming format seemed more formal! If it causes any potential issues due to the renaming, then I'll remove it, since the renaming itself is unimportant!

**Comment by goofoo3d** [comment]
Can you help me remove the pull request about the renaming?

**Comment by goofoo3d** [comment]
Hello,
When will my pull request be merged? If there is anything I need to do, please let me know! Thanks!

**Comment by MariMakes** [comment]
Hey @goofoo3d,

It took a couple of tries, but I've been able to rename the files that we expected would cause issues with an upgrade script. 
I tested a number of material, printer, core combinations and it's looking good 😄 

I'll merge these changes so we can ship them with the upcoming Cura 5.5 release.

**Pull request merged**
