### PR TITLE
Support gyroid support.

### PR DESCRIPTION
**Pull request by smartavionics**
Haven't actually tried printing gyroid support but at least now it can be evaluated.

As discussed in https://github.com/Ultimaker/CuraEngine/issues/991.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Yeah I thought I might do this in between somewhere, but you were ahead of me! Thanks.

It slices all right. I'm making a test print because I'm curious but that's a print quality / tuning issue if the test print goes wrong.

**Comment by smartavionics** [comment]
It should be OK, I think it needs to have the lines connected because otherwise you tend to get very ragged ends to the waves.

**Comment by Ghostkeeper** [comment]
It's a bit like grid or triangle infill. Kind of hard to remove, kind of rigid. But similar properties. For a fairly thin strip of support it works kind of nicely to squeeze the support and remove it that way (similar to zigzag).

**Comment by smartavionics** [comment]
Because it is so strong and stable maybe one can get away with reducing the density compared to the other support infills?

**Comment by Ghostkeeper** [comment]
Or maybe even the connected lines.

**Pull request merged**
