### PR TITLE
make lithophane alpha channel control total final width multiplier.

### PR DESCRIPTION
**Pull request by BagelOrb**
That way the picture is not always square. We can use the alpha channel to encode the actual shape

### CODE REVIEW

**Comment by BagelOrb** [comment]
Requested here: https://www.reddit.com/r/3Dprinting/comments/dmdbvn/lithophane_png/

**Comment by BagelOrb** [comment]
This test image has an alpha channel:
convex_hulk_txt

**Comment by BagelOrb** [comment]
It actually works!
(Who would have thought!) :P
image

**Comment by BagelOrb** [comment]
Note that the zero alpha pixels still show up as a zero-width surface.

I know it's not ideal, but let's not put too much effort into this, okay?
The solution to that would be super complicated!

**Comment by fieldOfView** [comment]
Cool! How does it look in X-Ray View?

**Comment by BagelOrb** [comment]
I'm probably thinking about it too easily again, but do we really need to code check this and QA this?
Lithophanes are super uncritical.

**Comment by fieldOfView** [comment]
One could argue that the ImageReader should be a Marketplace plugin. I think it would even be *more* discoverable that way. That way only @diegopradogesto has to test it ;-)

**Comment by BagelOrb** [comment]
Not a bad idea. Maybe I will do that in the future

**Comment by Ghostkeeper** [comment]
> One could argue that the ImageReader should be a Marketplace plugin. I think it would even be more discoverable that way. That way only @diegopradogesto has to test it ;-)

Since Diego left our team, the development team has been spreading the work, actually.

**Comment by fieldOfView** [comment]
Ah, that explains why my plugin has been "submitted" without review for >2 weeks now. Bye Diego 👋

**Comment by Ghostkeeper** [comment]
Yeah we've only recently been spreading the work because Diego's successor had not been doing it for a while. Should be better now though!

**Comment by ninovanhooff** [comment]
Cool feature, also love the simplicity of the implementation.
Might be nice for height maps as well, or maybe sprites where you can just create a lot of board game / terrain tiles 
Devs: https://jira.ultimaker.com/browse/CURA-7056

**Comment by ninovanhooff** [comment]
Force pushed a rebase since @BagelOrb previously indicated he prefers that.

**Comment by BagelOrb** [comment]
I do prefer rebasing over merging, but I don't require you to also force push it. My opinion was about keeping a clean history in the master branch without those ugly merge commits. Merge commits sometimes hide the introduction of bugs which are then very difficult to got bisect.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
