### PR TITLE
Tronxy Profiles 2022 Update

### PR DESCRIPTION
**Pull request by 64bittuning**
The Tronxy community has requested the removal of "max feedrate" settings in the slicer profile. The machines are usually run on one of three firmwares and these limitations really hinder slicer performance. There have also been multiple requests to add dual extrusion support. That was not something I had considered, nor did I know how to implement in when the original PR was submitted in 2020. There are also new printers that have been added to the product line. Those will be included as well.
The last PR attempt was plagued by a "test" failure in 14/15. This PR will be resubmitted in segments to ensure there are no faults.

### CODE REVIEW

**Comment by nallath** [comment]
For our reference: CURA-8932

**Comment by 64bittuning** [comment]
Please include https://github.com/Ultimaker/fdm_materials/pull/191 with this, as they work together.

**Comment by nallath** [comment]
> Please include [Ultimaker/fdm_materials#191](https://github.com/Ultimaker/fdm_materials/pull/191) with this, as they work together.

Ha, you're just in time :P I was about to merge this.

**Comment by 64bittuning** [comment]
My wife says I'm quick too.... *sad face*

**Pull request merged**
