### PR TITLE
Add FLSUN QQ

### PR DESCRIPTION
**Pull request by radfahrer**
Adds  definition and extruder definition for the FLSUN QQ.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Please use a more descriptive title for your PR.

**Comment by nallath** [comment]
Also, we won't release a new version of 4.0, so if you want this to be in the next release, please change it to merge into master.

**Comment by Ghostkeeper** [comment]
I thought I remembered this name. We already have FLSUN QQ. Please contribute to the existing definition instead.

**Comment by radfahrer** [comment]
This is the existing version. I got it merge into master before the 4.0 release. Couldn't figure out why it wasn't in 4. Thought I might need to add it to this branch. So long as it makes it into the next release I'll be happy.

**Pull request closed without merging**
