### PR TITLE
Added definitions for all Wanhao Duplicator FDM printers

### PR DESCRIPTION
**Pull request by FricoRico**
As the name suggests, this pull request features machine profiles for all Wanhao Duplicator FDM printers, including models and logo for the base plate. Tried to follow naming conventions as much as I could.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Nice. The meshes are way too big though (filesize-wise).

**Comment by FricoRico** [comment]
@fieldOfView I will see if I can optimize them to a smaller filesize 👍

**Comment by FricoRico** [comment]
I reduced the meshes as far as I could with the software that I have, while maintaining UVs for the logo texture. Every file went from `4,5MB` -> `1,5MB` so a total file size of `7,5MB` instead of `22,5MB`

**Comment by Appesteijn** [comment]
CURA-5492, tested ok

**Pull request merged**
