### PR TITLE
Version upgrade 4.5 to 4.6 for Maximum Deviation changes

### PR DESCRIPTION
**Pull request by BagelOrb**
Includes value changes for `meshfix_maximum_deviation`, so that its behavior remains the same.

Required for https://github.com/Ultimaker/CuraEngine/pull/1214

Some profiles used to set the meshfix_maximum_deviation to an odd number of microns. I rounded them _down_ after halving their values.

### CODE REVIEW

**Comment by BagelOrb** [comment]
This doesn't include any changes to the version "4.5" to "4.6". Should it?
I only need the version upgrade system to update to a new settings_version, which is from 11 to 12.

I don't think doing the whole version 4.6 should be part of this PR.

**Comment by fieldOfView** [comment]
Wow, 1400+ files need to change for such a small update. That puts startup performance into perspective...

**Comment by BagelOrb** [comment]
Haha yeah. I always have the biggest PRs :D

**Comment by fieldOfView** [comment]
It is sort of indicative though of a larger issue that the current approach of having all those quality profiles for all those printers in the main download is not tenable. Wasn't there once a plan to host them externally (Marketplace)?

**Comment by ChrisTerBeke** [comment]
@fieldOfView there was, but it requires some refactoring regarding XML material profiles (they can contain printer-specific settings) so we never came around to it so far.

**Comment by Ghostkeeper** [comment]
This PR is superseded by https://github.com/Ultimaker/Cura/pull/7385.

**Pull request closed without merging**
