### PR TITLE
Fix support eraser grouping

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR fixes issues with grouping and meshes created with the support eraser tool.

See https://github.com/Ultimaker/Cura/pull/3505#issuecomment-374141862:
> @Vandrasc has discovered a few issues:
>
>  1.  When grouping and then ungrouping a mesh with blockers, the blockers will fall to the build plate. This is expected but possibly confusing to users who don't know what the feature is doing under the hood.
>  2.  When importing and then ungrouping a project with blockers, the non-blocker meshes will just... vanish. This is of course not the expected behavior, even given what's under the hood.

With this PR, support eraser meshes are no longer ungrouped. The PR also fixes multiplying meshes that have support eraser meshes parented to them.

### CODE REVIEW

**Comment by Appesteijn** [comment]
Devs: CURA-5121

**Comment by ianpaschal** [comment]
Bad news. I'm getting the same behavior as before. In both places.

**Comment by ianpaschal** [comment]
**Case 1:**
ungroup

**Case 2:**
bad import

**Comment by fieldOfView** [comment]
~~~Are you sure you checkout out my branch? That's not what I am getting.~~~

Oh, wait, now I see. You first select all objects (which includes the parented objects) and then group them. This destroys the parenting.

**Comment by fieldOfView** [comment]
This should fix both cases. Note that the project saved before will have incorrect grouping; please create a new project to test.

**Comment by ianpaschal** [comment]
First one is fixed. Yay!

Second one still seems broken. I did create a new project. Same behavior as before with the disappearing base mesh.

Going to investigate further.

**Comment by fieldOfView** [comment]
Can you attach a project?

**Comment by ianpaschal** [comment]
[new testing.3mf.zip](https://github.com/Ultimaker/Cura/files/1825412/new.testing.3mf.zip)

**Comment by ianpaschal** [comment]
I just noticed that the imported support blockers also have that old problem of only deleting on the 2nd click.

**Comment by fieldOfView** [comment]
It is also interesting that when importing, the convex hull is wrong and the support meshes render in a lighter shade of grey (wut?).

**Comment by ianpaschal** [comment]
Ah yes! There was a 3rd thing that I couldn't think of while writing it. That was it.

**Comment by fieldOfView** [comment]
Ready for another round of testing.

The expected behavior with the tool is that when you deselect everything (click on the buildplate), the tool will not add/remove a support blocker. Instead that first click is used to make a selection. This is because when there is no selection you cannot activate another tool, so deselecting all objects would get you in a state where you cannot further manipulate the objects without adding or removing a support blocker. As long as there is a selection, the support blocker tool adds/removes support blockers on every click for me.

**Comment by ianpaschal** [comment]
Yup! Looks great! Thank you Aldo!

**Pull request merged**
