### PR TITLE
Support Eraser improvements

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR will improve the Support Eraser tool in a number of ways.

The original implementation of the support eraser has a rather big usability issue. Other than the other Tools in the toolbar, it is an action that is performed once when clicking the icon. All the other Tools are actually modalities: you click the tool and then manipulate the selected models. This is confounded by the placement of created cubes in the center of the buildplate; in all likelyness the model itself obscures the added cubes. When first using the tool I had clicked the tool at least 10 times before I discovered as many cubes had been added under my model.

This PR makes the Support Eraser modal, like the other tools. Once the tool has been activated, the user can click on the model to place anti-support-cubes on the clicked location:
anti_support

Picking is implemented with an "on demand" renderpass to render the "depth" of the scene. This PickingPass is implemented as a generic class that could be useful in more places in Cura. It provides functionality to pick a location at up to micron accuracy and a range of up to 16 meter.

TODO:
* ~~~Put the created anti-support-cubes into a group with the clicked model so (a) they don't drop to the buildplate when that option is enabled and (b) they move with the object when it is transformed~~~
* ~~~Click an added anti-support-cube to remove it again~~~
* ~~~Ignore press when nothing is selected~~~
* Allow dragging the anti-support-cube to scale it
* A panel with instructions (?)

### CODE REVIEW

**Comment by fieldOfView** [comment]
Even though I feel the current state of the PR is an improvement over the original implementation, the PR is not done; see the TODOs in the description. I can put in extra time to finalize this PR this week, but it would be rather disheartening if the PR would then remain in "pull-limbo" for over a month like some of my other PRs. @Appesteijn, would this stand any chance of getting merged before Cura 3.3?

**Comment by Appesteijn** [comment]
We are working hard to get up to speed with the Pull Requests (aka I am putting less new features in the last few sprints). 3.3-BETA is planned in two weeks, so if you could finish this in a few days we will add it to 3.3

**Comment by ianpaschal** [comment]
Thanks @fieldOfView! We actually broke the feature down into smaller pieces to make it more easy to incrementally improve. Placement with the mouse was step 2. I'd actually like to make a brush-style tool to paint in/out the red "overhang" designation at some point, maybe in a research sprint. But it's really great to already see this improvement.

It would be great to add it as soon as we can.

**Comment by ChrisTerBeke** [comment]
The GIF looks amazing! :)

**Comment by fieldOfView** [comment]
The GIF is a bit of a lie, because it has "drop models to build plate" disabled. See the first todo.

**Comment by fieldOfView** [comment]
This is now in a viable state and is ready for an initial test. The branch is up to date with master.

**Comment by Appesteijn** [comment]
Devs: CURA-5101

**Comment by ianpaschal** [comment]
Some results of my testing:

I believe the grouping causes this grey box to appear around the object:
screen shot 2018-03-16 at 12 40 42

This means that when you click an object, place a support blocker, then reselect the object (now a group) you can't apply per object settings to it.

Also, I'm not sure exactly how this happened, somehow I managed to select only a support blocker and then add a support blocker to it... or something... I can't seem to recreate it.
```
2018-03-16 12:40:50,113 - WARNING - [MainThread] UM.Scene.SceneNode.addDecorator [195]: Unable to add the same decorator type (<class 'cura.Settings.SettingOverrideDecorator.SettingOverrideDecorator'>) to a SceneNode twice.
2018-03-16 12:40:52,586 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-03-16 12:40:52,590 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-03-16 12:40:52,591 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Qt/Bindings/MainWindow.py", line 148, in mousePressEvent
2018-03-16 12:40:52,591 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._mouse_device.handleEvent(event)
2018-03-16 12:40:52,591 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Qt/QtMouseDevice.py", line 24, in handleEvent
2018-03-16 12:40:52,591 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.event.emit(e)
2018-03-16 12:40:52,592 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Signal.py", line 212, in emit
2018-03-16 12:40:52,592 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.__performEmit(*args, **kwargs)
2018-03-16 12:40:52,592 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Signal.py", line 315, in __performEmit
2018-03-16 12:40:52,592 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     func(dest, *args, **kwargs)
2018-03-16 12:40:52,592 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/Ultimaker/Uranium/UM/Controller.py", line 329, in event
2018-03-16 12:40:52,593 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     if self._active_tool and self._active_tool.event(event):
2018-03-16 12:40:52,593 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/Users/i.paschal/Code/fieldOfView/Cura/cura/../plugins/SupportEraser/SupportEraser.py", line 70, in event
2018-03-16 12:40:52,593 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     node_stack = picked_node.callDecoration("getStack")
2018-03-16 12:40:52,593 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: AttributeError: 'NoneType' object has no attribute 'callDecoration'
```

It's pretty bad though since it causes a crash to desktop.

On a more general note, I really like the click to place functionality but not so much the fact that I can't move my placed blocks or scale them. That doesn't really matter in a brush based tool because you can usually set your brush size, for example, as well as click and drag, but now it's a lot of clicking and a fixed size. So think the click to place is a huge improvement but the grouping not so much.

**Comment by fieldOfView** [comment]
> I believe the grouping causes this grey box to appear around the object:

Yes, it does. The grouping is necessary to prevent the added meshes from falling to the buildplate. I would prefer parenting the added meshes to the parent mesh (which prevents the extra dark shadow and the wireframe cage), but then they still drop to the buildplate - unless I fix up that code.

I'll fix the crash, thanks for testing.

Note that you can still move/resize the added meshes by switching to the move or scale tool and ctrl-clicking the objects.

**Comment by ianpaschal** [comment]
> Yes, it does. The grouping is necessary to prevent the added meshes from falling to the buildplate. I would prefer parenting the added meshes to the parent mesh (which prevents the extra dark shadow and the wireframe cage), but then they still drop to the buildplate - unless I fix up that code. Note that you can still move/resize the added meshes by switching to the move or scale tool and ctrl-clicking the objects.

Ah ok. I didn't know how to interact with sub objects. Also solves the issue of still being able to apply per-object-settings to the original object.

I'd say this introduces it's own not-so-intuitive twists but... there were already not-so-intuitive parts and I don't think we can eliminate them without building a whole new class of 3D brush style tools (which is sort of something I want to do in the research sprint: painting in/out the overhang area as an alternative to computing by angle). But that's a whollllle other thing.

So, while typing this I see you've made another commit for the crash. I think that case this is all good!

**Comment by fieldOfView** [comment]
@ianpaschal, see #3505 which does not add the group, simplifying the code. This way no cage is shown, and no additional convexhull is drawn.

**Comment by ChrisTerBeke** [comment]
Nice, it removes a support blocker cube when you click on it :)

**Comment by ChrisTerBeke** [comment]
And with the 3D viewer speed improvements with more meshes it works really well :)

**Comment by ChrisTerBeke** [comment]
It would also help if you can see a bit better through the underside of the build plate, as that's the angle you're often placing support blockers from.

**Pull request merged**
