### PR TITLE
HMS434 update

### PR DESCRIPTION
**Pull request by maukcc**
HMS434 multi tool update

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Can you take a look at the merge conflict?

**Comment by maukcc** [comment]
I am guessing it is complaining about value should be default_value.
Is there a reason to use default_value?
machine_gcode_flavor, machine_start_gcode and machine_end_gcode will not stick if you use value, but the others work just fine.
on the other hand gantry_height will not stick if you use default_value.
Maybe we could use some uniformity here.

**Comment by maukcc** [comment]
Also: the buildplate raster seems to have disappeared over the weekend. For all machines.

**Comment by Ghostkeeper** [comment]
> Is there a reason to use default_value?

Not really. It's really only there now to provide a default for CuraEngine which is not able to read the Python expressions. There is no reason for you to override `default_value` in a printer definition rather than to override `value`.

**Pull request merged**
