### PR TITLE
Update 5 files to add post-processor name to gcode

### PR DESCRIPTION
**Pull request by GregValiant**
# Description
Added a couple of lines of code so that these post processors will match the others I've altered and add their name to the end of data[0] in the gcode.

This fixes... OR This improves... -->
Keeps a record of the post processor used in a slice.
## Type of change

- [ X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Repeatedly

**Test Configuration**:
* Operating System: Win10 Home and Marlin

# Checklist:

- [X] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [X ] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by fieldOfView** [comment]
Instead of applying basically the same change to each postprocessing script, wouldn't it be better to add logic to the PostProcessing plugin to do this for all postprocessing scripts automatically?

**Comment by GregValiant** [comment]
That would be a more consistent way to go about it (and one that I hadn't considered).  It would eliminate the need for any new post-processor to include the code (although it's only a line or two).

On the other hand doing it as I have (within the code of the Post Processor) allows certain settings to be included in the added line, and messages can be passed.  Cherry-picking variables within "PostProcessingPlugin.py" would be messy, but simply adding the PostProcessor name could be done.

The changes I made (to all the post processors) produces this:
;MAXZ:145.6
;  Display Layer and Filename | Display Progress (Option: display_progress)
;  Advanced Cooling Fan Control (by_layer)
;  Pause At Layer ( 153 )
;  Alter Z-Hops (didn't run - Zhops not enabled)
;POSTPROCESSED

Adding code to PostProcessingPlugin.py I guess would result in: 
;MAXZ:145.6
;  Display Info on LCD
;  Advanced Cooling Fan Control
;  Pause At Height
;  Alter Z-Hops
;POSTPROCESSED

Part of what I envisioned was simply having more data available within the gcode.  Having those settings available at a glance, coupled with "AddCuraSettings" at the end of the file gives a pretty complete picture of how the file was sliced.
Maybe it's just a question of Style.  I figured people who actually bother to open a gcode and look at it would care that the information was there.

**Comment by GregValiant** [comment]
I think I can do that and still have the messages.  It means going over the post processors and pull requests (again).  It will take a bit of time.
I'm not good at pull requests.  Can I edit the files and the changes will show up?  Can I change them to drafts and make the changes?

**Comment by fieldOfView** [comment]
> Can I edit the files and the changes will show up?

Any change you make to the branch you created the PR from is added to the PR.

**Comment by GregValiant** [comment]
That'll work.

**Pull request closed without merging**
