### PR TITLE
edit start gcode

### PR DESCRIPTION
**Pull request by synsuiter**
Edited both axi and axi2 machine start gcodes to separate the xy moves and the z moves

### CODE REVIEW

**Comment by nallath** [comment]
I might be overlooking something, but those start g-codes look exactly the same.

**Comment by synsuiter** [comment]
@nallath are you referring to the code for AXI1 and AXI2 compared to each other or compared to the previous files submitted?

**Comment by synsuiter** [comment]
@nallath Please see bellow for exact changes in text:

\nG1 X-17.5 Y100 Z10 F3000                     ; move to wipe position
compared to 
\nG1 X-17.5 Y100 F3000                         ; move to wiper pad\nG1 Z10 F5000                                 ; move to wiper pad

AND

\nG1 X-17.5 Y80 Z10 F3000                      ; move back to wiper
compared to 
\nG1 X-17.5 Y80 F3000                          ; move to wiper pad\nG1 Z10 F5000                                 ; move to wiper pad

Capture
Capture2

**Comment by synsuiter** [comment]
@nallath Is there anything else needed for this change to be accepted? I am happy to answer any questions or provided any more needed information.

**Comment by rburema** [comment]
Hi @synsuiter  I messaged @nallath and it seems he missed that you replied. Sorry for the confusion. It seems we can merge this. Cheers!

**Comment by synsuiter** [comment]
@rburema , awesome! Thank you so much for your help! 😄

**Comment by rburema** [comment]
@synsuiter Thank _you_ for your contribution!

**Comment by rburema** [comment]
Speaking of forgetting things... Link-back to internal ticket: CURA-8299

**Pull request merged**
