### PR TITLE
Add Profile for Creality Ender 6

### PR DESCRIPTION
**Pull request by HOELLII**
Is there a reason this printer isn't yet added to Cura?

### CODE REVIEW

**Comment by HOELLII** [comment]
Updated variants to version 17. Check again.

**Comment by HOELLII** [comment]
Why does the check fail at the json file?
It is the Original File from the Creality Slicer 4.8.2 which is based on Cura.

I mean, i can remove the part with "machine_head_polygon", but i don't know if that's the right way.

Anyone has an idea or suggestion?

**Comment by nallath** [comment]
The machine_head_polygon was merged with machine_head_with_fans_polygon in 4.5, So if you change the setting to machine_head_with_fans_polygon it should work.

**Comment by Ghostkeeper** [comment]
For a while we had both polygons. Until at some point we figured only the shape with fans is really relevant for collision checking, and we removed the one without.

**Review by nallath — APPROVED** [review]

**Pull request merged**
