### PR TITLE
CURA-4525 multi build plate WIP

### PR DESCRIPTION
**Pull request by jackha**
See: https://github.com/Ultimaker/Cura/pull/3029

### CODE REVIEW

**Comment by nickthetait** [comment]
Care to show a screenshot in the current state?

**Comment by jackha** [comment]
Thanks for the interest :-) Here's a pic. In the "object menu" you can also select files and use the context menu.

cura-4525-multi-build-plate

**Comment by nallath** [comment]
Why make it a tool? That seems a bit weird to me (also; the tool menu is getting a bit cluttered.)

**Comment by jackha** [comment]
The "final" UI is yet to be designed. Currently it indeed clutters with the tools.
A possible idea is to "flip the settings side around" and you get a nice and big space.

**Comment by nallath** [comment]
Or a reserved bit of space in the main UI. I think this is interesting enough to take into acount. Having multiple workspaces will have such an impact on your workflow that it's almost impossible to do while fully remaining inside the scope of a plugin.

**Pull request closed without merging**
