### PR TITLE
Add a button to collapse the layerview legend

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds a button to the layerview legend to collapse it, mitigating complaints that the layerview legends takes up too much space.

### CODE REVIEW

**Comment by fieldOfView** [comment]
collapse

**Comment by nallath** [comment]
CURA-4547

**Comment by alekseisasin** [comment]
I would change the button icon when layer legend is visible, I prefer arrow_right

**Comment by fieldOfView** [comment]
I am using the same iconography for collapsing/expanding that is used elsewhere; categories in the sidebar and in the setting visibility preferences. I would not change it here without changing it in other places as well, for consistency. Consistency is important because it makes behavior predictable.

**Comment by fieldOfView** [comment]
I can see where this PR is going (2 weeks after the PR was opened)...

Before I reroll this against the Simulation View changes, some feedback whether this functionality is appreciated would be nice.

**Comment by ChrisTerBeke** [comment]
+1 from me to add this. Unfortunately we had conflicts to day that I manually resolved in order to be able to release the beta of 3.1 this week. I'll bring it up in the stand-up tomorrow and I have some time left I'll merge this.

**Comment by fieldOfView** [comment]
I am closing this PR, and will open a new one against the Simulation View panel.

**Pull request closed without merging**
