### PR TITLE
Adding_Acetate_profiles

### PR DESCRIPTION
**Pull request by KOUBeMT**

### CODE REVIEW

**Comment by nallath** [comment]
There seems to be a merge conflict with this. Could you resolve this?

**Comment by KOUBeMT** [comment]
can you please delete resources/quality/strateo3d/Standard_1.2/s3d_std1.2_PLA_H.inst.cfg
it should resolve the conflict...

**Comment by Ghostkeeper** [comment]
Developers, merge together with https://github.com/Ultimaker/fdm_materials/pull/138 in the `fdm_materials` repository. See CURA-7757.

**Review by Ghostkeeper — APPROVED** [review]
I didn't need to delete anything. Git resolves the conflict correctly automatically. I did update the setting_version though, which has no real consequences for these profiles since they don't adjust the material shrinkage ratio.

Nice to see you guys maintaining these profiles here.

**Pull request merged**
