### PR TITLE
Support for orthographic view

### PR DESCRIPTION
**Pull request by nallath**
This adds the much awaited orthographic view! 

Requires https://github.com/Ultimaker/Uranium/pull/490 to work 

CURA-5395

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Works great on MacOS:

image

**Comment by ChrisTerBeke** [comment]
The existing quick camera controls in the bottom left need some tweaking in orthographic though (e.g. this is the default right-side view:

image

**Comment by ChrisTerBeke** [comment]
The move/rotate/scale tools also seem broken when in orthographic mode (they're not responding to cursor input at all).

**Comment by LipuFei** [comment]
@ChrisTerBeke move/rotate/scale works here. Maybe it's only mac?

**Comment by LipuFei** [comment]
Confirmed that this a problem on Mac.

**Comment by diegopradogesto** [comment]
The support blocker doesn't work either.

Also the disallowed areas and the shadow below the object look different:
Screenshot 2019-05-23 at 08 48 49
Screenshot 2019-05-23 at 08 49 09

**Pull request merged**
