### PR TITLE
Cura-4358 Build Plate Adhesion default value takes the current value

### PR DESCRIPTION
**Pull request by ChrisTerBeke**
When BPA type is modified, and then the user changes Quality Profile, Cura will prompt user if they want to Keep or Discard Changes. However, the value for default is incorrect as displayed.

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
This PR is for other people than current core devs to comment on this change.

**Comment by ChrisTerBeke** [comment]
Connected Uranium PR: https://github.com/Ultimaker/Uranium/pull/292.

**Comment by fieldOfView** [comment]
Not just a better name; a description would be appreciated too

**Comment by nallath** [comment]
There.

**Comment by diegopradogesto** [comment]
What is done here is to use a context to avoid checking the user container stack when comparing the "default" and "customized" value of the settings. The initial problem was that when resolving the function in the build plate adhesion for getting the "default" value, the user container was used and then the value became the same as the "customized". Now the resolve functions such as getExtruderValue, getExtruderValues and resolveOrValue were remapped in order to use the context that avoids the first (or user) container. This fix also solves other similar problems in other settings, for instance "material_bed_temperature_layer_0".

**Pull request merged**
