### PR TITLE
added machine config file and extruder config file for FABLABBCN

### PR DESCRIPTION
**Pull request by EDUARDOCHAMORRO**
of the biomaterial, paste and ceramic printer opensource machine project of FabLab Barcelona.
https://gitlab.com/fablabbcn-projects/paste-extruder

### CODE REVIEW

**Comment by jellespijker** [comment]
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

**Comment by EDUARDOCHAMORRO** [comment]
added changes requested for machine config file- fablabbcn_pasteprinter.def.json

**Comment by jellespijker** [comment]
LGTM;
Sweat little printer you got there btw, what kind of paste are you printing with it?

**Comment by EDUARDOCHAMORRO** [comment]
Hi @jellespijker, we usually print clays and ceramic pastes but we have also tried biomaterials, as mixing coffee grinds or orange peels crushed and bound with agglutinates. We haven´t tried with geopolymers

**Pull request merged**
