### PR TITLE
Added retraction_combing_max_distance setting

### PR DESCRIPTION
**Pull request by smartavionics**
Combing travel moves longer than this distance will use retraction.

See #2531 and #3245.

### CODE REVIEW

**Comment by ctzsnooze** [comment]
Cool thank you!

**Comment by dmezh** [comment]
Thank you so much!

**Comment by Appesteijn** [comment]
Devs: CURA-5118

**Comment by ctzsnooze** [comment]
Any idea if this will come into an update of cure 3.3?

**Comment by fieldOfView** [comment]
This is more likely to be part of Cura 3.4

**Comment by ctzsnooze** [comment]
Thanks for the update!

**Comment by ctzsnooze** [comment]
Great!  Thank you!

**Comment by ctzsnooze** [comment]
Awesome, works really well

**Comment by notnyt** [comment]
This is broken over infill.

https://github.com/Ultimaker/Cura/issues/1901#issuecomment-438395778

**Comment by smartavionics** [comment]
> This is broken over infill.

It's no more broken than its ever been because combing never uses z-hop when moving over a single part.

**Pull request merged**
