### PR TITLE
Add printer profile for Modix3D printers

### PR DESCRIPTION
**Pull request by Modix3D**
Adds printer profiles for the Modix V3 line of printers: the Big40, 60, 120X, 120Z, 180X and Meter

This has been re-submitted under the Modix github account

### CODE REVIEW

**Comment by Modix3D** [comment]
@nallath Please let me know if any changes or edits are needed so that I can address it, or get movement on this pull request.

**Comment by Modix3D** [comment]
@Ghostkeeper and @nallath Is it possible to get this merged, or get feedback on what would need to get adjusted for it to get merged.

**Comment by 3DStreetFurniture** [comment]
^I'm surprised it wasn't merged into the beta.

**Comment by casperlamboo** [comment]
Hi @ Modix3D,

Thank you for opening the PR and adding the Modix3D printers to the platform.

As you have seen we have recently introduced a "printer linter" to automatically validate (part) of our printer PRs. I tried to  re-run the printer linter, but the printer linter failed due a bug (introduced from our side) in the code that was present when you merged from main. In order to re-run the printer linter we thus need to merge main back into your branch.

Once this is done we can continue with the review.

Thanks,
@casperlamboo

**Comment by Modix3D** [comment]
- Updated the end-gcode, 
	- it contained a typo (a rogue N) 
	- contained some old unsupported code (M107 instead of M106 S0)
	- properly de-selects the tool
	- moves to the back left corner instead of homing XY, which is a bit faster and doesn't need to move the bed

Thanks @casperlamboo for the update, it should be re-merged now.

-Lazar

**Comment by casperlamboo** [comment]
All looks good! thanks for the contribution. Merging now.

-casper

**Pull request merged**
