### PR TITLE
Update nwa3d_a31.def.json

### PR DESCRIPTION
**Pull request by DragonJe**
Updated to remove material setting and allow the profiles to be supported again using Generic PLA.

Thanks!

### CODE REVIEW

**Comment by DragonJe** [comment]
I removed material setting from the A31 and made the qualities global for Fabricator. 

I believe this should fix the issue with the qualities displaying as "not supported." 

The Deltacomb, that I also mentioned in my issue, has global qualities already, so I'm not sure why its profiles are still not supported.

**Comment by DragonJe** [comment]
Updated material settings for the A31 to align with variants

**Comment by Ghostkeeper** [comment]
Did you also want to submit a change to fdm_materials?

**Comment by DragonJe** [comment]
@Ghostkeeper no, because I thought the values in Fabtotum's fdm_materials will override the quality settings. So when their material is changed, it will change to the correct temps, etc. Am I correct to think that?

**Comment by Ghostkeeper** [comment]
No, the quality profiles override the material profiles. Here is some documentation on the precedence order: https://github.com/Ultimaker/Cura/blob/master/docs/Profile%20Stack.png

Note that your changes to me look fine (didn't test them yet though). Just something you might want to take into account since we can't test the actual print quality.

**Comment by DragonJe** [comment]
@Ghostkeeper will these changes be added to version 4.5.0?

**Comment by Ghostkeeper** [comment]
Ah, sorry. I think this one slipped through the cracks. I don't think we'll make it for v4.5 :disappointed: We have a feature freeze for that now.

It's good that you mention it again though. Sorry again.

**Comment by DragonJe** [comment]
Ok, thanks for the quick reply. I'll keep an eye out for it!

**Comment by nallath** [comment]
@DragonJe Could you resolve the issues mentioned by Ghostkeeper? If we don't get a response, we will close this pull request.

**Comment by DragonJe** [comment]
> @DragonJe Could you resolve the issues mentioned by Ghostkeeper? If we don't get a response, we will close this pull request.

Hi, yes! When COVID, this completely escaped my mind. I will work on it next week.

**Comment by nallath** [comment]
@DragonJe Another friendly reminder :)

**Pull request closed without merging**
