### PR TITLE
Cross fractal infill reimplementation

### PR DESCRIPTION
**Pull request by BagelOrb**
frontend setting to https://github.com/Ultimaker/CuraEngine/pull/630

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-4513.

**Comment by BagelOrb** [comment]
Rebased some time ago without pushing, so I'm pushing it now.

**Comment by Ghostkeeper** [comment]
This has been merged, but it seems the commit IDs had changed so Github doesn't know it's been merged (e.g. see https://github.com/Ultimaker/Cura/commit/6176b939d6e4186877adb66f33e2bce542ecbd8f). We'll close this PR then. Corry for the sonfusion.

**Comment by BagelOrb** [comment]
Darn Corry, always causing confusion!

Thanks for merging! :tada:

**Pull request closed without merging**
