### PR TITLE
[WIP] Use a single draggable range slider in Layerview

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR combines the two sliders in the LayerView with a single rangeslider. The rangeslider has three draggable handles: lower, upper and range. By dragging the range it is possible to always display eg 5 layers.

See https://github.com/Ultimaker/Cura/issues/1444

TODO:
* fix keyboard control
* use PointingRectangle for the layernumber box
* cleanup

### CODE REVIEW

**Comment by jackha** [comment]
Looks good, but the "middle" handle doesn't seem to work correctly yet. For my 10x10x10mm cube the lower handle moves more slowly. For my 100mm tall cube the lower handle doesn't seem to move at all.

**Comment by fieldOfView** [comment]
Unfortunately I won't have time this week to work on this. Will fix the remaining issues next week (unless someone wants to build on my work, in which case: feel free)

**Comment by fieldOfView** [comment]
@jackha: I think these issues were caused by the last commit (caa110b). Could you check?

**Comment by jackha** [comment]
Yes that's the cause... Version 6498a713e4d0528e6f15485a4e176ff4900540d7 works awesome! Are you currently refactoring or what?

**Comment by fieldOfView** [comment]
I am currently redoing this based on your layerview layout branch.

**Comment by fieldOfView** [comment]
I am closing this PR because I am working on a new PR against the layer_view3_layout branch.

I'll be back

**Comment by jackha** [comment]
Ah great. Just fixed some problems in the layer_view3_layout branch, make sure to get the newest commits as well.

**Pull request closed without merging**
