### PR TITLE
Add tab navigation to sidebar

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds tab-navigation between fields in the (custom) sidebar; it allows the user to tab/shift-tab between fields in the sidebar, making it quicker to make changes. Checkbox items can be operated with the spacebar, as can category headers. Comboboxes can be operated by the spacebar and/or up/down cursor keys.

### CODE REVIEW

**Comment by fieldOfView** [comment]
I know there's a JIRA issue about keyboard friendliness, but I can't remember the issue nr. Probably tagged somehow with Oak & Morrow.

**Comment by nallath** [comment]
CURA-1531

**Comment by fieldOfView** [comment]
Technically "you didn't do this" ;-)

Thanks for finding the jira issue. I had guestimated it was around 1900, but the 1500's makes sense. There's a similar issue about touchscreen friendliness that I still want to do.

**Comment by nallath** [comment]
If I have the focus of a category header, it "loops" between category headers. Is that intentional?

**Comment by BagelOrb** [comment]
@nallath You mean that you cannot get out of the category headers any more?

**Comment by fieldOfView** [comment]
@nallath please clarify. When I tab onto a category header, and press tab again, focus is moved to the next control (be it another header or a text/checkbox/combobox control)

**Comment by fieldOfView** [comment]
Ah, I think I see. When you expand a category, new controls are created and these are then out of the taborder. So tabbing to the next control will tab to the next category header instead of the first control in the category. I hope that can be fixed easily.

**Comment by nallath** [comment]
If it's something thats really hard to fix, i think we can still add the code as is. It's already a big improvement compared to the original state.

**Comment by fieldOfView** [comment]
Instead of relying on QML to automagically understand what we want it to do, I now catch tab and backtab and focus the correct item.

**Comment by nallath** [comment]
Thanks for the contribution!

**Comment by ErikDeBruijn** [comment]
Nice one @fieldOfView ! Your continued contributions are making Cura more and more pleasant to work with for everyone!

**Pull request merged**
