### PR TITLE
Added minus sign to have negative retractation when pausing for change

### PR DESCRIPTION
**Pull request by prochat**
The generated gcode is faulty as described here:
https://github.com/Ultimaker/Cura/issues/4114

My proposal seems to solve this problem.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Ah, but that then contradicts the change that was made here: https://github.com/Ultimaker/Cura/issues/4249 based on the findings of @boomercat and @putridp. We've had this value change back and forth a couple of times now!

**Comment by diegopradogesto** [comment]
I guess keeping it as positive would allow the user to enter both positive or negative numbers in the interface. So I would keep it as it is now.

**Comment by multiholle** [comment]
If you add a negative number, the generated gcode is missing the E parameter. This should really be fixed.

Also is the description of the parameter misleading.

**Comment by Ghostkeeper** [comment]
We're going to reject this. An explanation of why is written here: https://github.com/Ultimaker/Cura/issues/7502#issuecomment-617601243

**Pull request closed without merging**
