### PR TITLE
Elegoo Neptune series Printer Configuration

### PR DESCRIPTION
**Pull request by NARUTOfzr**
These are the config files that add the Neptune series from Elegoo.

### CODE REVIEW

**Comment by jellespijker** [comment]
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

**Comment by NARUTOfzr** [comment]
@jellespijker

**Comment by NARUTOfzr** [comment]
Hello @casperlamboo. 
Excuse me, what's wrong with these configuration files and what do I need to do to fix it?

**Comment by casperlamboo** [comment]
Hi @NARUTOfzr thanks for opening the PR and adding the neptune series. I see you branch has conflicts with our main branch. Can you please resolve these by merging our main branch back into your branch. After that I think the PR can be merged. I do not see any real issues anymore.

**Comment by NARUTOfzr** [comment]
@casperlamboo Thank you very much for your quick reply. Can I continue to modify the configuration file and add other machine configurations? Because our company recently launched two new machines, respectively Neptune3plus and Neptune3max.

**Comment by mroswald** [comment]
> @casperlamboo Thank you very much for your quick reply. Can I continue to modify the configuration file and add other machine configurations? Because our company recently launched two new machines, respectively Neptune3plus and Neptune3max.

I can't wait to get these changes in my hands, as the Elegoo distributed Cura is way behind! Thanks for your efforts! But I would suggest to create a dedicated PR for further changes, instead of blowing this one that is very close to getting merged.

**Comment by casperlamboo** [comment]
Indeed, a separate PR for the additional printers would be the desired way forward. But please resolve all merge conflicts in this PR before continuing so this can be merged, and further merge conflicts can be avoided.

**Comment by NARUTOfzr** [comment]
@mroswald Thank you for your attention and reminder.
@casperlamboo Thanks! I have merged the main branch into the branch I created.The picture shows conflicting files I don't know how to resolve.
image

**Comment by casperlamboo** [comment]
You have merged main into your branch on December 2nd: https://github.com/Ultimaker/Cura/pull/13706/commits/88f2dcfa1a7502b054f7aef95c2bdca72f75814b. There have since been more changes at our side on the relevant profiles, so the main branch needs to be merged again. Sorry for the inconvenience.

**Comment by NARUTOfzr** [comment]
@casperlamboo I seem to have done the wrong thing. I accidentally closed the PR. Can I open the PR again and merge the configuration file of ELEGOO-Neptune machine? Or do I need to recreate a pull request?

**Comment by mroswald** [comment]
> @casperlamboo I seem to have done the wrong thing. I accidentally closed the PR. Can I open the PR again and merge the configuration file of ELEGOO-Neptune machine? Or do I need to recreate a pull request?

You should see a button at the bottom of this PR `Reopen pull request`. If not (for whatever reason), you may need to recreate it.

**Pull request closed without merging**
