### PR TITLE
Deactivate G32 auto leveling before print

### PR DESCRIPTION
**Pull request by innovo3d**
don't need this any more on the new printers

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
There's a merge conflict, can you fix that so we can merge it?

**Comment by innovo3d** [comment]
I didn't really understand what the conflict was about. Can you explain?

**Comment by ChrisTerBeke** [comment]
GitHub indicates there's a merge conflict in the file `resources/definitions/innovo_inventor.def.json`. You can click resolve conflicts to see which lines are conflicting and fix them using GitHub's editor or locally.

**Comment by innovo3d** [comment]
I believe I've corrected the syntax now. I couldn't resolve/close it though, please review and let me know if there are any other actions pending.

**Comment by innovo3d** [comment]
Ok, I think its done now... it didn't like the way that I commented out a line... strange, it works if updated in the json file but I guess Github doesn't like it so I just removed the G32 S3 line altogether.  All should be good now.  Just to be clear, this will only be merged on the next 3.1 update?  When can we expect the next release?

**Comment by innovo3d** [comment]
Is everything all good with this now?



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

*Adam Rumjahn*
*CTO & Founder*

* <http://www.innovo3d.co>*

*adam@innovo3d.co <adam@innovo3d.co>Cel: +57 304 643 1248*
*Fijo: +57 2 374 2473*

**Comment by Ghostkeeper** [comment]
Yes, looks all right.

**Pull request merged**
