### PR TITLE
Added additional filters for USB serial devices

### PR DESCRIPTION
**Pull request by rmcolbert**
Sanguinololu boards show up as /dev/cu.SLAB_USBtoUART and /dev/ttySLAB_USBtoUART. Tweaked first glob to pick up USB anywhere after tty and added an uppercase USB for /dev/cu.*USB*.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Source for devices using `/dev/cu.SLAB_USBtoUART`: https://github.com/nodemcu/nodemcu-devkit/wiki/Getting-Started-on-OSX (I'm finding lots of sources talking about NodeMCU). I'm not finding anything for `/dev/ttySLAB_USBtoUART` though.

I believe it's better to make these globs a bit more strict than what they are now.

**Comment by nallath** [comment]
So it this something we should be merging or not?

**Comment by fieldOfView** [comment]
I still feel this should be left to PySerial, like so:
https://github.com/fieldofview/Cura/commit/4fad2a790bc466215dd459fd581e9253e3336ebc

**Comment by rmcolbert** [comment]
@fieldOfView The change to PySerial worked on Windows. Still need to test on Mac.

**Comment by rmcolbert** [comment]
I have verified that switching to use PySerial ([fieldOfView/Cura@4fad2a7](https://github.com/fieldOfView/Cura/commit/4fad2a790bc466215dd459fd581e9253e3336ebc)) works on macOS also.

**Comment by fieldOfView** [comment]
@rmcolbert, I have created #2107 as an alternative to this PR

**Comment by rmcolbert** [comment]
I'm definitely in favor of using PR #2107 instead of my workaround. I'm closing this PR.

**Comment by nallath** [comment]
Could you test if PR2017 fixes the issue for you?

**Comment by rmcolbert** [comment]
I have tested PR2017 on both Windows 10 & macOS. It passed in both cases.

**Comment by nallath** [comment]
Excellent, thanks!

**Comment by Ghostkeeper** [comment]
Let us know if you have those updates for the 101Hero ready ;)

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/pull/2109

**Pull request closed without merging**
