### PR TITLE
Update and fix Kingroon KP3S Pro missing nozzle

### PR DESCRIPTION
**Pull request by Tachyonn**
# Description

This fixes missing nozzle variants as in #16435 and updates definintion file.
Changes:
  - Added the default "machine_depth" value to ```Cura/resources/definitions/kingroon_kp3s_pro.def.json```
  - Changed the default "machine_name" value ```Cura/resources/definitions/kingroon_kp3s_pro.def.json```
  - Added missing nozzle variants to ```Cura/resources/variants/kigroon```
## Type of change

- [x] Printer definition file(s)

# How Has This Been Tested?

- [x] Test A
  - Added new Kingroon KP3S Pro printer. On the Machine Settings page Depth value now 200 instead of 180 as it was before.
  - On Generic PLA profile nozzle variants appears and not showing Empty as it was before.

**Test Configuration**:
* Operating System:
Windows 10, Cura 5.4.0
# Checklist:

- [ ] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by saumyaj3** [comment]
Hey Tachyonn! 

Thanks for the contribution. 👯‍♂️

**Comment by zippy85** [comment]
Hi - Great news, i have the exact same problem. How do i change this? when i try to make changes in cura json file, it says i dont have permission to change it. Can you help with a guide?

**Comment by Tachyonn** [comment]
> Hi - Great news, i have the exact same problem. How do i change this? when i try to make changes in cura json file, it says i dont have permission to change it. Can you help with a guide?

You need to download [kingroon_kp3s_pro.def.json](https://github.com/Ultimaker/Cura/blob/main/resources/definitions/kingroon_kp3s_pro.def.json) and place it to ```<your_current_cura_install_dir>/share/cura/resources/definitions```.
You need to download all files with "pro" suffix from [here](https://github.com/Ultimaker/Cura/tree/main/resources/variants/kingroon), kingroon_kp3s_pro_0.2.inst.cfg and so on, and place it to ```<your_current_cura_install_dir>/share/cura/resources/variants/kingroon``` folder.
Restart Cura.

**Comment by zippy85** [comment]
> > Hi - Great news, i have the exact same problem. How do i change this? when i try to make changes in cura json file, it says i dont have permission to change it. Can you help with a guide?
> 
> You need to download [kingroon_kp3s_pro.def.json](https://github.com/Ultimaker/Cura/blob/main/resources/definitions/kingroon_kp3s_pro.def.json) and place it to `<your_current_cura_install_dir>/share/cura/resources/definitions`. You need to download all files with "pro" suffix from [here](https://github.com/Ultimaker/Cura/tree/main/resources/variants/kingroon), `kingroon_kp3s_pro_0.2.inst.cfg` and so on, and place it to `<your_current_cura_install_dir>/share/cura/resources/variants/kingroon` folder. Restart Cura.

Hi Tachyonn - Thanks for quick reply and for your work :) I will try it out again.
Have a nice day

**Comment by zippy85** [comment]
It worked!!! thank you so much 🥇

**Comment by kawasero79** [comment]
Hi Tachyonn, I had the same problem! I downloaded everything as you describe, I restarted Cura and laminated a piece. But when I open the file on the printer it restarts. Has it happened to anyone else? Thank you

**Pull request merged**
