### PR TITLE
Fix floods of QML errors in styles.qml

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR prevents hundreds of QML warning messages logged per second in some user reports of Cura being slow.

https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/24#issue-872046698 includes a log that has 700 of these warnings in the span of 2 seconds.

https://github.com/Ultimaker/Cura/issues/9628#issuecomment-823952208 also has hundreds of these warnings.

These warnings seem to be more prevalent in combination with the SidebarGUI plugin, but I see them too with "vanilla" Cura, especially when closing the application.

styles.qml currently uses `UM.Theme` and `Theme` interchangeably. This PR changes that to consistently use `UM.Theme` like the rest of Cura. For me that makes all the warnings go away.

I have made this PR against the 4.9 branch, because I think it is imperative that this gets fixed in a 4.9.1 release.

```
2021-04-30 11:42:01,492 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///.../cura/../resources/themes/cura-light/styles.qml:335: TypeError: Cannot read property 'getSize' of null
2021-04-30 11:42:01,492 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///.../cura/../resources/themes/cura-light/styles.qml:338: TypeError: Cannot read property 'getColor' of null
2021-04-30 11:42:01,500 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///.../cura/../resources/themes/cura-light/styles.qml:327: TypeError: Cannot read property 'getSize' of null
2021-04-30 11:42:01,500 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///.../cura/../resources/themes/cura-light/styles.qml:329: TypeError: Cannot read property 'getColor' of null
2021-04-30 11:42:01,500 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///.../cura/../resources/themes/cura-light/styles.qml:335: TypeError: Cannot read property 'getSize' of null
2021-04-30 11:42:01,500 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///.../cura/../resources/themes/cura-light/styles.qml:338: TypeError: Cannot read property 'getColor' of null
2021-04-30 11:42:01,500 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///.../cura/../resources/themes/cura-light/styles.qml:327: TypeError: Cannot read property 'getSize' of null
2021-04-30 11:42:01,500 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///.../cura/../resources/themes/cura-light/styles.qml:329: TypeError: Cannot read property 'getColor' of null
```

### CODE REVIEW

**Comment by fieldOfView** [comment]
The CI failure seems to be unrelated to my changes.

**Comment by jellespijker** [comment]
My hero!
This annoyed the %^&@# out of me as well.

**Comment by jellespijker** [comment]
I wholesomely agree with you that this should be in the 4.9.1 release, but I'm not the only stakeholder in this. So I will discuss it with the PO and testers and come back to you on Monday. But I can't see any of them say that this shouldn't be in the 4.9.1

**Comment by jellespijker** [comment]
Adding it to 4.9.1 and pulled it in the sprint as Jira ticket CURA-8204

**Comment by jellespijker** [comment]
Looks good, thanks for the PR

**Pull request merged**
