### PR TITLE
Adding 3DI D300 and  3DI D220 to Cura

### PR DESCRIPTION
**Pull request by v27jain**
We are a 3D Printer manufacturing company in Pune, India. We wish to add our machine definitions to upcoming Cura versions.

### CODE REVIEW

**Comment by v27jain** [comment]
Can anyone kindly approve and run the workflows ?

**Review by okrvj12 — APPROVED** [review]

**Comment by Ghostkeeper** [comment]
Did you intend to close your pull request?

Sorry that we only approved the workflows twice. It's a recent change from Github that we have to approve it every time. We haven't really gotten used to it yet.

Please run the automated tests yourself as well though! It's a simple `make test` command from CMake in your repository.

**Comment by v27jain** [comment]
Yes, I want to close this. Actually I didn't know regarding the make test command, so I closed this and  created a new pull request in which all the tests are checked and it's completely fine. Best regards.

**Comment by Ghostkeeper** [comment]
Ah, found it: https://github.com/Ultimaker/Cura/pull/9863 replaces this one.

**Comment by v27jain** [comment]
So once all the checks are passed, does it automatically show up in the next release ?

**Comment by Ghostkeeper** [comment]
No, we would first need to review it, test it and merge it.

**Comment by v27jain** [comment]
Okay. The query was regarding #9863. 
Regards.

**Pull request closed without merging**
