### PR TITLE
Update extruder files for Magna 2 230 and 300

### PR DESCRIPTION
**Pull request by DevelopmentHellbot**
Add start and end gcodes for Magna 2 230 and Magna 2 300 for switching extruders. The start gcode was also updated.

### CODE REVIEW

**Comment by nallath** [comment]
This branch has conflicts with the main line, so we can't merge them right now. Could you resolve these issues?

**Comment by nallath** [comment]
> The conflicts come from the modifications on the start and end gcodes. How can i resolve the conflicts and keep the modificactions that i made ?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by Ghostkeeper** [comment]
Hmm, this seems to also include part of https://github.com/Ultimaker/Cura/pull/10614?

**Review by Ghostkeeper — APPROVED** [review]

**Comment by Ghostkeeper** [comment]
Doesn't really matter :) We're humans, so as long as it's all there, it's fine.

**Comment by Ghostkeeper** [comment]
With the other branch in, the changes here were indeed only to the extruder files:

```
 resources/definitions/hellbot_magna_2_230_dual.def.json          | 2 +-
 resources/definitions/hellbot_magna_2_300_dual.def.json          | 2 +-
 resources/extruders/hellbot_magna_2_230_dual_extruder_0.def.json | 8 +++++++-
 resources/extruders/hellbot_magna_2_230_dual_extruder_1.def.json | 8 +++++++-
 resources/extruders/hellbot_magna_2_300_dual_extruder_0.def.json | 8 +++++++-
 resources/extruders/hellbot_magna_2_300_dual_extruder_1.def.json | 8 +++++++-
```

**Pull request merged**
