### PR TITLE
Formatted README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>
  
- ***[Why not to use GitHub Wiki][Wiki]***

  <br>

- I didn't remove any badges, though personally I would drop the first row
  as those stats are either redundant or uninteresting opposed to the size,
  the people working on it, ..

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Added quicklinks

- Formatted & moved reporting 
  issues into dedicated file

- Referenced links

- Added logo

- Unified badges

- Removed redundant licening note

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

## ![Badge Info]

If you want to know more about **Markdown** check out:

<br>

                            [![Button MarkedDown]][MarkedDown]

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Cura

### CODE REVIEW

**Comment by digitalfrost** [comment]
Looks nice, but does this mean we have to create a new badge on [img.shields.io](https://shields.io/)  if we want to add additional sections to the README ?

Also the README is no longer very readable in a text editor.

I think the pull request is nice until line 31. This is the new  header / masthead. 
I think the original file is nicer from line 25 onwards (the screenshot and everything underneath) as it then fulfills its function as a README.

**Comment by digitalfrost** [comment]
I would also drop the first line of badges.

**Comment by ElectronicsArchiver** [comment]
> Looks nice, but does this mean we have to create a new badge on [img.shields.io](https://shields.io/) if we want to add additional sections to the README ?

? They are auto generated like before, you just add different text / color, that's it

> Also the README is no longer very readable in a text editor.

Well if you actually cared about text only editors, the previous one wasn't that much better.
If you want a text only version I can make a separate one designed for that specifically.

> I think the pull request is nice until line 31. This is the new header / masthead.
I think the original file is nicer from line 25 onwards (the screenshot and everything underneath) as it then fulfills its function as a README.

Well considering a README is the front page of a repo, I think it should act as such, as a hub, to get you to the content you want, not everything at once, not things you didn't ask for.

Showcase some stuff, link to resources, that's it, just like project websites do.

> I agree about the redundant badges.
I would also drop the first line of badges shown in the [preview](https://github.com/ElectronicsArchiver/Cura)

Guess I should still wait on what a maintainer rules..

**Comment by jellespijker** [comment]
@Joeydelarago Since you recently worked on the documentation can you take a look at this one?

**Comment by Joeydelarago** [comment]
Hey, thanks for the contribution. The new README looks really slick. I'll most likely go through our other repositories and copy this style. If you see I haven't done it yet, feel free to take the work off my hands. Just request my review on the pull request and I will check it out.

**Pull request merged**
