### PR TITLE
Stop Esc key from exiting full screen mode

### LINKED ISSUE #7499: Minor but annoying UI issues
**Application version**
4.5.0

**Platform**
Windows

**Printer**
N/A

**Reproduction steps**
1. Maximise Cura window. Press ESC key. Window is un-maximised - this is unexpected and contrary to normal Windows style.

2. Although there are Maximise/Minimise buttons (top right hand corner of Cura window), and although the system menu has enabled maximise and minimise options when you use the mouse to activate it by clicking on the Cura icon at the top left corner of the Cura window, when you use Alt-Space to activate the system menu the maximise and minimise options are not enabled - which means that those of us who use the keyboard to avoid switching to the mouse and back again cannot minimise or maximise by Alt-Space and then n/m.

**Screenshot(s)**
Can be provided if needed.

**Actual results**
1. Esc de-maximises window.
2. Maximise / Minimise not enabled when system menu is shown using Alt-space.

**Expected results**
1. Esc should not de-maximise window.
2. Maximise / Minimise should be enabled when system menu is shown using Alt-space.

### PR DESCRIPTION
**Pull request by Sophist-UK**
# Description

Fixes #7499

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Printer definition file(s)
- [ ] Translations

# How Has This Been Tested?

It hasn't been tested - because I was previously unable to create a run-from-source environment.

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by Sophist-UK** [comment]
Note: This is based on #14356 but has a much smaller change limited literally to removing the key binding for Esc.

Hopefully this minimalism will allow this PR to be merged. #14356 should be closed.

**Comment by Sophist-UK** [comment]
Some actions are failing but I do not believe this is as a result of this PR as they both seem to be linked it Github credentials not working.

HOWEVER...

Whilst this PR should still be a good fix (because Esc should NOT IMO exit fullscreen mode in any case), the Cura code exists so that Esc should exit Qt's FullScreen mode (which it does do), however it also exits Maximised mode and goes to Restored mode as well. This may well be a Qt bug / quirk, and I am unsure whether stopping Esc from exiting FullScreen mode will also cause it to switch from Maximised to Restored.

I will research further.

**Comment by fieldOfView** [comment]
I have tested the fix, and it works.

**Comment by Sophist-UK** [comment]
Excellent!!

**Comment by fieldOfView** [comment]
> Excellent!!

Yes, it works, but it will probably not get merged as is. Please remove the line instead of commenting it out. That way you also don't need the new comment. You can push a new commit to the same branch, and the PR will automatically update.

NB: ultimately, it is not up to me to decide what gets merged or not. I am just a community member, like you.

**Comment by Sophist-UK** [comment]
> NB: ultimately, it is not up to me to decide what gets merged or not. I am just a community member, like you.

No - given the size and scope of your contributions you are definitely not just a community member like me.

**Review by nallath — APPROVED** [review]

**Pull request merged**
