### PR TITLE
Update FilamentChange.py

### PR DESCRIPTION
**Pull request by Poporacer**
The L parameter is used for the filament load length the additional unload parameter is U

### CODE REVIEW

**Comment by rburema** [comment]
Thanks for the PR!

It seems that `U` is only required for a [Marlin-flavoured](https://marlinfw.org/docs/gcode/M600.html) printer though, [RepRap](https://reprap.org/wiki/G-code#M600:_Filament_change_pause) makes no mention of the `U` in their `M600`, only `L`.

**Comment by Poporacer** [comment]
That could be a problem since Marlin uses `L` for Load length and RepRap uses `L` for additional **unload** length. It looks like RepRap does not have a load option? The problem with the Additional Unload length is that if you are using Marlin based firmware, once the filament is loaded, it will then load the additional` L` value and usually will strip the filament. A couple solutions:
1. Label the current "Later Retraction Distance" as "RepRap Later Retraction Distance" and add another option labeled "Marlin Later Retraction Distance" and in the code utilize the appropriate flag values. Possibly add an additional option of "Marlin Load Length"
2. On the tool tip for the "Later Retraction Distance" include the information that this is only for RepRap based systems?

**Comment by rburema** [comment]
Hi @Poporacer 

When looking through the code to see how other scripts handle these things: `PauseAtHeight.py` and `DisplayProgressOnLCD.py` simply let the user choose a method (gcode flavour) from a dropdown (via 'method' and, one 'time remaining' is enabled 'time remaining method' respectively -- the second one has the simpler menu).

**Comment by nallath** [comment]
I think we can close this in favor of  #10403

**Pull request closed without merging**
