### PR TITLE
Fix error when CrashHandler is opened before opengl is initialised

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR fixes a Python error being thrown when CrashHandler is opened before opengl is initialised.

Contributes to #2837

### CODE REVIEW

**Comment by Appesteijn** [comment]
Devs: CURA-4621

**Comment by ChrisTerBeke** [comment]
We should probably cherry-pick this to 3.1 as well.

**Comment by ChrisTerBeke** [comment]
I merged it to master, I'll cherry pick this tomorrow when I have some more time.

**Comment by ChrisTerBeke** [comment]
Picked to 3.1 as well now.

**Pull request merged**
