### PR TITLE
Ender 3 Max Complete Profile Added

### PR DESCRIPTION
**Pull request by baldaaaa**
Contributions:
- Ender 3 Max detailed definition
- Ender 3 Max platform mesh
- Ender 3 Max nozzle variants

### CODE REVIEW

**Comment by loraderon** [comment]
Is there any reasons for this PR to not be merged? It's seems like a simple changes that doesn't affect any other areas at all and would benefit us with this printer immensely.

**Comment by baldaaaa** [comment]
Exactly what I was thinking. Can someone with write access kindly help with the merge?

**Comment by nallath** [comment]
Apologies! We've been busting our behinds off to meet the 5.0 deadline, so we've been slacking with PR's. I've carved out a bit of time to handle them.

**Comment by nallath** [comment]
For our reference: CURA-8934

**Review by nallath — APPROVED** [review]

**Pull request merged**
