### PR TITLE
Fix issues with Workspace and Profile Changes dialogs

### PR DESCRIPTION
**Pull request by fieldOfView**
Some recently added dialogs don't work nicely with Hi DPI screens, and don't use the system theme properly. This PR fixes some of those issues.

Fixes https://github.com/Ultimaker/Cura/issues/1634

### CODE REVIEW

**Comment by fieldOfView** [comment]
I think Jenkins is having issues. I have only changed qml files, and AFAIK there are no tests for the qml files.

**Comment by awhiemstra** [comment]
It failed on Windows because it could not find the Uranium files. The Windows build slave had some issues so I triggered a rebuild. Now it's fine. :)

**Comment by Appesteijn** [comment]
I have tested this PR and there is a typo which causes a crash: CRITICAL - 3MFReader.WorkspaceDialog._createViewFromQML [234]: QQmlComponent error string file:///Applications/Cura.app/Contents/MacOS/plugins/plugins/3MFReader/WorkspaceDialog.qml:36 Cannot assign to non-existent property "fille"

Besides that this is how my Open Project dialog looks like on my MacBook Pro (2016) 
screen shot 2017-04-05 at 10 55 35

**Comment by fieldOfView** [comment]
@Appesteijn, thanks for reporting. If you change that ```fille``` to ```fill```, does that also fix the layout issue?
See #1651 which fixes the typo

**Pull request merged**
