### PR TITLE
Create creality_ender3S1.def.json

### PR DESCRIPTION
**Pull request by LA3QMA**
Added Creality Ender-3 S1

### CODE REVIEW

**Comment by nallath** [comment]
Is there a specific reason that you removed skirt from the options to allow for platform adhesion?

**Comment by LA3QMA** [comment]
> Is there a specific reason that you removed skirt from the options to allow for platform adhesion?

My mistake. "skirt/brim/raft" etc should be available.
Also the default start gcode should include "M420 S1; use stored ABL data"

**Comment by jellespijker** [comment]
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

**Comment by Joeydelarago** [comment]
Hey @LA3QMA, sorry about getting back to you so late. We have had a PR that added the ender3S1 reviewed and merged since you created this PR. I am going to close this PR, but if you have any changes you would like to make to the existing profile based on this PR please open a new PR for it.

Thanks!

**Pull request closed without merging**
