### PR TITLE
Updated innovo_inventor.def.json settings

### PR DESCRIPTION
**Pull request by innovo3d**
Added M140 to turn off heated bed
Changed default extruder temp to 205
Changed print speed defaults
Removed infill overlap override
Removed machine preferences

### CODE REVIEW

**Comment by innovo3d** [comment]
I just found another feature I want to add :P sorry

**Comment by innovo3d** [comment]
How do I add another commit to this PR?

**Comment by nallath** [comment]
Adding it to your branch should do the trick.

**Comment by innovo3d** [comment]
Done! Looks like all of the changes are in there in this PR.  Let me know if you guys need anything else.  Thanks so much!

**Comment by Ghostkeeper** [comment]
Looks fine. Works fine. Merges fine. Thanks!

**Pull request merged**
