### PR TITLE
Add platform mesh for the 101Hero & updated printer profile to use it.

### PR DESCRIPTION
**Pull request by rmcolbert**

### CODE REVIEW

**Comment by nickthetait** [comment]
Do you work for the kickstarter/company or are you a user of the 101Hero?

**Comment by rmcolbert** [comment]
I am a user of the 101Hero. The base profile for the printer already existed. I only added the mesh and updated the definition file to point to it.

**Comment by Ghostkeeper** [comment]
Devs, see CURA-4046.

**Comment by fieldOfView** [comment]
Note: the way to prevent commits from one feature to end up in the PR for another commit is to create a "feature branch" per feature you are working on. As a rule of thumb it is never a good idea to create a PR from your master branch.

**Comment by nallath** [comment]
To keep the history a bit cleaner, i added the platform in a separate commit. I also saved the platform as binary, which decreases the size a bit. See dee09e15aed7ff4924188130ef9927cc262fcabd

**Pull request closed without merging**
