### PR TITLE
Persistent Post-Processing Scripts

### PR DESCRIPTION
**Pull request by Ghostkeeper**
This change will cause the added post-processing scripts to be saved in the user's configuration. Post-processing scripts were one of the few things that did reset when you restart Cura. No longer!

Post-processing scripts are added on a per-printer basis instead of globally. This choice was made because the scripts are quite often printer-dependent, compensating for broken firmware or adding small features to the g-code in the same way as the normal settings.
As such, the post-processing scripts will be removed when you switch to a different printer, and reappear if you switch back. You could view them as global settings.

Implementation details: The post-processing scripts that were added and the settings that belong to them are stored in the metadata of the global stack (as serialised config files). They can never cause a name clash with existing settings (which is a requirement also because you can add multiple of the same script). Their order is retained. It also does not require any version upgrade because the metadata is optional. If the metadata entry is missing it will cause the script list to be empty. If a post-processing script is changed in later versions to have a different setting name, that setting will reset to its default value unless a version upgrade deals with the change, just like our normal settings.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
This implements https://github.com/Ultimaker/Cura/issues/2796, https://github.com/nallath/PostProcessingPlugin/issues/46, https://github.com/Ultimaker/Cura/issues/2854 and https://github.com/Ultimaker/Cura/issues/3133.

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-4623.

**Comment by Drayson80** [comment]
Damn, I want this feature so heavy since a long time... PLEASE make it into CURA3.3!!

**Comment by jackha** [comment]
merge conflict: loadAllScripts needs to be rewritten :-(

**Comment by Ghostkeeper** [comment]
The merge conflict is resolved now.

**Comment by Kriechi** [comment]
This introduces a bug where newlines in the replace string are mangled/removed/lost.
ref #2103

Example:
  * Search: `;LAYER:`
  * Replace: `M118 P4 S"foobar"\n;LAYER:`
  * No regex

Not save & restart Cura. The newline will be missing. Or the UI simply refuses to display the whole string altogether end empties the field.

**Comment by Ghostkeeper** [comment]
Thanks for the bug report. I've fixed that now in master, so it should be fixed in the next release.

**Comment by thelastWallE** [comment]
Can we maybe have just a checkbox in the printsetting menu, there we can enable or disable all postprocessing altogether?
Or a set of settings which one can enable if he wants to print a temp tower.
To have to stacking the ChangeatZ Scripts on top of each other and change a number of settings is not very userfriendly. Then one would only have to set the bandwidth of layers for this temperature, startlayer for the first change, step-increment for the temperature and number of changes for the whole tower.
Anmerkung 2019-12-07 133938

**Comment by Ghostkeeper** [comment]
> Can we maybe have just a checkbox in the printsetting menu, there we can enable or disable all postprocessing altogether?

The currently advised workflow (since post-processing scripts are stored with the printer) if you use post-processing scripts that are specific to a print rather than a printer, you can switch them on or off by having two printers and switching between the two. This way you won't have to go into the post-processing scripts list and delete all of them. The use case is small though, since if your post-processing scripts are specific to the print rather than the printer, then there's little reason to store them for the next print anyway; you'll need to remove them for the next print usually, unless you're printing many of the same thing but with small adaptations.

> Or a set of settings which one can enable if he wants to print a temp tower.

You mean the prime tower? There's a set of settings for that.

> To have to stacking the ChangeatZ Scripts on top of each other and change a number of settings is not very userfriendly. Then one would only have to set the bandwidth of layers for this temperature, startlayer for the first change, step-increment for the temperature and number of changes for the whole tower.

Which workflows are user friendly is a function of both the size of the use case (how often is it used) and complexity of the system. We've not yet implemented per-layer settings but we're keeping it open as a possibility for the future in our architecture. For now, ChangeAtZ is a passable workaround but even there we don't see a lot of usage yet.

If you actually have an issue with this, please open up a ticket and fill in the template!

**Pull request merged**
