### PR TITLE
[WIP] Rework connection via USB

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR aims to solve the following issues:

* Cura does not properly (auto-)detect all printers, and a manual port-selection is missing
* Cura tries connecting to all serial ports on startup, resetting all connected printers (and other Arduino-based peripherals)
* A USB connected printer is "seen" by all printer-instances in Cura as "the" USB-connected printer
* In case of multiple connected printers, there is no way to see which printer is connected to which serial port

It works off this proposal: https://github.com/Ultimaker/Cura/issues/1049. Also see https://github.com/Ultimaker/Cura/issues/70 for discussion.

Instead of automatically trying to connect to any USB serial device, this PR will present the user with a dialog to deliberately connect a printer to a serial port (or an automatic option, which still allows the user to scan all ports). It will also allow the user to disable connecting to the USB printer on startup, so Cura no longer resets the printer when starting.

### CODE REVIEW

**Comment by fieldOfView** [comment]
I have created this premature PR mostly so it can get a JIRA issue and you know what's coming.

**Comment by Ghostkeeper** [comment]
For devs, see CURA-3690.

**Comment by awhiemstra** [comment]
Note that the unit tests are failing because you branched at a point where unit tests in master were broken. Merging master should fix that. :)

**Comment by Ghostkeeper** [comment]
Can you let us know when you consider this finished, @fieldOfView?

**Comment by fieldOfView** [comment]
Not for a while. I can close this in the mean time and reopen when I am done. Let me know what you prefer.

**Comment by nallath** [comment]
We just had a research sprint, so we were a bit slow to respond. I think closing this and opening it when its done is the best option.

**Comment by fieldOfView** [comment]
I am fairly happy with the interface work, but getting it all functional is taking more time than expected. I am retracting this PR for now, and will return once I have a working solution (hopefully in time for 2.7)

**Pull request closed without merging**
