### PR TITLE
Adding support for additional object files

### PR DESCRIPTION
**Pull request by thopiekar**
* 3MF files
* OBJ files

### CODE REVIEW

**Comment by thopiekar** [comment]
I wasn't sure about the name for obj files, so I took "application/prs.wavefront-obj" for traditional *.obj files and I also found "application/vnd.ms-3mfdocument" for 3MF files, as found here:
```
application/vnd.ms-3mfdocument			3mf
```
https://git.fedorahosted.org/cgit/mailcap.git/plain/mime.types

But this page is telling something else: http://fileformats.archiveteam.org/wiki/3MF

What do you think?

**Comment by Ghostkeeper** [comment]
I'm guessing you found http://stackoverflow.com/questions/18641754/mime-type-of-wavefronts-obj-and-mtl too.

**Comment by thopiekar** [comment]
Correct, but I didn't take '''text/plain''', because every file format
(.txt and all other based on '''text/plain''') would take Cura as
supporting application. So I created a XML, which explains that all
.obj files are called prs.[...] and is based on text/plain, so you can
still open .txt with text-editors and .obj with text-editors and Cura.

I'll add this XML during this day.

**Comment by awhiemstra** [comment]
http://www.iana.org/assignments/media-types/application/vnd.ms-3mfdocument
So IANA agrees with the mime type you found. And since they are the final registration point of mime types, that seems the correct one to use. You might want to file a bugreport for shared-mime-info that points them to that type, since shared-mime-info should have all IANA defined types by default iirc.

As for OBJ, unfortunately, like STL there is no proper defined mime type for it. Ideally we'd have some additional lines to distinguish them from text files by more than just the extension, but that might prove tricky.

**Comment by thopiekar** [comment]
Ah, ok. I was just google'ing for these mime types, but didn't know about a official resource.
Good to know this mime-type is correct.

Correct, these files just don't simply start with a specific header.
@awhiemstra: What do you think? Could we keep it like this or should we wait, until there is a better solution?

**Comment by Ghostkeeper** [comment]
This is fine for now. I don't think a better solution will present itself in the near future.

**Pull request merged**
