### PR TITLE
Show USB target temperatures, (estimated) time and jobname

### LINKED ISSUE #2760: Mac 3.0.4 Monitor Page Incorrect Target Temperature + Missing Job Name
Hello everyone. I noticed an issue with Cura 3.0.4 on Mac, and as you can see in the screenshot below, the target temperature display "0C" for both extruder and build plate despite it properly being set, indicating a UI issue? Job name, print name, estimated time left are also either empty or at 00:00:00. Is this the normal behavior for anything that's not an "official" ultimaker? I would normally try to fix an issue and do a pull request, but unfortunately I am unfamiliar with this project. Can anyone chime in and check what's going on?

screen shot 2017-11-09 at 3 50 22 pm

screen shot 2017-11-09 at 3 55 32 pm

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR enhances the USB Printing plugin to show target temperatures (from M105 responses), shows the total and estimated remaining time, and the jobname while printing. This was previously left unimplemented.

This PR fixes #2760

### CODE REVIEW

**Comment by nallath** [comment]
CURA-4574

**Comment by fieldOfView** [comment]
Note that this PR was made before the 3.1 branch was made. Since this PR constitutes a fix, and does not have any string changes, it could still be considered for Cura 3.1 (hey, one can hope...)

**Comment by nallath** [comment]
I'm re-writing how a ton of the output devices work, as it's a mess right now. I hope to get that in for 3.2.

**Comment by fieldOfView** [comment]
So does that mean that this is not going to get merged?

**Comment by nallath** [comment]
Well, the code can be re-used, but we need a slightly different structure for it.

**Comment by fieldOfView** [comment]
I would rather close the PR if it does not get merged. I have enough lingering PRs to keep up to date.

Note that I would argue that this PR could be merged into 3.1 still, because it fixes a longstanding issue and has no string implications or any influence on the Ultimaker happy path (since that does not include USB printing anyway).

**Comment by nallath** [comment]
Yeah, but that is outside of my control. I'm re-writing the network connection as that's a complete mess and it's interfering with Cura Connect. I'm not with the "regular" Cura team right now.

**Pull request merged**
