### PR TITLE
Fix definition changes for UMO upgrade options

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR fixes https://github.com/Ultimaker/Cura/issues/1879

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Devs, see CURA-3875.

**Comment by fieldOfView** [comment]
PR is against master, but this really needs to be fixed in Cura 2.6; it is a regression introduced with the cura stack rework.

**Comment by Ghostkeeper** [comment]
Uh, I'm getting the error:

    2017-05-31 17:12:13,433 - CRITICAL - cura.CrashHandler.show [39]: An uncaught exception has occurred!
    2017-05-31 17:12:13,434 - CRITICAL - cura.CrashHandler.show [42]: Traceback (most recent call last):
    2017-05-31 17:12:13,435 - CRITICAL - cura.CrashHandler.show [42]:   File "/home/ruben/Projects/Cura/cura/../plugins/UltimakerMachineActions/UMOUpgradeSelection.py", line 41, in setHeatedBed
    2017-05-31 17:12:13,436 - CRITICAL - cura.CrashHandler.show [42]:     definition_changes_container = self._createDefinitionChangesContainer(global_container_stack)
    2017-05-31 17:12:13,436 - CRITICAL - cura.CrashHandler.show [42]:   File "/home/ruben/Projects/Cura/cura/../plugins/UltimakerMachineActions/UMOUpgradeSelection.py", line 55, in _createDefinitionChangesContainer
    2017-05-31 17:12:13,437 - CRITICAL - cura.CrashHandler.show [42]:     container_stack.definitionChanges = definition_changes_container
    2017-05-31 17:12:13,438 - CRITICAL - cura.CrashHandler.show [42]: NameError: name 'container_stack' is not defined

Should that variable be `global_container_stack`?

**Comment by Ghostkeeper** [comment]
I cherry-picked your commit to the 2.6 branch and then added my fix on top. Github doesn't recognise it because of the cherry-pick, so I'm closing this manually. Thanks for your fix!

**Comment by fieldOfView** [comment]
Thanks for fixing my fix. I am afraid I can't remember having thoroughly tested my fix, so I guess I may not have. Sorry for PR'ing untested code.

**Pull request closed without merging**
