### PR TITLE
Adding TwoTrees Bluer printer

### PR DESCRIPTION
**Pull request by WashingtonJunior**
Adding TwoTrees Bluer definition and platform files.

### CODE REVIEW

**Comment by WashingtonJunior** [comment]
Adding TwoTrees Bluer definition and platform files.

**Comment by nallath** [comment]
Please don't re-use the custom_extruder. This might cause unintended changes if that file is ever changed.

**Comment by konskarm** [comment]
The printer slices fine and I do not see any issues with the added files, so I am merging this.

**Comment by WashingtonJunior** [comment]
Thank you!!!

**Comment by konskarm** [comment]
Note that the printer will be available in 4.9, since the 4.8 is scheduled for next week.

**Pull request merged**
