### PR TITLE
ATMAT machines profiles

### PR DESCRIPTION
**Pull request by gandzia44**
Hi,

This is PR contains ATMAT machines profiles.

Regards,
Szymon.

### CODE REVIEW

**Comment by gandzia44** [comment]
Is there something wrong with CI/CD right now?

**Comment by Ghostkeeper** [comment]
No, it's rightly complaining, about several things:
* Definition files should not define an `id`.
* Variants are referring to a definition called `signal_pro_500_old` which doesn't exist.
* Definition files are overriding `default_value` while a setting has an actual `value`.
* Missing platform mesh files.

Did you test these profiles in an actual Cura version, or just wrote them from the top of your head?

**Comment by gandzia44** [comment]
I had problem with building CURA so I tested files on already builded last release. I will fix it tomorrow morning, now I know what to look at

**Comment by konskarm** [comment]
Devs see CURA-7323

**Comment by gandzia44** [comment]
Going to change it this weekend

**Comment by ninovanhooff** [comment]
Any update @gandzia44  ?

**Comment by gandzia44** [comment]
Sorry, there was some mess caused by COVID.
I pushed commits with requested changes.

**Comment by konskarm** [comment]
Hi @gandzia44. We have now released the 4.6 and upped the setting_version to 13. Which means that it has to be changed to 13 for variants and also for the qualities. As soon as this is done I can confirm that the profiles can be added for Cura 4.7, as there is no other change to be done.

Sorry for that inconvenience.

**Comment by konskarm** [comment]
I will merge this PR without the buildplates for the printers mentioned above, as there is no answer yet and it is not that big of an issue.

**Pull request merged**
