### PR TITLE
add definition for Sovol SV05

### PR DESCRIPTION
**Pull request by maxkreja**
I've noticed that there is no preset for the Sovol SV05. The manual of the printer even states to use a Sovol SV01 as base and just change the name and dimensions. However, there are a few more differences between the Sovol SV01 and the SV05:

- SV05 has a direct drive extruder → reduced `retraction_amount` to 0.5 mm from 3 mm
- suggested print speed for SV05 is 80 mm/s -> increased `speed_print` to 80 mm/s from 50 mm/s
- adjusted `machine_width`, `machine_height` and `machine_depth` to match the SV05s print volume of 220x220x300
- changed the name of the machine and extruder

The default acceleration and jerk settings are also really conservative for a printer with the layout of the SV05, but I did not change them yet because I have to thoroughly test the printer with higher acceleration and jerk settings.

### CODE REVIEW

**Comment by eropple** [comment]
FYI - you may want to look at https://github.com/Ultimaker/Cura/pull/13716, where I've reworked the Sovol definitions to be more in line with others and built some general-purpose profiles. I don't have a SV05, so I'm projecting from the SV01PRO and SV06, and suggestions are gratefully appreciated.

**Comment by jellespijker** [comment]
Can you sync your fork, with our `main`. We have added a **printer-linter** tool for our printer definitions and profiles. This should help us with processing our PR's. It performs some standard diagnostic checks and apply auto-formatting on the changed files in this PR, but you can also run it locally. See https://github.com/Ultimaker/Cura/tree/main/printer-linter

If it finds issues for which it knows a fix it should post a comment with that suggested fix such that you can easily commit that fix if you're okay with it.

**Comment by maxkreja** [comment]
As mentioned in #13716 I would like to postpone this PR until #13716 is merged, and I am done with my testing. Thanks @eropple, for your input on this topic.

**Comment by jellespijker** [comment]
You can change this PR to a WIP PR such that it will be very clear that it isn't finished to be merged just yet

**Comment by jellespijker** [comment]
@maxkreja the other Sovol printers have been merged, you might want to sync your fork again and build on those.

**Pull request merged**
