### PR TITLE
Merging UM3NetworkPrintingPlugin into Cura

### PR DESCRIPTION
**Pull request by thopiekar**
Contributes to CURA-2862

### CODE REVIEW

**Comment by fieldOfView** [comment]
There are commits before june 28 in the original repo:
https://github.com/Ultimaker/UM3NetworkPrintingPlugin/commits/master?after=A34lcccDu2ehYRd8p%2Fymlu5A%2FcIrMzE0

**Comment by thopiekar** [comment]
Hmm, I also wonder why they are missing.
Maybe all lines have been changed since that time so Git skipped them? Can't answer myself why this happend :confused: 

Would you say that it really hurts to have these commits missing? :roll_eyes:

**Comment by fieldOfView** [comment]
How did you create your branch?

**Comment by thopiekar** [comment]
You are right @fieldOfView :disappointed:
For a reason my git says that there are no commits left. `git log UM3NPP_merge..UM3NPP/master` gives no output.
I'll try to force git to add these commits by cherry-picking..

**Comment by thopiekar** [comment]
Cherry-picking seems to add commits only on the top. That's probably the reason why I'm getting conflicts here. Will try to find an alternative solution tomorrow, which hopefully merges all commits together.

**Comment by thopiekar** [comment]
Or wait: Maybe a Github bug?

I picked one of the commits on your page which seem to miss. And guess what:
```
thopiekar@home:~/Projekte/eclipse-Ultimaker/Cura$ git branch -a --contains 48625ed129d190eecedba19afe7f2a10f0d6aaf1
* UM3NPP_merge
  remotes/UM3NPP/master
  remotes/UM3NPP/thopiekar-adding-additional-warning-message
  remotes/origin/UM3NPP_merge
```

So looks like Github is wrong here. :upside_down_face:

**Comment by thopiekar** [comment]
@fieldOfView to answer you question: I just merged both branches together.

**Comment by thopiekar** [comment]
@nallath Can we merge this? :wink:

**Comment by Ghostkeeper** [comment]
While this pull request is linked to an issue that's still in ToDo on our Jira board, we expect that there is still some work to be done.

**Pull request merged**
