### PR TITLE
Fix Rectangles that always show as white regardless of the theme

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR removes a number of unthemable white blocks from the sidebar.
See the white areas here: 
borrowed screenshot

Fixes https://github.com/Ultimaker/Cura/issues/1371

### CODE REVIEW

**Comment by awhiemstra** [comment]
Note that any rectangle with colour "transparent" could also be replaced with a simple Item instead.

**Comment by fieldOfView** [comment]
I agree. I'll amend my PR

**Comment by fieldOfView** [comment]
I have replaced transparent rectangles with items throughout Cura.

**Comment by Ghostkeeper** [comment]
I went into theme.json and replaced all colours (using the regex `\[\d{1,3},\s*\d{1,3},\s*\d{1,3},\s*\d{1,3}\]`) with pure red `[255, 0, 0, 255]`. The result is now this:

pureredtheme

As it looks now, it seems that one colour is not yet themeable: The colour of the icons for print preview on the top right (white on the screenshot). Clicking things in this interface is very hard; it requires some guesswork. But I wasn't able to make anything else appear other than pure red. The other things you see in the screenshot are the build plate, which is intended because it has a texture, and the colours of the materials (the little yellow blocks), which is also intended.

Merging this right now is fine with me as it is a strict improvement. But would you like to make the last little detail themeable as well?

**Comment by fieldOfView** [comment]
"mooi rood is niet lelijk" ;-)

The two icons in the sidebar are on my list of things to fix. The print monitor icon has colored overlays. These icons are the only SVG files among the icons where the color is taken from the SVG file. The icon should be split into two icons; the printer icon, and a status overlay. The status overlay can then be colored using the theme instead of the SVG file.

**Comment by fieldOfView** [comment]
The two header tab buttons are now also themeable.

**Pull request merged**
