### PR TITLE
Stop postprocessing plugin creating unnecessary script folders

### PR DESCRIPTION
**Pull request by fieldOfView**
# Description

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- install any plugin that includes i18n functionality. 
It needs to register the parent of its i18n folder to be able to load translations
- remove the `scripts` folder from the configuration folder
- run Cura
- inspect the plugin folder
- a `scripts` folder should _not_ be created there
- a `scripts` folder should have been created in the configuration folder

**Test Configuration**:
* Operating System:
Tested on Windows. Note that on Linux the scripts folder may be created in two locations (preference folder and configuration folder can be split). 

# Checklist:

- [x] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [x] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/contributing.md) 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by casperlamboo** [comment]
Hi @fieldOfView thank you for opening this PR. To be honest I'm a bit confused by the issue. I tried to follow these steps from the **main** branch. This is what happened
1. I started Cura, and installed the SettingsGuide as I know this plugin to rely on translations
2. After closing Cura I removed the `~/Library/Application Support/cura/5.4/script` folder (I'm on macOS this is where my cura configuration lives)
3. After starting Cura again the `~/Library/Application Support/cura/5.4/script` folder was re-created. I could not find any `script` folder in the `plugins` folder

This is intended behavior, is it not? I experienced the same behavior when running from the PR-branch. Could you confirm I'm performing the right reproduction steps and or clarify what in the progress is unexpected.

Thank you in advance!

**Comment by fieldOfView** [comment]
The settingsguide plugin does not use the Uranium i18n module, so it does not need to add itself as a resource storage path. Try eg the MeshTools plugin instead, which adds its resource folder to the resources searchpath:
https://github.com/fieldOfView/Cura-MeshTools/blob/release/MeshTools.py#L52-L59

**Review by casperlamboo — COMMENTED** [review]
Ah, I see. I do get the changes now! I do however have one suggestion. Namely: add a `continue` when the script folder doesn't exists. This mimics the previous behavior where the loop would continue when failing to create a path.

**Comment by casperlamboo** [comment]
Thanks for applying the changes! All looks good 👍

**Pull request merged**
