### PR TITLE
desktop.in: Ultimaker Cura everywhere!

### PR DESCRIPTION
**Pull request by thopiekar**

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Are we sure this doesn't affect lookups from other applications?

**Comment by thopiekar** [comment]
On Linux? No, this is only an menu entry - nothing else.

**Comment by thopiekar** [comment]
Also we are overwriting this file in cura-build when creating the AppImage.
So this change is only visible in my Cura PPAs.

**Comment by thopiekar** [comment]
Works:
image
image

Thanks @ChrisTerBeke

**Pull request merged**
