### PR TITLE
Hopefully Adding the Makeblock 3d Printer files to the latest version

### PR DESCRIPTION
**Pull request by pkz0313**
I created definition, extruder, and quality for the Makeblock 3D Printer. I hope that it could be in the latest release of Ultimaker Cura!

Thanks a lot!

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
I tried to find this 3D printer, but on the [Makeblock website](https://www.makeblock.com/) it doesn't list them. After searching for it with a search engine I did find [this one](https://www.makeblock.com/project/mgiraffe-3d-printer-kit) which seems to be a community project of sorts. However that printer is called the "mGiraffe". And it's a Delta printer, which this definition is not.

What is this printer and where can I find information about it?

**Comment by pkz0313** [comment]
@Ghostkeeper Hi, sorry for bringing you inconvenience. This 3d printer is our new product and it can't be found on the Makeblock Website yet.

[](url)
[Makeblock mCreate Product Introduction--EN.pdf](https://github.com/Ultimaker/Cura/files/3791962/Makeblock.mCreate.Product.Introduction--EN.pdf)

**Comment by Ghostkeeper** [comment]
Ah, right. Then maybe can we call this printer "mCreate" or "Makeblock mCreate" then, instead of just generic Makeblock? The manufacturer can still be Makeblock. But that would allow for other printers by Makeblock to be added in the future as well and would reduce confusion of people that have those other printers at home.

And if you do, please also rename the files.

**Comment by pkz0313** [comment]
ok. The files had been renamed.

**Comment by Ghostkeeper** [comment]
Developers, please refer to issue CURA-6952.

**Comment by Ghostkeeper** [comment]
The `gantry_height` override has no effect, since you are only overriding the `default_value` but this setting has a `value`, which gets precedence over the default_value.

A gantry height of 0 will effectively prevent one-at-a-time mode as well. Are you sure that's what you intended? You could also just deactivate the `print_sequence` setting.

**Comment by pkz0313** [comment]
The gantry_height had been updated.

**Comment by fieldOfView** [comment]
The `gantry_height` override still has no effect, because you are still setting a default value instead of a value.

**Comment by nallath** [comment]
I've already fixed that in master (since our CI was also complaining about that)

**Comment by pkz0313** [comment]
Thank you! You guys are so nice.

**Pull request merged**
