### PR TITLE
Add Crazy3DPrinter Definitions

### PR DESCRIPTION
**Pull request by heed818**
Hi,
I just add Definitions for Crazy 3D Printers,
Please help to check,thank you.

### CODE REVIEW

**Comment by heed818** [comment]
Hi,we have modify definition for Crazy3D CZ-300,please help to merge to master,thank you.

**Comment by heed818** [comment]
Hi @nallath 
I have changed definition for Crazy 3D Printers,may it be merged to master?
thanks:)

**Review by nallath — APPROVED** [review]

**Comment by heed818** [comment]
Hi @Ghostkeeper ,may i know how does it automatically show up in the next release ?
thank you

**Comment by Ghostkeeper** [comment]
Yes, this should show up in the 4.12 release.

**Comment by heed818** [comment]
> Yes, this should show up in the 4.12 release.

Ok,thank you for the information :)

**Pull request merged**
