### PR TITLE
CURA-4182 Slider for quality profile

### PR DESCRIPTION
**Pull request by LipuFei**
slider_1
slider_2

### CODE REVIEW

**Comment by fieldOfView** [comment]
No more custom profiles that can be used in Simple mode ? 👎

**Comment by fieldOfView** [comment]
step-4

**Comment by ChrisTerBeke** [comment]
Hi @fieldOfView. What we're trying to fix with this PR is that it was unclear to users what the impact of a profile was for quality vs speed. We think that custom profiles belong in the custom settings.

**Comment by fieldOfView** [comment]
The power of having custom profiles (ie: Quality Changes profiles) in Recommended mode is that you could give a user a good working profile for a certain printer/material or even for a certain feature, without showing the complexity that is behind it. Eg a profile for printing vases, without having to hunt down vase mode.

**Comment by awhiemstra** [comment]
Whoa, that is a lot of code just to do a slider with tick marks. Have you looked at how any of the QML controls implement this?

**Comment by nallath** [comment]
Yeah, we did. It's not just the tick marks, it's also about disallowing certain parts of the slider and showing different messages on certain parts of the slider.

**Pull request merged**
