### PR TITLE
Fixes shader creation with Ubuntu+nvidia

### PR DESCRIPTION
**Pull request by Patola**
This fixes issue #88 with Ubuntu + nvidia

### CODE REVIEW

**Comment by daid** [comment]
I do think this needs a tiny platform dependeny check, as on linux adding this is most likely fine (as the package is easy to install) but on Mac and Windows adding python-opengl as a dependency isn't that great. (And it will possibly break "angle" support on windows)

**Comment by awhiemstra** [comment]
Hmm, the problem I have with this is that it is an Ubuntu-specific bug that we are now solving by adding a global dependency. A simple platform.system() == "Linux" check would at least reduce it to "just" Linux but for Fedora or Arch users that would still introduce an additional dependency. Ideally this would just be fixed upstream, but until it is I would be fine with introducing this workaround as long as it is limited to Ubuntu/Debian based systems.

**Comment by Patola** [comment]
I will remake the patch. Thanks

**Comment by thopiekar** [comment]
Think something like
```
if platform.system() == "Linux":
    if platform.linux_distribution()[0] in ("Ubuntu", ): # Just in case it also happens on Debian, so it can be added
        from OpenGL import GL
```

**Comment by BurtonQin** [comment]
This problem occurred to me after I installed NVDIA driver. Thanks to the answers above, I found it easy to deal with.
1.**ldconf -p | grep libGL.so**
    I found that the first entry is still
    libGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so
    instead of 
    libGL.so (libc6,x86-64) => /usr/lib/nvidia-340-updates/libGL.so
2. **cd /etc/ld.so.conf.d**
    I found many conf files, including   
    i386-linux-gnu_GL.conf  and x86_64-linux-gnu_GL.conf
    **cat x86_64-linux-gnu_GL.conf**
    /usr/lib/nvidia-340-updates
    /usr/lib32/nvidia-340-updates
    but i386-linux-gnu_GL.conf is empty.
    So I just copy the contents in x86-linux-gnu_GL.conf to i386-linux-gnu_GL.conf
3. **sudo ldconfig**
    Everything is OK now☺

**Comment by thopiekar** [comment]
I'll test it today.
Can you report this problem at launchpad? Would be great to have it fixed
in Ubuntu itself.
Another important question: to you still get this segmentation fault, when
closing Cura?

However, I would still keep this fix alive until Ubuntu fixes this problem.
What do you think?

**Pull request closed without merging**
