### PR TITLE
Add plug-in to read PLY files

### PR DESCRIPTION
**Pull request by Ghostkeeper**
Cura can natively read PLY files now.

There is a change that needs to be made to cura-build as well in order to allow the Windows installer to open these files as well. I'll make that change promptly.

Contributes to issue CURA-6739.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Yay for using Trimesh to do this!

At some point it would be nice to move _toMeshData into something that can be used by multiple plugins.

**Comment by Ghostkeeper** [comment]
Yeah, true. I'm working now on some of the other file formats as well and each time it needs this _toMeshData function...

**Comment by fieldOfView** [comment]
Perhaps it could be worth it to rename this plugin to TrimeshReader.py and also let it handle other relevant formats such as Collada (.dae).

**Comment by Ghostkeeper** [comment]
Yeah, I think I'll do that.

**Pull request merged**
