### PR TITLE
Jogging

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds manual printhead/printbed control ("jogging") and is a partial implementation of the proposals in https://github.com/Ultimaker/Cura/issues/979#issuecomment-254503356

The implementation has been tested with OctoPrint (the master branch of the OctoPrintPlugin has some fixes for this), and should work for USB-connected printers too (because they have the same API). The PR hides the interface for Cura Connect clusters. I don't know if it works for single UM3 printers. If it doesn't, there is a convenient bool to set in the constructor of the NetworkPrinterOutputDevice, like this:
https://github.com/Ultimaker/Cura/blob/a9f2ad7ca348f974949d811b913f01e53d7ffa81/plugins/UM3NetworkPrinting/NetworkClusterPrinterOutputDevice.py#L106

This is what it currently looks like:
image

### CODE REVIEW

**Comment by nallath** [comment]
Whoo! Nice work!

**Comment by nallath** [comment]
CURA-4488

**Comment by Appesteijn** [comment]
Is it difficult to add temp and speed control and make this work for UM3s?

**Comment by fieldOfView** [comment]
I don’t have an UM3 to test this with, so I don’t know if it works or not.

The extruder/bed temps and extrusion functionality I would like to integrate with the extruder items and bed preheat above in a followup pr.

**Comment by nallath** [comment]
Should be pretty easy to get it to work with an UM3. Do note that it can't / won't work with any printer that runs connect.

**Comment by fieldOfView** [comment]
>  Do note that it can't / won't work with any printer that runs connect.

I have already added code that hides the controls for a Cura Connect cluster.

If it does not work for UM3 (has anyone tested?), please attach some logs

**Comment by fieldOfView** [comment]
Hmm, NetworkPrinterOutputDevice does not expose an API to send Gcode directly. @nallath, I thought you said that functionality is available? Since the UM3 firmware is not publically available, can you point me in the right direction endpoint-wise?

**Comment by nallath** [comment]
I don't think homing is available. But for the rest; all properties can accept a put which should update it.

**Comment by fieldOfView** [comment]
For now, I have hidden the jogging UI for the UM3(Ex), since it does not have the API to support jogging and I am unable to add an implementation of that API without access to an UM3.

**Comment by ChrisTerBeke** [comment]
Also works over USB (tested with UM2+ on Windows).

**Comment by ChrisTerBeke** [comment]
@fieldOfView with the new cluster API manual control is not possible anyways, so I'd say it's outside the scope of this PR indeed.

**Comment by mikeq3** [comment]
This is a good start. I really need the ability to preheat the nozzle and extrude or retract a specified length. Can we add a button to preheat the nozzle similar to the bed preheat button/field? Also an extrude and retract button with a length field?

**Comment by Ghostkeeper** [comment]
That would be a nice addition.

But don't get your hopes up. If it doesn't work on the Ultimaker 3 there will be little chance nowadays that Ultimaker's employees get to spend their time on it. However it can't work for the Ultimaker 3 since that runs cluster firmware now which has an API that doesn't support it. You can't make the API support it either since the cluster firmware is closed software...

**Comment by fieldOfView** [comment]
This PR is meant as a start. I plan to do follow up PRs, starting with preheating and extrude/retract.

**Comment by robinmdh** [comment]
@fieldOfView The UM3 (stand alone) does support jogging, You can put the coordinates of the head.
We removed the debug gcode execution though.

**Comment by fieldOfView** [comment]
@robinmdh, I know (jogging, but no homing). However, I don't have a UM3 to test with, and I would not want to commit untested code. I also heard that the Cura Connect stuff would interfere (https://github.com/Ultimaker/Cura/pull/2669#issuecomment-341136584), and again since I have no UM3, I have no idea about that.

**Comment by Rudy-Raw** [comment]
I was wondering if consideration can be given to adding a jog control for the E step extrude and retraction?
Thank for any reply.

**Comment by fieldOfView** [comment]
It has, but I gave priority to (pre-)heating extruders. There’s a PR for that in review. Once that merges, I’ll revisit extruding/retracting

**Comment by Rudy-Raw** [comment]
That's great! Will be looking out for it.

**Pull request merged**
