### PR TITLE
Fix Z hops when retracting

### PR DESCRIPTION
**Pull request by Ghostkeeper**
These are profile changes needed to ensure that the behaviour is the same as what it used to be.

See https://github.com/Ultimaker/CuraEngine/pull/1155 for a full explanation.

Implements CURA-6860.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Need to hold those horses a little bit as this ticket is still in progress and we're investigating the purpose and expected behaviour of the Only Hop Over Printed Parts setting. We're doing our best to keep everything both working consistently and working the same as in previous versions, though those may be in contradiction here. Still in progress!

**Comment by smartavionics** [comment]
Ok, so here's a look at some gcode created today and you can see it z-hops just fine.

Screenshot_2019-10-30_09-08-05

**Comment by smartavionics** [comment]
Travel settings are:

Screenshot_2019-10-30_09-11-00

Ignore the max comb extra distance addition as that is set to 0 and not having any effect.

**Comment by Ghostkeeper** [comment]
Superseded by https://github.com/Ultimaker/CuraEngine/pull/1185.

**Pull request closed without merging**
