### PR TITLE
Add new printer profile

### PR DESCRIPTION
**Pull request by markbernard**
Add the Anet A6 printer profile to the Cura master.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-6505.

The definitions look correct from the source code. I'm trying them out now.

**Comment by Ghostkeeper** [comment]
The platform mesh is located inside the build volume. I'll shift it down a bit.

**Comment by Ghostkeeper** [comment]
I made one small modification and then merged it: https://github.com/Ultimaker/Cura/commit/4910bc006b761635b5a4480115e9efaf3c0ab299

Thanks! I've seen this printer being used in people's project files quite a lot.

**Comment by markbernard** [comment]
Glad to do it. I didn't think about making the build plate below 0 in the Z. I remember if I ever do another one. Thanks.

**Pull request merged**
