### PR TITLE
Add new machine Goofoo Cube

### PR DESCRIPTION
**Pull request by goofoo3d**
Goofoo Cube is our new machine, please add it to the Cura project! Thanks!

### CODE REVIEW

**Comment by goofoo3d** [comment]
I add our newest machine Goofoo Cube and modify some goofoo_cube definitions and 0.7_pla_standard, please check it! Thanks!

**Comment by goofoo3d** [comment]
Merry Christmas! When should my submission be merged?

**Comment by tgoff** [comment]
Any chance we could get this merged?  I had to manually copy these files in to get my new GooFoo Cube printer to work.  It looks like the PR is just failing a code style test because of missing newlines?

**Comment by Ghostkeeper** [comment]
The failing code style issues are due to the state of this branch being outdated vs. the state of the build environment the CI runs on. They are not the fault of this issue.

We are quite behind on PRs. Sorry for that. This is currently the next oldest one, so I'll review it now.

**Review by Ghostkeeper — APPROVED** [review]
Seems to work correctly. Thank you for the contribution!

**Pull request merged**
