### PR TITLE
Add few things to 'About' dialog

### PR DESCRIPTION
**Pull request by diegopradogesto**
Add native rendering to the labels

The 'close' button was also changed to use the common style.

### CODE REVIEW

**Comment by fieldOfView** [comment]
AFAIK the native rendering is already implied by Label in QTQuick Controls 1. But it does not hurt to have it twice.

**Comment by diegopradogesto** [comment]
Ah, OK, I didn't know it. I saw a lot of `Label`s without it and I always tend to add it when I see it as a boy scouting process.

**Comment by fieldOfView** [comment]
Note that this PR places a Cura-themed close button on a system-themed background. This is not necessarily "correct". I would say you either make the whole dialog Cura-themed, or make all of it (except maybe the logo, because that is defined in the theme) system-themed. Hisotrically, any dialog that was opened from Cura would be system-themed, but that rule has been abandoned a little while ago (with marketplace being Cura-themed).

**Comment by Ghostkeeper** [comment]
We're slowly working towards making all dialogues Cura-themed. Next up is the preferences window.

That being said, I think we should change the whole dialogue at once rather than only one button of it, so that it would look good for release even in between. So I'm inclined to reject this PR. It only adds an unnecessary font rendering property and a button that would look out of place.

**Comment by Ghostkeeper** [comment]
Nallath agreed. We're closing this.

**Comment by Ghostkeeper** [comment]
I'll leave it up to @diegopradogesto to delete the branch unless he wants to argue this decision.

**Comment by diegopradogesto** [comment]
OK, I agree! It's better to do it all at the same time.

**Pull request closed without merging**
