### PR TITLE
Solidworks export to Cura update

### PR DESCRIPTION
**Pull request by RichardB95**
I have made some modifications to the solidworks macro for exporting STL files to Cura. Currently every file that is sent to Cura has the same name (model_for_cura). This isn't very helpful when you want to print of an SD card. My fix fetches the part name and exports the file to cura using this part name.

This is the modified macro:
' ******************************************************************************
' C:\Users\s.edwards\AppData\Local\Temp\swx6644\Macro1.swb - macro recorded on 01/30/17 by s.edwards
' ******************************************************************************
Dim swApp As ISldWorks
Dim Part As Object
Dim tempFileName As String
Dim tempDir As String
Dim All As Boolean
Dim boolStatus As Boolean
Dim stlBinaryFormat As Boolean
Dim stlQuality As Integer
Dim swModel      As SldWorks.ModelDoc2
Dim myWS As Object
Dim curaVersion As String
Dim curaDir As String
Private Function EnumerateRegistryKeys(hive, key) As Collection
Dim curaKeyNames As New Collection
Dim idx As Integer
idx = 1
'get all Cura key names
Set reg = GetObject("winmgmts://./root/default:StdRegProv")
reg.EnumKey hive, key, arrSubKeys
If Not IsNull(arrSubKeys) Then
For Each subkey In arrSubKeys
If InStr(1, subkey, "Cura ") = 1 Then
curaKeyNames.Add subkey
idx = idx + 1
End If
Next
End If
'sort the cura key names with the latest version first
Dim i As Long, j As Long
Dim vTemp As Variant
'Two loops to bubble sort
For i = 1 To curaKeyNames.count - 1
For j = i + 1 To curaKeyNames.count
If curaKeyNames(i) < curaKeyNames(j) Then
'store the lesser item
vTemp = curaKeyNames(j)
'remove the lesser item
curaKeyNames.Remove j
're-add the lesser item before the
'greater Item
curaKeyNames.Add vTemp, vTemp, i
End If
Next j
Next i
Set EnumerateRegistryKeys = curaKeyNames
End Function
Sub main()
Set swApp = Application.SldWorks
Set swModel = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
FilePath = swModel.GetPathName
FileName = Replace(UCase(Dir(FilePath)), ".SLDPRT", "")
tempDir = CreateObject("WScript.Shell").ExpandEnvironmentStrings("%Temp%")
tempFileName = tempDir & "" & FileName & ".STL"
' need to change this
' Back up the current STL options so that we can restore them later.
stlBinaryFormat = swApp.GetUserPreferenceToggle(swUserPreferenceToggle_e.swSTLBinaryFormat)
stlQuality = swApp.GetUserPreferenceIntegerValue(swUserPreferenceIntegerValue_e.swSTLQuality)
swApp.SetUserPreferenceToggle swUserPreferenceToggle_e.swSTLBinaryFormat, True ' Use binary STL
swApp.SetUserPreferenceIntegerValue swUserPreferenceIntegerValue_e.swSTLQuality, swSTLQuality_Fine ' Up the quality
' Figure out where Cura is installed.
Const HKEY_LOCAL_MACHINE = &H80000002
strKeyPath = "SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
' Get all possible Cura locations
Dim curaDirNames As Collection
Set curaDirNames = EnumerateRegistryKeys(HKEY_LOCAL_MACHINE, strKeyPath)
If curaDirNames.count = 0 Then
MsgBox "Cannot find Cura on this computer.", vbInformation + vbOKOnly, "Cannot find Cura"
End If
Dim curaName As String
curaName = curaDirNames.Item(1) 'use the first one which is the latest version
' Get Cura location
Set myWS = CreateObject("WScript.Shell")
curaDir = myWS.RegRead("HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall" & curaName & "\DisplayIcon")
' remove the icon file
Dim lastSlashIdx As Long
lastSlashIdx = InStrRev(curaDir, "")
curaDir = Left(curaDir, lastSlashIdx)
Part.ClearSelection2 (All) ' Clear the selection. We want everything in the current document.
Set Part = swApp.ActiveDoc
Part.SaveAs tempFileName
' Restore the options
swApp.SetUserPreferenceToggle swUserPreferenceToggle_e.swSTLBinaryFormat, stlBinaryFormat
swApp.SetUserPreferenceIntegerValue swUserPreferenceIntegerValue_e.swSTLQuality, stlQuality
Shell """" & curaDir & "Cura.exe"" --single-instance " & """" & tempFileName & """"
End Sub

### CODE REVIEW

**Comment by nallath** [comment]
Uuh, you're trying to merge all changes that have been made in master to 2.7. I'm pretty sure that's not what you want, right?

**Comment by RichardB95** [comment]
This is my first time contributing to a git hub forum so I'm not quite sure how I'm supposed to go about it. The modifications that I made were to solid works plugin. Perhaps you can give me some guidance as to where I should post this.

**Comment by nallath** [comment]
The solid works plugin is hosted here; https://github.com/Ultimaker/CuraSolidWorksPlugin
What you should do it create a fork of this plugin, make your changes, commit those (on your fork). Then you can do a pull request between that fork and our code.

**Comment by nickthetait** [comment]
Also here is a little more detailed instructions https://help.github.com/articles/creating-a-pull-request/

**Pull request closed without merging**
