### PR TITLE
Add native CAD plugin to Enterprise edition

### PR DESCRIPTION
**Pull request by jellespijker**
The native CAD plugin has been added to the requirements and reference copy operations in the Conan data file and Conan file script. Now the native CAD plugin will only be included if the enterprise build flag is set. This ensures that unnecessary dependencies are not brought into non-enterprise builds.

> [!CAUTION]
> Untested just a quick port you also might want to validate that native_cad_plugin version 2.0.0 is indeed the latest released version

# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Printer definition file(s)
- [ ] Translations

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Operating System:

# Checklist:

- [X] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [X] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have uploaded any files required to test this change

### CODE REVIEW

**Comment by wawanbreton** [comment]
Is this change required for 5.7 ?

**Comment by jellespijker** [comment]
If we want a 5.7 Enterprise with the CAD plugin bundled yes

**Comment by jellespijker** [comment]
But this isn't needed for the beta ;-)

**Comment by wawanbreton** [comment]
Ok, so maybe merge it after 5.7 release ? I'm a bit scared of side-effects, so if we don't need it yet, I'd prefer to wait.

**Comment by jellespijker** [comment]
I would just merge this for the stable release,  otherwise you have the same weird version issue we had with 5.6.0 and 5.6.0+Enterprise versions. Which was a hack.

By not merging it for the creation of 5.7.0 conan release package, you're basically adding a new feature later.

imo the risk is limited

**Review by wawanbreton — APPROVED** [review]
Well, let's do it then

**Pull request merged**
