### PR TITLE
Create ubuild-3d_mr_bot_280.def.json

### PR DESCRIPTION
**Pull request by uBuild-3D**
Machine definition of MrBot280 3D printer by www.ubuild-3d.com
Thanks

### CODE REVIEW

**Comment by Appesteijn** [comment]
Looks good

**Comment by Appesteijn** [comment]
Both Fine and Draft quality have an LH of 0.2 is this what you want?

**Comment by uBuild-3D** [comment]
I'll answer your asap. Thanks

**Comment by Vandrasc** [comment]
Hi @uBuild-3D, could you please confirm the layer height of Fine and Draft, thanks! For the rest, it looks good indeed!

**Comment by fieldOfView** [comment]
The printer definition should not have a layer height set, but it should set a preferred quality. See https://github.com/Ultimaker/Cura/commit/e897431c959491a8cf27fbf275bd2bcabdb15d01#diff-d9718dd9a2eecf1fe13c187b85da7e36

**Comment by uBuild-3D** [comment]
The layer height of Fine is 0,1mm and Draft is 0,2mm

**Comment by Ghostkeeper** [comment]
I've set the default layer height via the quality profile now: 05c034558dfe88e4c3ca6e12b023ff1291baea27

That should resolve this issue.

**Pull request merged**
