### PR TITLE
skriware 2 print settings update

### PR DESCRIPTION
**Pull request by Lukkoz**
quality profiles for Skriware 2 added.
def.json updated with new settings resolve problems fixed for raft parameters.

### CODE REVIEW

**Comment by Lukkoz** [comment]
Is this all I need to do to get my changes included in Cura 4.9 upade?

**Comment by Ghostkeeper** [comment]
Yeah, looks like it, from your side. There's a lot to do for us before then though so no guarantees! We need to give this a good test too.

**Comment by Lukkoz** [comment]
Do you need to do additional tests before you merge my commit to master?

**Comment by Ghostkeeper** [comment]
We also do a manual review and test whether it all loads correctly, yes.

**Comment by Lukkoz** [comment]
Will there be a chance to fix something if your manual review shows some issues? I tested those files with the current release (Cura 4.8) and they load correctly, but as I understand you are planning some changes.

**Comment by Ghostkeeper** [comment]
If we have issues in the review we'll indicate those to you, unless it's like really simple and we can easily change it ourselves.

If we break things ourself in your PR after you've branched off it's really our own fault and we'll do our best to update it for you. If we think that might have issues with the print quality we'll always try to involve you first.

**Comment by Lukkoz** [comment]
Hi I saw that a 4.9 version was released, but my commit was merged to the master branch and changes are not available in the release. Is there a problem with it? Or did I miss something in the pull request flow?

**Comment by konskarm** [comment]
@Lukkoz you have correctly pointed to our master branch, which means that, once the PR is merged, the changes will be available in the next Cura release.

**Comment by Lukkoz** [comment]
@konskarm What should I do to get my PR merge accepted? As I understand someone with write access should accept the merge? Is there some additional procedure for it? I asked @Ghostkeeper before and he replied that it is all from my side. Maybe I am not getting this process right? :(

**Comment by konskarm** [comment]
Ghostkeeper actually said that all is well on your side. The past few weeks we have been very busy and our developers did not have time to review and test your PR. Once it is picked up, we will let you know whether something comes out of the review/test that needs to be fixed.

**Comment by Lukkoz** [comment]
Ok thank you very much then :)

**Pull request merged**
