### PR TITLE
[CURA-1696] Using Uranium's translation tools

### PR DESCRIPTION
**Pull request by thopiekar**
Depends on: https://github.com/Ultimaker/Uranium/pull/160

### CODE REVIEW

**Comment by thopiekar** [comment]
Just waiting until my changes to through my PPA, so I test my work here and be 100%ly sure that everything works.

**Comment by thopiekar** [comment]
Correctly outputs this on older Uranium:
```
CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    UraniumTranslationTools


CMake Error at CMakeLists.txt:26 (CREATE_TRANSLATION_TARGETS):
  Unknown CMake command "CREATE_TRANSLATION_TARGETS".


-- Configuring incomplete, errors occurred!
See also "/foo/bar/Cura/build/CMakeFiles/CMakeOutput.log".
```

**Comment by thopiekar** [comment]
Now with our new Uranium:
```
-- Using CURA_BINARY_DATA_DIRECTORY from set of environment variables...
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
CMake Warning at /usr/share/cmake-3.5/Modules/UraniumTranslationTools.cmake:87 (message):
  GETTEXT_MSGINIT_EXECUTABLE is undefined!

  Skipping to create i18n-create-po* targets...
Call Stack (most recent call first):
  CMakeLists.txt:26 (CREATE_TRANSLATION_TARGETS)


CMake Warning at /usr/share/cmake-3.5/Modules/UraniumTranslationTools.cmake:98 (message):
  CURA_BINARY_DATA_DIRECTORY is not set!
Call Stack (most recent call first):
  CMakeLists.txt:26 (CREATE_TRANSLATION_TARGETS)


-- Creating target i18n-update-po
-- Creating target i18n-update-mo
-- Creating target i18n-update-po-de
-- Creating target i18n-create-mo-de
-- Creating target i18n-update-po-en
-- Creating target i18n-create-mo-en
-- Creating target i18n-update-po-es
-- Creating target i18n-create-mo-es
-- Creating target i18n-update-po-fi
-- Creating target i18n-create-mo-fi
-- Creating target i18n-update-po-fr
-- Creating target i18n-create-mo-fr
-- Creating target i18n-update-po-it
-- Creating target i18n-create-mo-it
-- Creating target i18n-update-po-nl
-- Creating target i18n-create-mo-nl
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3.4.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /foo/bar/Cura/build
```

Let's see what our build system says...

**Comment by Ghostkeeper** [comment]
Why was this merged?

**Comment by thopiekar** [comment]
The task of CURA-1696 was to remove the duplicate code across UM and Cura.
In UM the CMake code, which is creating our translation targets (you probably remember the work I made on this half a year ago,) was moved into a separate CMake module. Now the duplicate code here can be savely removed as this module from UM is now being used.

**Comment by thopiekar** [comment]
As @sedwards2009 said that I can merge everything when I'm ready (and I was ready when I tested it here on my own desktop), I merged it here.
Apparently we have problems because of that in cura-build, but I found also a solution for that.

**Comment by thopiekar** [comment]
The WIP was misleading here, sorry.

**Pull request merged**
