### PR TITLE
Add Type A Machines series 1 2014 definition and mesh

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds the definition and mesh from https://github.com/Ultimaker/Cura/pull/1859

I have removed the references for ````"inherits": "typeamachines",``` and ```"platform_texture": "series1_pro_txt.png",``` because those files were not provided. I have also changed the category to "Other". Finally I tweaked the platform offset to prevent z-fighting.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Hopefully for @EldRick, this commit can still be cherry-picked to the 2.6 branch.

**Comment by Ghostkeeper** [comment]
Devs, see CURA-3865.

**Comment by BagelOrb** [comment]
Where do you get this info from, man? Do you even have a Type A Machine?!
Or did you just get this info from the Type A Machines version of Cura?

**Comment by fieldOfView** [comment]
See the linked issue/failed PR here: https://github.com/Ultimaker/Cura/pull/1859
(That one can be closed now too)

**Pull request merged**
