### PR TITLE
Unify pause at height scripts

### LINKED ISSUE #7198: make the "pause at height" post process  context based
**Is your feature request related to a problem? Please describe.**
The Post process list is in my opinion a mess. instead of having one entry for "pause of layer height"
we have four entries that aren't even listed directly after another. And the difference is basically the used commands. If you don't read every entry it is possible to use the false one, resulting in abortet prints ,ect.

**Describe the solution you'd like**
make it context sensitive to the printer and its code setting.

**Describe alternatives you've considered**
make a dropdown  menufor the version in the setting of the process

**Affected users and/or printers**
Basically everyone that uses Boards that doesn't use the marlin code set

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds an option to the pause at height script to set the pause method (gcode command), instead of having 4 different pause at height scripts. This should make maintenance of these script less work, since fixes don't have to be made in 4 scripts. It also gives feature parity to all the different flavors.

TODO:
* ~automatically suggest the right method for the current printer definition~ see a7e23ba
* ~add repetier-specific parking if repetier flavor is selected~ see c87ee61
* ~make "griffin" a method~ see 87633e7
* ~consider the need to upgrade configurations for projects including a pause at height script~ see 321693d

Fixes #7198

### CODE REVIEW

**Comment by nallath** [comment]
I think we should add an upgrade script for this (one way or another). Old projects will otherwise not be loaded correctly.

**Comment by fieldOfView** [comment]
I agree, hence the WIP tag.

**Comment by fieldOfView** [comment]
For the upgrade script, I'll wait for #7247 to be merged (or rejected), since that sets up the basics for a 4.5 to 4.6 upgrade script.

**Comment by fieldOfView** [comment]
Also see https://github.com/Ultimaker/Cura/issues/6099

**Comment by mahtDFR** [comment]
Relevant? #7227

**Comment by agibson2** [comment]
Will this make is so that I don't need to maintain the hacked Octoprint @pause script?  For octoprint, all that should be inserted is a single @pause line.  Octoprint handles the scripts for the actual gcode commands to make pause and resume work.

https://community.ultimaker.com/topic/24105-post-processing-script-for-octoprints-pause-feature/

**Comment by fieldOfView** [comment]
I'm waiting for #7427 to merge, in order not to create a big merge conflict. There needs to be a versionupgrade

**Comment by nallath** [comment]
@fieldOfView https://github.com/Ultimaker/Cura/pull/7227 is merged.

**Comment by fieldOfView** [comment]
Now that there is an upgrade step for 4.6 to 4.7 in master, I can add my work on the Pause at Height scripts to that.

**Comment by fieldOfView** [comment]
Ready for review

**Comment by ninovanhooff** [comment]
Internal reference: CURA-7453

**Comment by agibson2** [comment]
Does this new revised unified script have an option to only insert a single @pause line for Octoprint?  Octoprint handles the commands to send to the printer to implement the pause and resume (resume on the web GUI)?  Looking at the code it seems like the only option for @pause is to use 'repetier' but I see other commands being put in too.

**Comment by fieldOfView** [comment]
> Does this new revised unified script have an option to only insert a single @Pause (lower case p) line for Octoprint?

Did any of the previous scripts? If not, then neither does this unified one. It can easily be added, but please open a new feature request for that.

**Comment by agibson2** [comment]
Feature request added for Octoprint...
https://github.com/Ultimaker/Cura/issues/7842

**Pull request merged**
