### PR TITLE
Add support for Peopoly Moai (SLA)

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds a definition and a set of quality profiles for the upcoming Peopoly Moai:
https://www.kickstarter.com/projects/1554809440/moai-affordable-high-resolution-laser-sla-3d-print

Note that this printer is an SLA printer. Because of this the definition disables/hides a number of features (materials, temperatures (nozzle, buildplate), fan cooling, retraction, supports). Supports are intended to be added using a different tool before slicing.  

In cooperation with Shu (Mark) Peng from Peopoly

### CODE REVIEW

**Comment by nallath** [comment]
Why does it inherit ultimaker machines? That doesn't make a whole lot of sense.

**Comment by fieldOfView** [comment]
Hmm, weird. I'll fix that.

**Comment by fieldOfView** [comment]
Fixed

**Comment by jackha** [comment]
The definition didn't work without an inheritance. I've added inherits fdmprinter (although it isn't an fdmprinter) and merged it. Maybe we can add an slaprinter.def.json ?

**Comment by fieldOfView** [comment]
'doh! I'm an idiot.

**Comment by fieldOfView** [comment]
> Maybe we can add an slaprinter.def.json ?

That slaprinter.def.json would still need to inherit from fdmprinter. But it could be nice if more SLA printer manufacturers find Cura without materials, temperatures & support usefull

**Comment by jackha** [comment]
No you're not an idiot :stuck_out_tongue_winking_eye:
Yes I hope more SLA printer manufacturers find Cura useful, would be awesome!

**Pull request merged**
