### PR TITLE
Added experimental settings to print small features slower.

### PR DESCRIPTION
**Pull request by smartavionics**
This PR adds settings that tell Cura to print outlines that are shorter than some threshold length slower. The threshold length can be set directly or it is computed from a small hole diameter.

Printing the walls of very small holes can be tricky and slowing down helps with adhesion and accuracy.

### CODE REVIEW

**Comment by smartavionics** [comment]
Provides solution for https://github.com/Ultimaker/Cura/issues/3622.

**Comment by Ghostkeeper** [comment]
See discussion over at https://github.com/Ultimaker/CuraEngine/pull/779

**Comment by jackha** [comment]
Devs: CURA-5503

**Comment by jackha** [comment]
Hi @smartavionics , why did you close the PRs?

**Comment by smartavionics** [comment]
People still want this so reopening.

**Comment by Ghostkeeper** [comment]
Developers, see the new ticket CURA-6464 that was created after re-opening.

**Comment by rburema** [comment]
(P.S. The failed check happens in master too, has nothing to do with this PR, we've got a ticket to fix that soonish.)

**Pull request merged**
