### PR TITLE
Add profile for Ender3 v2

### PR DESCRIPTION
**Pull request by pcartwright81**
Add profile for Ender3 v2

### CODE REVIEW

**Comment by konskarm** [comment]
I notice that the only difference between the Ender3 and the Ender3v2 files is the size of the printer. Keep in mind that the Ender3 used to also be 220x220x250mm but it was changed in commit https://github.com/Ultimaker/Cura/commit/726561bf309616107ad874d4e508b3a3ec9e5701 after the discussion in https://github.com/Ultimaker/Cura/issues/6267. 

Is there a change the same situation will arise in the Ender3v2? Because if that's the case, I think the Ender3v2 users can be covered by the Ender3 printer profile so that we don't have to have two different printer profiles that are exactly the same.

**Comment by emarforio** [comment]
I for one would appreciate to have the "duplicate" config. I am very new to 3D-printing and just bought my first printer, an Ender 3 V2, and were a bit confused and put off by not finding the exact model at first. So even if the config is the same it is nice to show newbies like me that their device is supported out of the box.

**Comment by pcartwright81** [comment]
> I for one would appreciate to have the "duplicate" config. I am very new to 3D-printing and just bought my first printer, an Ender 3 V2, and were a bit confused and put off by not finding the exact model at first. So even if the config is the same it is nice to show newbies like me that their device is supported out of the box.

Agree.  It was a little confusing at first why I had to manually copy the profile and set the dimensions.  Didn't know how to respond to the pull request comment.  Was hoping someone would say whether or not the dimensions needed to be updated or not.

**Comment by mdehaas** [comment]
I do not agree that because users are confused (and not willing to investigate further) there is a need to create duplicate profiles. This causes changes to the profile (and possibly code) need to be applied on multiple files. This will eventually lead to drift (forgotten or orphaned profiles). The solution in my opinion should be that if a profile applies to multiple vendors/series/models/editions there should be a possibility to add more than one of the above to the profile.
This however will lead to a lengthy list in the configuration dialog so a new 'user journey' has to be modelled around that.

**Comment by Ghostkeeper** [comment]
For one, it would be nicer to inherit from the Ender 3 (v1) profile if it's just the size that is different, and then override just that size. That way if other things change in the Ender 3 profile, like an improved start g-code, it would also change for the v2.

The profiles are already shared among all Creality printers anyway, so it wouldn't lead to duplication there, or outdatedness.

Another possibility instead of this would be to add a machine action that allows the user to choose which edition of the printer they have. The Ultimaker Original does something like that, where you get another screen after adding the printer where the user can select whether they have the heated bed installed in their printer or not.

**Comment by mattpker** [comment]
To solve the issue of confusion, the profile for "Ender-3" could be renamed to "Ender-3 (v1/v2)".

**Comment by Medduus** [comment]
in  the endeer slicer that is based on cura u can get the profiles for the v2

**Comment by amweiss** [comment]
> I notice that the only difference between the Ender3 and the Ender3v2 files is the size of the printer. Keep in mind that the Ender3 used to also be 220x220x250mm but it was changed in commit [726561b](https://github.com/Ultimaker/Cura/commit/726561bf309616107ad874d4e508b3a3ec9e5701) after the discussion in #6267.
> 
> Is there a change the same situation will arise in the Ender3v2? Because if that's the case, I think the Ender3v2 users can be covered by the Ender3 printer profile so that we don't have to have two different printer profiles that are exactly the same.

This is correct, the bed size between the Ender 3 and Ender 3v2 is the same. It's actually 235x235x250 but only prints to 220x220x250. I would agree with the above suggestion to just rename the profile to include "(v1/v2)"

**Comment by digitalfrost** [comment]
Can be closed since Rename Ender-3 profile to include v2 #12442 has been merged.

**Pull request closed without merging**
