### PR TITLE
Added machine settings of German RepRap NEO machine

### PR DESCRIPTION
**Pull request by simonCor**
This is the machine: https://www.germanreprap.com/produkte/3d-drucker/neo-3d-drucker/

The configuration works fine fine for mine.

### CODE REVIEW

**Comment by nallath** [comment]
Could you also add another platform model? Now it uses the UM2 platform, which might be a bit confusing.

**Comment by simonCor** [comment]
I understand - I will see if I can a custom one for the Neo.

**Comment by simonCor** [comment]
Ok. It now has a custom build platform

**Comment by nallath** [comment]
Allright, thanks for putting in the work :+1:

**Comment by TZanke** [comment]
Hello,

thank you for your work.

I found a problem with the orientation of the build platform. I have to rotate the objects 90° clockwise to get the expected result in prints.

Is it a problem of the custom build platform STL or X/Y zero positions in the JSON file?

Any idea how to fix this?

**Pull request merged**
