### PR TITLE
update speed_wall

### PR DESCRIPTION
**Pull request by heed818**
update speed_wall for da Vinci Super

### CODE REVIEW

**Comment by heed818** [comment]
speed parameter updating...

**Comment by heed818** [comment]
Hi Sir @Ghostkeeper ,after the merge last month we modify some parameters.
could these be able to merge in 4.13 @@?
thanks.

**Comment by heed818** [comment]
> 

Hi Sir @Ghostkeeper @nallath , we only modify the value of parameters and don't change the structure of XYZprinting because there are some parameter is not correct.
If there have anything wrong to merge in 4.13,please feel free to let us know
,thanks

**Comment by Ghostkeeper** [comment]
Generally pinging us for these PRs serves only to frustrate. I tend to process them from old to new, and there were people that had still waited longer than you. Sorry that it takes a long time.

Is there a reason why you chose to edit these 160 files instead of setting the retraction and speed settings in a higher-level profile, such as the Da Vinci printer profile? In fact, `retraction_prime_speed = =retraction_speed` should already be the default so I don't see why it gets overridden at all?

**Comment by heed818** [comment]
Thanks for your effort, and we mainly want to modify two printers' setting printbed_heating to "false ",retract_prime_speed is not the urgent modify .

**Comment by Ghostkeeper** [comment]
Okay, do you want to remove the remaining changes then, or fix them?

**Comment by heed818** [comment]
Hi Sir @Ghostkeeper ,
We remove retraction_prime_speed = =retraction_speed in all profiles.
Thank you :)

**Comment by heed818** [comment]
Hi Sir @Ghostkeeper ,
We remove retraction_prime_speed = =retraction_speed in all profiles.
Thank you :)

**Comment by heed818** [comment]
Hi Sir @Ghostkeeper ,i fix the settings and do Fetch,but i got:
"/__w/Cura/Cura/.git: Permission denied"
how can i fix it and commit my fix setting it @@?  
Thank you.

**Comment by Ghostkeeper** [comment]
> Hi Sir @Ghostkeeper ,i fix the settings and do Fetch,but i got:
"/__w/Cura/Cura/.git: Permission denied"
how can i fix it and commit my fix setting it @@?
Thank you.

It's not something we do. Since Cura is a public repository, everyone can pull. I think you might have been using an SSH key that was not connected to your account, or maybe expired.

I see that you removed those setting overrides, thank you!

**Review by Ghostkeeper — APPROVED** [review]

**Comment by Ghostkeeper** [comment]
Seems to work. Thanks for the contributions!

**Pull request merged**
