### PR TITLE
add prusa I3 XL  machine profile and STL

### PR DESCRIPTION
**Pull request by guigashm**
add prusa I3 XL  machine profile and STL

### CODE REVIEW

**Comment by nallath** [comment]
Thanks for adding it :)

**Comment by guigashm** [comment]
;DD glad to help.

**Comment by thopiekar** [comment]
@nallath: there is a "icon" property pointing at a ultimaker icon. Is this correct?!

**Comment by nallath** [comment]
If i recall correctly, the icon bit in the machine is depricated. We should really remove that, but we never got to it.

**Pull request merged**
