### PR TITLE
Added machine_cooling_fan_number to the machine settings category.

### PR DESCRIPTION
**Pull request by smartavionics**
Defaults to 0, most people should never need to change this.

See https://github.com/Ultimaker/CuraEngine/pull/797.

Fixes issue discussed in https://community.ultimaker.com/topic/23371-fan-problem/.

### CODE REVIEW

**Comment by jackha** [comment]
Devs: CURA-5502

**Comment by ianpaschal** [comment]
I'm not able to test this; don't see the setting showing up in Cura. Not sure why...

**Comment by ianpaschal** [comment]
I'm not seeing these fan settings show up.

**Comment by smartavionics** [comment]
You have to install @fieldOfView's Printer Settings plugin (possibly broken at the moment due to master branch changes?)

**Comment by ianpaschal** [comment]
Ah I was looking in the Cooling section. My bad.

**Comment by ianpaschal** [comment]
See comment on related Cura Engine PR. 😉

**Comment by ianpaschal** [comment]
Will not be merged. See 
https://github.com/Ultimaker/CuraEngine/pull/797 for discussion.

**Pull request closed without merging**
