### PR TITLE
Objectlist additions

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR adds some information to the object list:
* indicates the extruder(-color) used for the model (for multi-extrusion printers only)
* shows the meshtype if the model is not a normal mesh
* shows the number of per model setting overrides
* indicates models that are outside the build volume

which box is which?
Clicking the mesh-type or per-model-settings-count will open the Per Model Settings tool panel.

The PR also adds a small fix to ensure that support_mesh models are rendered using the color of the support_extruder.

### CODE REVIEW

**Comment by fieldOfView** [comment]
I see Test_ObjectsModel needs some updating now that I have added a number of roles to the model.

**Comment by fieldOfView** [comment]
Tests are fixed

**Comment by Ellecross** [comment]
jesus christ. This is awesome. @fieldOfView you are the man.

**Comment by nallath** [comment]
For our reference: CURA-7405

**Pull request merged**
