### PR TITLE
Simplified Chinese Translate

### PR DESCRIPTION
**Pull request by alphaarea**
Add Chinese Translate
But only translated partial word

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
We can't really merge this until there is a complete translation. A lot of these translate to empty, so the text would disappear.

**Comment by LipuFei** [comment]
Hi @alphaarea, a few remarks:
- I suggest to use code `zh-CN` instead of `cn` (reference: [ISO Language Code Table](http://www.lingoes.net/en/translator/langcode.htm)).
- Please don't leave untranslated or blank texts.
- Could you also put the language into the Dropdown list in `resources/qml/Preferences/GeneralPage.qml`, so you can actually select it in the GUI?

**Comment by ccjjmartin** [comment]
@LipuFei Should this PR be closed?  It looks like #2035 is going to be the PR that gets merged.

**Comment by Ghostkeeper** [comment]
The other PR has now been merged, which makes this one obsolete. Thank you, but sorry!

**Pull request closed without merging**
