### PR TITLE
Add profile for machine 3DMaker Starter

### PR DESCRIPTION
**Pull request by tvlgiao**
Hello, I would like to add our 3D Printer machine profile for Cura. Machine is 3DMaker Starter. See more: http://www.3dmaker.vn/may-in-3dmaker-starter/

### CODE REVIEW

**Comment by nallath** [comment]
Could you also add the 3D model for the build plate? You're still using the UM2 build plate

**Comment by tvlgiao** [comment]
Hi nallath, Thanks for your feedback. I'm designing the build plate. Will update it soon.

**Comment by tvlgiao** [comment]
Hi nallath, I uploaded the STL file of build plate. Also update the profile file. Thanks!

**Comment by awhiemstra** [comment]
Merged. Thank you!

**Comment by TMHogenhout** [comment]
There is one more problem with it when you actually add the printer. I'll give it a second look tomorrow. 

Version: master
Platform: Linux-3.19.0-18-generic-x86_64-with-Ubuntu-15.04-vivid
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "/home/tamara/Desktop/Uranium/UM/Qt/Bindings/AvailableMachinesModel.py", line 40, in createMachine
    machine.loadSettingsFromFile(Resources.getPath(Resources.SettingsLocation, file))
  File "/home/tamara/Desktop/Uranium/UM/Settings/MachineSettings.py", line 107, in loadSettingsFromFile
    category.fillByDict(value)
  File "/home/tamara/Desktop/Uranium/UM/Settings/SettingsCategory.py", line 39, in fillByDict
    setting = Setting(key, self._i18n_catalog, default = value["default"], type = value["type"])
KeyError: 'type'

**Comment by awhiemstra** [comment]
That's because the profile was based on the 15.06 fdmprinter.json and master changed a lot of things around, so the merging of customised settings fails.

**Pull request merged**
