### PR TITLE
Added definition for Creatable D3

### PR DESCRIPTION
**Pull request by jbkim**
Creatable D3 https://creatablelabs.com/

### CODE REVIEW

**Comment by nallath** [comment]
For our reference; CURA-6084

**Comment by jbkim** [comment]
@nallath What's the meaning of 6064?

**Comment by nallath** [comment]
It's our ticket number in Jira (our internal issue tracker). It basically means that we've added it to our sprint so that someone will have a look at it at some point.

**Comment by nallath** [comment]
The profiles don't actually work. There is a json error with them and when you try to load them into Cura, it fails to add the machine.

**Comment by jbkim** [comment]
@nallath I just fixed the json error. :)

**Comment by nallath** [comment]
Did you actually test if this works? If you try to add the machine it fails. As far as I can see you didn't set the ID of the machine correctly in the extruder definition.

**Comment by jbkim** [comment]
@nallath I added the machine and it works but I can't see the Material menu under
setting > Extruder 1. Could you tell me how I can fix this?

**Comment by fieldOfView** [comment]
Remove the line ```"has_materials": false,``` from the machine definition file

**Comment by jbkim** [comment]
@nallath Thanks. I fix it. ;)

**Comment by jbkim** [comment]
@nallath Hi, I expected this update applied to 4.0-beta but it didn't. Is there any problem?

**Comment by Ghostkeeper** [comment]
Sorry. It was merged to master, which is to be released in 4.1.

We've split off the 4.0 beta from the master code base in December, before the first beta. We do that to allow the 4.0 release to become more stable while we work on new things for 4.1. So as a rule, while the beta is going on, we won't add new things to keep the release stable. That includes new printers.

The 4.0 beta has been exceptionally long so it looks a bit strange, I understand.

**Pull request merged**
