### PR TITLE
Infill outline count

### PR DESCRIPTION
**Pull request by BagelOrb**
Frontend PR for:
https://github.com/Ultimaker/CuraEngine/pull/775

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-5401.

**Comment by BagelOrb** [comment]
Somehow you already merged the setting:
image
Something really strange happened there...

**Comment by BagelOrb** [comment]
calling @alekseisasin

**Comment by BagelOrb** [comment]
This commit seems to be the culprint: 729569034d38c9b7d599f63347bcce1c691a9c95

**Comment by BagelOrb** [comment]
Ah you made this code to review my backend PR - not realizing I had already made this PR for that.
Then you forgot you had changed this code when you made your next commit.

Always commit using `git add -p` !!

**Comment by BagelOrb** [comment]
This branch now fixes your mistake, so you don't need to do that yourself.

**Comment by alekseisasin** [comment]
@BagelOrb , you are right, I was testing your PR and committed. Thank you that you mentioned it.

**Pull request merged**
