### PR TITLE
add KOONOVO printer

### PR DESCRIPTION
**Pull request by KOONOVO3DPrinter**
add a printer: KOONOVO Pyramid   size:310*310*400mm    
KOONOVO Pyramid
KOONOVO Pyramid-1

### CODE REVIEW

**Comment by fieldOfView** [comment]
This is an invalid pull request. A pull request is something very different from a feature request.

**Comment by KOONOVO3DPrinter** [comment]
发件人：黄剑锋&nbsp;&nbsp;
深圳市嘉禾三维科技有限公司---专业3D打印机及配件生产厂家，自主研发，超高性价比。


Tel：13682452915
QQ：364112187
邮箱：koonovo@foxmail.com
公司：深圳市嘉禾三科技有限公司


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ultimaker/Cura"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 下午4:01
收件人:&nbsp;"Ultimaker/Cura"<Cura@noreply.github.com&gt;;
抄送:&nbsp;"小黄"<koonovo@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Ultimaker/Cura] add KOONOVO printer (#8395)





 
This is an invalid pull request. A pull request is something very different from a feature request.

**Comment by KOONOVO3DPrinter** [comment]
How should I request to add my 3D printer directly, thank you



发件人：黄剑锋&nbsp;&nbsp;
深圳市嘉禾三维科技有限公司---专业3D打印机及配件生产厂家，自主研发，超高性价比。


Tel：13682452915
QQ：364112187
邮箱：koonovo@foxmail.com
公司：深圳市嘉禾三科技有限公司


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ultimaker/Cura"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 下午4:01
收件人:&nbsp;"Ultimaker/Cura"<Cura@noreply.github.com&gt;;
抄送:&nbsp;"小黄"<koonovo@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Ultimaker/Cura] add KOONOVO printer (#8395)





 
This is an invalid pull request. A pull request is something very different from a feature request.

**Comment by konskarm** [comment]
A pull request is a change that you would like to contribute to the Cura codebase. As @fieldOfView mentions, what you were searching for is a feature request, which is done via [this link](https://github.com/Ultimaker/Cura/issues/new?assignees=&labels=Type%3A+New+Feature&template=feature_request.md&title=). In any case, even if you make a feature request for a 3rd party printer definition to be added in Cura, it will be rejected.

The Cura team relies on community contributions when it comes to 3rd party printers, since we do not have access to every possible printer out there. If you manage to create the printer definition yourself, we will be more than happy to review it and accept it so that it becomes available in the following Cura releases. You can refer to [this guide](https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura) and draw from already existing 3rd party printer definitions found in the [resources folder](https://github.com/Ultimaker/Cura/tree/master/resources) in Cura to achieve that.

For the time being, I am closing this pull request.

**Comment by KOONOVO3DPrinter** [comment]
&nbsp;I see. Thank you
&nbsp;

发件人：黄剑锋&nbsp;&nbsp;
深圳市嘉禾三维科技有限公司---专业3D打印机及配件生产厂家，自主研发，超高性价比。


Tel：13682452915
QQ：364112187
邮箱：koonovo@foxmail.com
公司：深圳市嘉禾三科技有限公司


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Konstantinos Karmas"<notifications@github.com&gt;; 
发送时间: 2020年9月17日(星期四) 晚上9:47
收件人: "Ultimaker/Cura"<Cura@noreply.github.com&gt;; 
抄送: "小黄"<koonovo@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Ultimaker/Cura] add KOONOVO printer (#8395)





 
A pull request is a change that you would like to contribute to the Cura codebase. As @fieldOfView mentions, what you were searching for is a feature request, which is done via this link. In any case, even if you make a feature request for a 3rd party printer definition to be added in Cura, it will be rejected.
 
The Cura team relies on community contributions when it comes to 3rd party printers, since we do not have access to every possible printer out there. If you manage to create the printer definition yourself, we will be more than happy to review it and accept it so that it becomes available in the following Cura releases. You can refer to this guide and draw from already existing 3rd party printer definitions found in the resources folder in Cura to achieve that.
 
For the time being, I am closing this pull request.

**Comment by KOONOVO3DPrinter** [comment]
This is my 3D printer configuration file, please review it, if possible, please add it in the next version，Thank&nbsp;you&nbsp;very&nbsp;much.&nbsp;



发件人：黄剑锋&nbsp;&nbsp;
深圳市嘉禾三维科技有限公司---专业3D打印机及配件生产厂家，自主研发，超高性价比。


Tel：13682452915
QQ：364112187
邮箱：koonovo@foxmail.com
公司：深圳市嘉禾三科技有限公司


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ultimaker/Cura"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 晚上9:47
收件人:&nbsp;"Ultimaker/Cura"<Cura@noreply.github.com&gt;;
抄送:&nbsp;"小黄"<koonovo@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Ultimaker/Cura] add KOONOVO printer (#8395)





 
A pull request is a change that you would like to contribute to the Cura codebase. As @fieldOfView mentions, what you were searching for is a feature request, which is done via this link. In any case, even if you make a feature request for a 3rd party printer definition to be added in Cura, it will be rejected.
 
The Cura team relies on community contributions when it comes to 3rd party printers, since we do not have access to every possible printer out there. If you manage to create the printer definition yourself, we will be more than happy to review it and accept it so that it becomes available in the following Cura releases. You can refer to this guide and draw from already existing 3rd party printer definitions found in the resources folder in Cura to achieve that.
 
For the time being, I am closing this pull request.

**Comment by Ghostkeeper** [comment]
Please note that attachments to e-mail replies don't get added to Github. If you had an attachment to that message, we can't see it. You'd need to go to the Github website to post it.

**Pull request closed without merging**
