### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.po,*.pot -L childs,initialy,lod,ned,te,slicable,sur,tutoriels,wont`

### CODE REVIEW

**Comment by luzpaz** [comment]
Please review 9b203c8 carefully as it modifies source code

**Comment by nallath** [comment]
> Found via `codespell -q 3 -S *.po,*.pot -L childs,initialy,lod,ned,te,slicable,sur,tutoriels,wont`

Sometimes you see a solution that makes you think; Why didn't I come up with that...

**Comment by nallath** [comment]
For our reference: https://jira.ultimaker.com/browse/CURA-8544

**Comment by nallath** [comment]
I've fixed the failing tests in 5ea0d927cababbe80043b70fddacc74d4dda60c1

**Pull request merged**
