### PR TITLE
FEATURE: Support wsh usb driver (for mac)

### PR DESCRIPTION
**Pull request by Torsten85**
This pr adds support for the wch driver. This driver is e.g. necessary to connect an anet a8 to a mac.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Shouldn't the non-usb-only path also include the wchusb* variants?

**Comment by Ghostkeeper** [comment]
I'd add it there too, but I don't know how to go about testing my code.

Should we just try without testing? Can't really hurt in this case, perhaps.

**Comment by thopiekar** [comment]
I don't think it will hurt. We are just expanding the list..
Additionally, as far as I know, we don't care about USB printing that much anymore, so I felt free to merge it directly.
Was it a bad idea?

**Comment by awhiemstra** [comment]
Nah, the worst that can happen is that we scan a few more devices to see if they are printers.

**Comment by Ghostkeeper** [comment]
Done in a3af887d3f6a9bd6ef16c6a3f675b6ec08b93756.

**Pull request merged**
