### PR TITLE
Add Minimum to Adaptive Layers Maximum Variation

### PR DESCRIPTION
**Pull request by MariMakes**
A negative value will result in a failed slice as mentioned here https://github.com/Ultimaker/Cura/issues/13749

Warning value of 0 is added

### CODE REVIEW

**Comment by fieldOfView** [comment]
Hey, your first Cura PR!

Please indent with spaces. not tabs.

**Comment by MariMakes** [comment]
Teehee. Hi @fieldOfView 👋 
I'd like to think that https://github.com/Ultimaker/Cura/pull/13448 was my first, but it was during a release period and I made a mistake. 

I think I fixed the indent issue. @jellespijker

**Review by casperlamboo — APPROVED** [review]
Looking good! 😎

**Comment by jellespijker** [comment]
LGTM;

Now the challenge of fixing the merge conflict @MariMakes Shout-out if you need help

**Comment by MariMakes** [comment]
I've been using Notepad++, you need to turn on a specific setting for changing the tabs to spaces. 😊 

image

**Pull request merged**
