### PR TITLE
Fix sending commands in rapid succession over USB

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR fixes sending commands in rapid succession over USB. When sending multiple commands using sendCommand(), it can happen that a command is sent before a previous command is fully received.

Probably contributes to #3050

### CODE REVIEW

**Comment by alekseisasin** [comment]
I tested this solution and it does not work for UM Original+. Has same issue.
I think we need make a special command for UM Original+ firmware 'Marlin V1', -> (G28 XYZ)

**Comment by fieldOfView** [comment]
I don't have an UMO+, so I cannot test this. 

It still baffles me how changing the head homing to also home the bed would fix this (for any printer). Does homing the bed work properly using the jogging controls on the UMO+?

How is the UMO+ firmware different from the UM2?

**Comment by fieldOfView** [comment]
Note that even if the PR does not fix the #3050 issue, it still fixes a possible overflow in the serial connection to USB printers, so I would still argue it needs to be merged. Perhaps @nallath could add his feedback, since het did a refactor of the USB printing code.

**Comment by alekseisasin** [comment]
UM+ does not recognize 'X' or 'Y' in G28. For this reason we had before only 'G28' .  
I do not mind to merge your pull request, because it might help to prevent USB commands overflow. I have wish to solve the initial issue.
The firmwares are:
UM2  firmware name is "Marlin Ultimaker2"
UM+  firmware name is "Marlin V1"

**Comment by fieldOfView** [comment]
What repo does the UMO+ firmware use? It is strange that G28 accepts the X & Y arguments just fine on my UMO and on my UM2.

**Comment by LipuFei** [comment]
@fieldOfView Conflicts to resolve...

**Comment by fieldOfView** [comment]
@LipuFei Done...

**Pull request merged**
